Repository googleapis/repo-automation-bots, pull requests merged in 2020-04, with the labels that each got.

#427 build: set AUTOSYNTH_MULTIPLE_COMMITS=true for context aware commits
  synth.py
Labels: automerge, cla: yes

#431 fix: sync repo settings changes
  packages/sync-repo-settings/src/sync-repo-settings.ts
  packages/sync-repo-settings/test/test.ts
Labels: cla: yes

#432 refactor: use the built-in .github config
  packages/header-checker-lint/src/header-checker-lint.ts
  packages/header-checker-lint/test/fixtures/config_copyright_holder.json
  packages/header-checker-lint/test/fixtures/config_copyright_holder.yml
  packages/header-checker-lint/test/fixtures/config_ignored_files.json
  packages/header-checker-lint/test/fixtures/config_ignored_files.yml
  packages/header-checker-lint/test/header-checker-lint.ts
Labels: cla: yes

#436 chore: remove duplicate mocha config
  .mocharc.json
Labels: automerge, cla: yes

#439 fix(sync-repo-settings): add logic to ignore certain repos, add tests
  packages/sync-repo-settings/src/required-checks.json
  packages/sync-repo-settings/src/sync-repo-settings.ts
  packages/sync-repo-settings/test/fixtures/repos.json
  packages/sync-repo-settings/test/test.ts
Labels: cla: yes

#440 fix(merge-on-green): address bugs related to status check name detection
  packages/merge-on-green/src/merge-logic.ts
  packages/merge-on-green/src/merge-on-green.ts
  packages/merge-on-green/test/merge-on-green.ts
Labels: cla: yes

#446 fix: drop prepare, which is broken with "npm ci"
  packages/auto-label/package.json
  packages/blunderbuss/package.json
  packages/buildcop/package.json
  packages/conventional-commit-lint/package.json
  packages/failurechecker/package.json
  packages/gcf-utils/package.json
  packages/header-checker-lint/package.json
  packages/label-sync/package.json
  packages/merge-on-green/package.json
  packages/publish/package.json
  packages/release-please/package.json
  packages/sync-repo-settings/package.json
  packages/trusted-contribution/package.json
Labels: cla: yes

#445 fix(Build Cop): check for undefined suites and clean up logging
  packages/buildcop/src/buildcop.ts
  packages/buildcop/test/buildcop.ts
  packages/buildcop/test/fixtures/testdata/empty_results.xml
Labels: cla: yes

#449 fix: do not install chromium in bots
  scripts/serverless-scheduler-proxy-deploy.sh
Labels: cla: yes

#450 Revert "fix(merge-on-green): address bugs related to status check name detection"
  packages/merge-on-green/src/merge-logic.ts
  packages/merge-on-green/src/merge-on-green.ts
  packages/merge-on-green/test/merge-on-green.ts
Labels: cla: yes

#452 chore(Build Cop): refactor tests to reduce duplication
  packages/buildcop/test/buildcop.ts
  packages/buildcop/test/fixtures/testdata/no_tests.xml
Labels: cla: yes

#454 feat(Build Cop): don't mark locked and old issues as flaky
  packages/buildcop/README.md
  packages/buildcop/__snapshots__/buildcop.js
  packages/buildcop/src/buildcop.ts
  packages/buildcop/test/buildcop.ts
Labels: cla: yes

#442 feat(gcf-utils): add Cloud Tasks retry logic
  packages/gcf-utils/package.json
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/fixtures/repos.json
  packages/gcf-utils/test/gcf-utils.ts
  packages/publish/package.json
  packages/sync-repo-settings/package.json
  scripts/publish-functions.sh
Labels: cla: yes, do not merge

#455 fix: max-dispatches-per-second is 500, no parenthesis needed
  scripts/publish-functions.sh
Labels: cla: yes

#458 fix: closing paren should be after deploy_queue
  scripts/publish-functions.sh
Labels: cla: yes

#459 fix: queue name rules
  packages/gcf-utils/package.json
  packages/gcf-utils/src/gcf-utils.ts
  scripts/publish-functions.sh
Labels: cla: yes

#460 fix: queue naming logic and function naming logic are opposite
  scripts/publish-functions.sh
Labels: cla: yes

#461 fix: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD was set in wrong script
  scripts/publish-functions.sh
  scripts/serverless-scheduler-proxy-deploy.sh
Labels: cla: yes

#467 docs: address README typo
  README.md
Labels: cla: yes

#469 fix: address bugs with tasks logic found after deployment
  packages/gcf-utils/package.json
  packages/gcf-utils/src/gcf-utils.ts
Labels: cla: yes

#462 fix(deps): upgrade to kms v2
  packages/gcf-utils/package.json
  packages/gcf-utils/src/bin/genkey.ts
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/src/index.d.ts
  packages/gcf-utils/test/gcf-utils.ts
  packages/gcf-utils/test/integration/gcf-utils-integration.ts
Labels: automerge, cla: yes

#477 fix: scheduler deploy script was missing quote
  scripts/serverless-scheduler-proxy-deploy.sh
Labels: cla: yes

#476 chore: update lint ignore files
  .eslintignore
  .prettierignore
Labels: automerge, cla: yes

#478 build(tests): update mocha config
  packages/auto-label/.mocharc.js
  packages/auto-label/.mocharc.json
  packages/blunderbuss/.mocharc.js
  packages/blunderbuss/.mocharc.json
  packages/buildcop/.mocharc.js
  packages/buildcop/.mocharc.json
  packages/conventional-commit-lint/.mocharc.js
  packages/conventional-commit-lint/.mocharc.json
  packages/failurechecker/.mocharc.js
  packages/failurechecker/.mocharc.json
  packages/gcf-utils/.mocharc.js
  packages/gcf-utils/.mocharc.json
  packages/gcf-utils/package.json
  packages/generate-bot/.mocharc.js
  packages/generate-bot/.mocharc.json
  packages/header-checker-lint/.mocharc.js
  packages/header-checker-lint/.mocharc.json
  packages/label-sync/.mocharc.js
  packages/label-sync/.mocharc.json
  packages/merge-on-green/.mocharc.js
  packages/merge-on-green/.mocharc.json
  packages/publish/.mocharc.js
  packages/publish/.mocharc.json
  packages/release-please/.mocharc.js
  packages/release-please/.mocharc.json
  packages/sync-repo-settings/.mocharc.js
  packages/sync-repo-settings/.mocharc.json
  packages/trusted-contribution/.mocharc.js
  packages/trusted-contribution/.mocharc.json
Labels: cla: yes

#474 fix(sync-repo-settings): categorize repos correctly in required-checks.json
  packages/sync-repo-settings/src/required-checks.json
  packages/sync-repo-settings/src/sync-repo-settings.ts
  packages/sync-repo-settings/test/fixtures/repos.json
  packages/sync-repo-settings/test/test.ts
Labels: automerge, cla: yes

#481 chore(scripts): add CI for scripts and fix some shellcheck errors
  .github/workflows/ci.yaml
  scripts/publish-functions.sh
Labels: cla: yes

#475 fix(merge-on-green): bug that comments on PR multiple times
  packages/merge-on-green/src/merge-on-green.ts
  packages/merge-on-green/test/merge-on-green.ts
Labels: cla: yes

#490 feat(publish): label-based pre-release support
  packages/publish/__snapshots__/publish.js
  packages/publish/src/publish.ts
  packages/publish/test/fixtures/events/pull_request_labeled.json
  packages/publish/test/fixtures/tiny-tarball-packument-1.json
  packages/publish/test/fixtures/tiny-tarball-packument-2.json
  packages/publish/test/publish.ts
Labels: cla: yes

#492 build: update ignore files for synth
  .eslintignore
  .mocharc.js
  .mocharc.json
  .prettierignore
  synth.metadata
  synth.py
Labels: cla: yes

#494 fix(Build Cop): keep existing priority and type labels
  packages/buildcop/__snapshots__/buildcop.js
  packages/buildcop/src/buildcop.ts
  packages/buildcop/test/buildcop.ts
Labels: cla: yes

#486 feat: generate scaffolding for snippet-bot
  .github/workflows/ci.yaml
  packages/snippet-bot/.eslintignore
  packages/snippet-bot/.eslintrc.json
  packages/snippet-bot/.prettierignore
  packages/snippet-bot/.prettierrc.js
  packages/snippet-bot/README.md
  packages/snippet-bot/__snapshots__/.gitkeep
  packages/snippet-bot/package.json
  packages/snippet-bot/src/app.ts
  packages/snippet-bot/src/index.d.ts
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/test/fixtures/config/valid-config.yml
  packages/snippet-bot/test/fixtures/events/issue_opened.json
  packages/snippet-bot/test/fixtures/events/pull_request_opened.json
  packages/snippet-bot/test/snippet-bot.ts
  packages/snippet-bot/tsconfig.json
Labels: cla: yes

#496 fix: switch to new default publish token
  packages/publish/src/publish.ts
Labels: cla: yes

#497 chore: update npm scripts and synth.py
  package.json
  synth.py
Labels: automerge, cla: yes

#480 feat(gcf-utils)!: Use Secret Manager as opposed to KMS + GCS
  cloudbuild.yaml
  packages/gcf-utils/README.md
  packages/gcf-utils/package.json
  packages/gcf-utils/src/bin/README.md
  packages/gcf-utils/src/bin/genkey-util.ts
  packages/gcf-utils/src/bin/genkey.ts
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/gcf-utils.ts
  packages/gcf-utils/test/genkey-util.ts
  scripts/migrate-secrets.sh
  scripts/publish-functions.sh
  scripts/serverless-scheduler-proxy-deploy.sh
  serverless-scheduler-proxy/go.sum
  serverless-scheduler-proxy/main.go
Labels: cla: yes

#502 Revert "feat(gcf-utils)!: Use Secret Manager as opposed to KMS + GCS"
  cloudbuild.yaml
  packages/gcf-utils/README.md
  packages/gcf-utils/package.json
  packages/gcf-utils/src/bin/README.md
  packages/gcf-utils/src/bin/genkey-util.ts
  packages/gcf-utils/src/bin/genkey.ts
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/gcf-utils.ts
  packages/gcf-utils/test/genkey-util.ts
  scripts/migrate-secrets.sh
  scripts/publish-functions.sh
  scripts/serverless-scheduler-proxy-deploy.sh
  serverless-scheduler-proxy/go.sum
  serverless-scheduler-proxy/main.go
Labels: cla: yes

#503 fix: revert scripts and synth.py change
  package.json
  synth.py
Labels: cla: yes

#482 fix(merge-on-green): bug that won't let subtests pass by adding in regex
  packages/merge-on-green/src/merge-logic.ts
  packages/merge-on-green/test/merge-on-green.ts
Labels: automerge, cla: yes

#507 fix: patch to protect against the publish loop bug we saw
  packages/publish/src/publish.ts
Labels: cla: yes

#508 Revert "fix(merge-on-green): bug that won't let subtests pass by adding in regex"
  packages/merge-on-green/src/merge-logic.ts
  packages/merge-on-green/test/merge-on-green.ts
Labels: cla: yes

#510 feat: add matching for subtests
  packages/merge-on-green/src/merge-logic.ts
  packages/merge-on-green/test/merge-on-green.ts
Labels: automerge, cla: yes, kokoro:force-run, kokoro:run

#509 fix: manage google-auth-library-java, google-(api|http|oauth)-java-client settings
  packages/sync-repo-settings/.gitignore
  packages/sync-repo-settings/src/index.d.ts
  packages/sync-repo-settings/src/required-checks.json
  packages/sync-repo-settings/test/fixtures/repos.json
  packages/sync-repo-settings/test/test.ts
Labels: automerge, cla: yes
