Repository googleapis/repo-automation-bots, pull requests merged in 2020-10, with the labels that each got.

#997 fix(logger): allow log methods to be used in isolation
  packages/gcf-utils/src/logging/gcf-logger.ts
  packages/gcf-utils/test/gcf-logger.ts
Labels: cla: yes

#988 fix: upgrade MOG to Probot 10
  packages/merge-on-green/package-lock.json
  packages/merge-on-green/package.json
  packages/merge-on-green/src/merge-logic.ts
  packages/merge-on-green/src/merge-on-green.ts
  packages/merge-on-green/test/merge-on-green.ts
Labels: cla: yes

#1003 fix: upgrade label-sync to probot 10
  packages/label-sync/package-lock.json
  packages/label-sync/package.json
  packages/label-sync/src/label-sync.ts
  packages/label-sync/test/test.ts
Labels: cla: yes

#1002 fix: upgrade failureChecker to Probot 10
  packages/failurechecker/package-lock.json
  packages/failurechecker/package.json
  packages/failurechecker/src/failurechecker.ts
  packages/failurechecker/test/failurechecker.ts
Labels: cla: yes

#1007 build(node_library): migrate to Trampoline V2
  .trampolinerc
  synth.metadata
Labels: cla: yes, context: full

#1012 feat(failure-checker): autorelease: tagged is not considered failure for some languages
  packages/failurechecker/src/failurechecker.ts
  packages/failurechecker/test/failurechecker.ts
Labels: cla: yes

#1018 chore(python): make python-samples-owners writers
  packages/sync-repo-settings/src/required-checks.json
Labels: cla: yes

#1016 fix(failurechecker): use the logger!
  packages/failurechecker/src/failurechecker.ts
Labels: automerge, cla: yes

#999 fix: upgrade blunderbuss to probot 10
  packages/blunderbuss/package-lock.json
  packages/blunderbuss/package.json
  packages/blunderbuss/src/blunderbuss.ts
  packages/blunderbuss/test/blunderbuss.ts
Labels: cla: yes

#1022 Fix: issue 1021 where auto-label bot needs to catch "config not found" on installation
  packages/auto-label/src/auto-label.ts
  packages/auto-label/test/auto-label.ts
Labels: cla: yes

#1023 fix(merge-on-green): implement solution for quota issues
  packages/merge-on-green/src/merge-logic.ts
  packages/merge-on-green/src/merge-on-green.ts
  packages/merge-on-green/test/merge-on-green.ts
Labels: cla: yes

#1024 fix: minor clean ups relating to #1023
  packages/merge-on-green/src/merge-logic.ts
  packages/merge-on-green/src/merge-on-green.ts
Labels: cla: yes

#1006 fix: upgrade header-checker-lint to probot 10
  packages/header-checker-lint/__snapshots__/header-checker-lint.js
  packages/header-checker-lint/package-lock.json
  packages/header-checker-lint/package.json
  packages/header-checker-lint/src/header-checker-lint.ts
  packages/header-checker-lint/test/header-checker-lint.ts
Labels: automerge, cla: yes

#1025 feat: create new octokit instance with installation ID
  packages/merge-on-green/src/merge-on-green.ts
  packages/merge-on-green/test/merge-on-green.ts
Labels: cla: yes

#1000 feat: upgrade buildcop to probot 10
  packages/buildcop/package-lock.json
  packages/buildcop/package.json
  packages/buildcop/src/buildcop.ts
  packages/buildcop/test/buildcop.ts
Labels: cla: yes

#1001 fix: upgrade conventional-commit-lint to probot 10
  packages/conventional-commit-lint/package-lock.json
  packages/conventional-commit-lint/package.json
  packages/conventional-commit-lint/src/conventional-commit-lint.ts
  packages/conventional-commit-lint/test/conventional-commit-lint.ts
Labels: cla: yes

#1011 fix: upgrade snippet bot to probot 10
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/package.json
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/test/snippet-bot.ts
Labels: cla: yes

#1029 chore(publish): update and prune dependencies
  packages/publish/.c8rc.json
  packages/publish/.gitignore
  packages/publish/package-lock.json
  packages/publish/package.json
  packages/publish/test/publish.ts
Labels: cla: yes

#1013 fix(deps): upgrade SRS to probot 10
  packages/sync-repo-settings/package-lock.json
  packages/sync-repo-settings/package.json
  packages/sync-repo-settings/src/sync-repo-settings.ts
  packages/sync-repo-settings/test/test.ts
Labels: cla: yes

#1010 fix: upgrade slo stat bot
  packages/slo-stat-bot/package-lock.json
  packages/slo-stat-bot/package.json
  packages/slo-stat-bot/src/slo-bot.ts
  packages/slo-stat-bot/src/slo-compliant.ts
  packages/slo-stat-bot/src/slo-label.ts
  packages/slo-stat-bot/src/slo-lint.ts
  packages/slo-stat-bot/test/slo-bot.ts
  packages/slo-stat-bot/test/slo-compliant.ts
  packages/slo-stat-bot/test/slo-label.ts
  packages/slo-stat-bot/test/slo-lint.ts
Labels: cla: yes

#1014 fix: upgrade trusted-contribution to probot 10
  packages/trusted-contribution/package-lock.json
  packages/trusted-contribution/package.json
  packages/trusted-contribution/test/trusted-contribution.ts
Labels: cla: yes

#1043 feat(blunderbuss): support assign_prs_by config
  packages/blunderbuss/.eslintignore
  packages/blunderbuss/__snapshots__/blunderbuss.js
  packages/blunderbuss/src/blunderbuss.ts
  packages/blunderbuss/test/blunderbuss.ts
  packages/blunderbuss/test/fixtures/config/pr_on_label.yml
Labels: automerge, cla: yes

#1047 fix(generate-bot): correctly name .eslintrc.json file
  packages/generate-bot/templates/.eslintrc.json
Labels: cla: yes

#1039 feat: extended auto-label to accept user configs & label based on file directories
  README.md
  packages/auto-label/README.md
  packages/auto-label/src/auto-label.ts
  packages/auto-label/src/helper.ts
  packages/auto-label/test/fixtures/config/invalid-config.yml
  packages/auto-label/test/fixtures/config/simple-config.yml
  packages/auto-label/test/fixtures/config/valid-config.yml
  packages/auto-label/test/fixtures/events/pr_opened_labeled.json
  packages/auto-label/test/language-path-tests.ts
Labels: automerge, cla: yes

#1051 chore(docs): update code of conduct
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: cla: yes, context: full

#1052 build(sync-repo-settings): update node's required checks
  packages/sync-repo-settings/src/required-checks.json
  packages/sync-repo-settings/test/test.ts
Labels: cla: yes

#1033 feat: add dependabot to DEFAULT_TRUSTED_CONTRIBUTORS
  packages/trusted-contribution/src/trusted-contribution.ts
Labels: automerge, cla: yes

#1048 feat: add generated-files-bot
  .github/workflows/ci.yaml
  packages/generated-files-bot/.eslintignore
  packages/generated-files-bot/.eslintrc.json
  packages/generated-files-bot/.prettierignore
  packages/generated-files-bot/.prettierrc.js
  packages/generated-files-bot/README.md
  packages/generated-files-bot/__snapshots__/.gitkeep
  packages/generated-files-bot/__snapshots__/template-bot.js
  packages/generated-files-bot/cloudbuild.yaml
  packages/generated-files-bot/package-lock.json
  packages/generated-files-bot/package.json
  packages/generated-files-bot/src/app.ts
  packages/generated-files-bot/src/generated-files-bot.ts
  packages/generated-files-bot/src/index.d.ts
  packages/generated-files-bot/test/fixtures/config/valid-config.yml
  packages/generated-files-bot/test/fixtures/events/pull_request_opened.json
  packages/generated-files-bot/test/fixtures/manifests/simple.json
  packages/generated-files-bot/test/fixtures/manifests/simple.yaml
  packages/generated-files-bot/test/template-bot.ts
  packages/generated-files-bot/tsconfig.json
Labels: cla: yes

#1058 fix(generated-files-bot): fix app.ts export name
  packages/generated-files-bot/src/app.ts
Labels: automerge, cla: yes

#1063 fix(probot): latest release of probot breaks auth
  packages/gcf-utils/package-lock.json
  packages/gcf-utils/package.json
  packages/gcf-utils/src/gcf-utils.ts
Labels: cla: yes

#1065 build: also copy the package-lock.json during deployment
  scripts/build-function.sh
Labels: cla: yes

#1062 feat(auto-label): never label with api: docs or api: build
  packages/auto-label/src/auto-label.ts
  packages/auto-label/test/auto-label.ts
  packages/auto-label/test/fixtures/events/downloadedfile.json
Labels: automerge, cla: yes
