Repository googleapis/repo-automation-bots, pull requests merged in 2020-06, with the labels that each got.

#571 feat(README): add architecture diagram
  README.md
  architecture.png
Labels: cla: yes

#572 fix(Blunderbuss): make assign_issues_by work without assign_issues
  packages/blunderbuss/src/blunderbuss.ts
  packages/blunderbuss/test/fixtures/config/on_label.yml
Labels: cla: yes

#573 docs(Blunderbuss): update README config location
  packages/blunderbuss/README.md
Labels: cla: yes

#574 feat(auto-label): support more APIs and issue titles
  packages/auto-label/src/auto-label.ts
  packages/auto-label/test/auto-label.ts
Labels: cla: yes

#583 chore(sync-repo-settings): Add lint check for j-d-s
  packages/sync-repo-settings/src/required-checks.json
Labels: cla: yes

#587 chore(sync-repo-settings): Make Java 11 optional for g-s-j
  packages/sync-repo-settings/src/required-checks.json
Labels: automerge, cla: yes

#593 feat(Build Cop): grab the right package for Node.js tests
  packages/buildcop/__snapshots__/buildcop.js
  packages/buildcop/src/buildcop.ts
  packages/buildcop/test/buildcop.ts
  packages/buildcop/test/fixtures/testdata/node_one_failed.xml
Labels: cla: yes

#595 feat(Build Cop): group tests into a single issue when 10+ fail
  packages/buildcop/README.md
  packages/buildcop/__snapshots__/buildcop.js
  packages/buildcop/src/buildcop.ts
  packages/buildcop/test/buildcop.ts
  packages/buildcop/test/fixtures/testdata/node_group.xml
  packages/buildcop/test/fixtures/testdata/node_group_pass.xml
Labels: cla: yes, do not merge

#597 fix(deps): release-please expects 18.x.x of octokit
  packages/release-please/package.json
Labels: cla: yes

#607 fix: remove label from PR if automerge fails
  packages/merge-on-green/src/merge-logic.ts
  packages/merge-on-green/test/merge-on-green.ts
Labels: automerge, cla: yes

#610 fix: update node issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#616 build(java): update required status checks for dependencies
  packages/sync-repo-settings/src/required-checks.json
Labels: cla: yes

#605 fix: ensure that function does not depend on errors to execute correctly
  packages/merge-on-green/src/merge-logic.ts
  packages/merge-on-green/test/merge-on-green.ts
Labels: cla: yes

#618 revert: "build(java): update required status checks for dependencies"
  packages/sync-repo-settings/src/required-checks.json
Labels: automerge, cla: yes

#606 fix: add error logging when user is not authorized to push to a branch
  packages/merge-on-green/src/merge-logic.ts
  packages/merge-on-green/test/merge-on-green.ts
Labels: cla: yes

#619 feat(buildcop): try using default credentials
  packages/buildcop/buildcop.go
  packages/buildcop/go.sum
Labels: cla: yes

#620 fix(merge-on-green): condition for error message
  packages/merge-on-green/src/merge-logic.ts
Labels: cla: yes

#627 build: add config .gitattributes
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full
