Repository googleapis/repo-automation-bots, pull requests merged in 2020-08, with the labels that each got.

#793 build(release-please): remove caret from webhooks import
  packages/release-please/package.json
Labels: cla: yes

#788 feat(gcf-utils): log more trigger information
  packages/gcf-utils/src/logging/trigger-info-builder.ts
  packages/gcf-utils/test/trigger-info-builder.ts
Labels: cla: yes

#790 fix(sync-repo-settings): error handling for file read
  packages/sync-repo-settings/src/sync-repo-settings.ts
Labels: cla: yes

#766 feat(monitoring-system): add a data processor for GitHub events data
  packages/monitoring-system/data-processor/README.md
  packages/monitoring-system/data-processor/package.json
  packages/monitoring-system/data-processor/src/data-processor-factory.ts
  packages/monitoring-system/data-processor/src/data-processors/cloud-tasks-data-processor.ts
  packages/monitoring-system/data-processor/src/data-processors/github-data-processor.ts
  packages/monitoring-system/data-processor/src/firestore-schema.ts
  packages/monitoring-system/data-processor/test/unit/data-processors/cloud-tasks-data-processor.spec.ts
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/github-processor-fixture-1.json
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/github-processor-fixture-2.json
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/mock-firestore-data-1.json
  packages/monitoring-system/data-processor/test/unit/data-processors/github-data-processor.spec.ts
  packages/monitoring-system/data-processor/test/unit/data-processors/mocks/mock-firestore.ts
  packages/monitoring-system/data-processor/test/unit/data-processors/mocks/octokit-middleware.ts
  packages/monitoring-system/data-processor/test/unit/data-processors/util/test-util.ts
Labels: automerge, cla: yes

#798 fix(slo-stat-bot): Added slo-bot to deploy
  scripts/publish-functions.sh
Labels: cla: yes

#799 chore(sync-repo-settings): add debug for required status checks
  packages/sync-repo-settings/src/sync-repo-settings.ts
Labels: cla: yes

#800 fix(sync-repo-settings): attempt freezes to avoid mutating global state
  packages/sync-repo-settings/package.json
  packages/sync-repo-settings/src/sync-repo-settings.ts
Labels: cla: yes

#796 feat(gcf-utils): add trigger info as bindings to all log statements
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/src/logging/gcf-logger.ts
  packages/gcf-utils/src/logging/trigger-info-builder.ts
  packages/gcf-utils/test/gcf-bootstrapper.ts
  packages/gcf-utils/test/gcf-logger.ts
  packages/gcf-utils/test/integration/gcf-logger-integration.ts
  packages/gcf-utils/test/trigger-info-builder.ts
Labels: automerge, cla: yes

#803 fix(sync-repo-settings): add google-cloudevents-nodejs to exclude rules
  packages/sync-repo-settings/src/required-checks.json
Labels: cla: yes

#801 chore(infra): enable slo-stat-bot to be built
  .github/workflows/ci.yaml
  scripts/build-functions.sh
Labels: cla: yes

#795 fix(slo-stat-bot): Added issue types for readability
  packages/slo-stat-bot/__snapshots__/slo-label.js
  packages/slo-stat-bot/__snapshots__/slo-lint.js
  packages/slo-stat-bot/cron
  packages/slo-stat-bot/src/slo-bot.ts
  packages/slo-stat-bot/src/slo-compliant.ts
  packages/slo-stat-bot/src/slo-label.ts
  packages/slo-stat-bot/src/types.ts
  packages/slo-stat-bot/test/slo-bot.ts
  packages/slo-stat-bot/test/slo-compliant.ts
  packages/slo-stat-bot/test/slo-label.ts
  packages/slo-stat-bot/test/slo-lint.ts
Labels: cla: yes

#787 test(data-processor): add tests for cloud logs data processor
  packages/monitoring-system/data-processor/package.json
  packages/monitoring-system/data-processor/src/data-processor-factory.ts
  packages/monitoring-system/data-processor/src/data-processors/cloud-logs-data-processor.ts
  packages/monitoring-system/data-processor/src/data-processors/data-processor-abstract.ts
  packages/monitoring-system/data-processor/src/data-processors/github-data-processor.ts
  packages/monitoring-system/data-processor/test/unit/data-processors/cloud-logs-data-processor.spec.ts
  packages/monitoring-system/data-processor/test/unit/data-processors/cloud-tasks-data-processor.spec.ts
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/cloud-logs/error-missing-id.json
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/cloud-logs/error.json
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/cloud-logs/execution-end-missing-timestamp.json
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/cloud-logs/execution-end.json
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/cloud-logs/execution-start-missing-id.json
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/cloud-logs/execution-start.json
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/cloud-logs/github-action-missing-type.json
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/cloud-logs/github-action.json
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/cloud-logs/non-metric.json
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/cloud-logs/trigger-information-missing-repo.json
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/cloud-logs/trigger-information-missing-type.json
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/cloud-logs/trigger-information.json
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/firestore/mock-firestore-data-1.json
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/firestore/mock-firestore-data-2.json
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/firestore/mock-firestore-data-3.json
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/github-processor/github-processor-fixture-1.json
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/github-processor/github-processor-fixture-2.json
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/task-queue/mock-task-queue-data-1.json
  packages/monitoring-system/data-processor/test/unit/data-processors/github-data-processor.spec.ts
  packages/monitoring-system/data-processor/test/unit/data-processors/mocks/mock-firestore.ts
  packages/monitoring-system/data-processor/test/unit/data-processors/mocks/mock-pubsub-subscription.ts
  packages/monitoring-system/data-processor/test/unit/data-processors/util/test-util.ts
Labels: automerge, cla: yes

#809 fix(gcf-utils): Revert binding trigger information to logger
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/src/logging/gcf-logger.ts
  packages/gcf-utils/src/logging/trigger-info-builder.ts
  packages/gcf-utils/test/gcf-bootstrapper.ts
  packages/gcf-utils/test/gcf-logger.ts
  packages/gcf-utils/test/integration/gcf-logger-integration.ts
  packages/gcf-utils/test/trigger-info-builder.ts
Labels: cla: yes

#810 chore(infra): add slo bot cron deploy
  scripts/cron-deploy.sh
Labels: cla: yes

#812 build(slo-stat-bot): fix linter issues
  packages/slo-stat-bot/.eslintrc.json
  packages/slo-stat-bot/.gitignore
  packages/slo-stat-bot/package.json
  packages/slo-stat-bot/src/index.d.ts
Labels: cla: yes

#814 fix(trusted-contribution): fail gracefully if config read fails
  packages/trusted-contribution/src/trusted-contribution.ts
Labels: cla: yes

#819 chore: add repo override for python-crc32c
  packages/sync-repo-settings/src/required-checks.json
Labels: cla: yes

#820 chore: disable strict status checks for python-bigtable
  packages/sync-repo-settings/src/required-checks.json
Labels: cla: yes

#817 fix(slo-stat-bot): Does not lowercase label names from scheduled event
  packages/slo-stat-bot/src/slo-bot.ts
Labels: automerge, cla: yes

#827 fix(slo-stat-bot): excluded labels calculation
  packages/slo-stat-bot/src/slo-appliesTo.ts
  packages/slo-stat-bot/test/slo-appliesTo.ts
Labels: cla: yes

#823 test(data-processor): add more test cases for the Cloud Logs data processor
  packages/monitoring-system/data-processor/src/data-processor-factory.ts
  packages/monitoring-system/data-processor/src/data-processors/cloud-logs-data-processor.ts
  packages/monitoring-system/data-processor/test/unit/data-processors/cloud-logs-data-processor.spec.ts
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/cloud-logs/error-jsonPayload.json
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/cloud-logs/error-textPayload.json
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/cloud-logs/no-severity-2.json
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/cloud-logs/no-severity.json
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/cloud-logs/trigger-information-github.json
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/cloud-logs/trigger-information-missing-repo.json
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/cloud-logs/trigger-information-missing-type.json
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/cloud-logs/trigger-information-pubsub.json
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/cloud-logs/trigger-information-scheduler.json
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/cloud-logs/trigger-information-task.json
Labels: automerge, cla: yes

#824 feat(data-processor): add better type checking, include updates from gcf-utils, and reduce duplicated code
  packages/monitoring-system/data-processor/src/data-processors/data-processor-abstract.ts
  packages/monitoring-system/data-processor/src/data-processors/github-data-processor.ts
  packages/monitoring-system/data-processor/src/firestore-schema.ts
  packages/monitoring-system/data-processor/src/type-check-util.ts
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/github-processor/github-processor-fixture-1.json
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/github-processor/github-processor-fixture-2.json
  packages/monitoring-system/data-processor/test/unit/data-processors/github-data-processor.spec.ts
  packages/monitoring-system/data-processor/test/unit/data-processors/mocks/mock-firestore.ts
Labels: automerge, cla: yes

#828 feat(blunderbuss): ignore draft PRs
  packages/blunderbuss/README.md
  packages/blunderbuss/src/blunderbuss.ts
  packages/blunderbuss/test/blunderbuss.ts
  packages/blunderbuss/test/fixtures/events/pull_request_draft.json
Labels: cla: yes

#826 test(data-processor): add tests for type-check-util and firestore-schema
  packages/monitoring-system/data-processor/test/unit/firestore-schema.spec.ts
  packages/monitoring-system/data-processor/test/unit/type-check-util.spec.ts
Labels: cla: yes

#825 feat(data-processor): add a centralized logger
  packages/monitoring-system/data-processor/src/data-processor-factory.ts
  packages/monitoring-system/data-processor/src/data-processors/cloud-tasks-data-processor.ts
  packages/monitoring-system/data-processor/src/data-processors/github-data-processor.ts
  packages/monitoring-system/data-processor/src/task-service.ts
  packages/monitoring-system/data-processor/src/util/logger.ts
Labels: automerge, cla: yes

#833 chore(failurechecker): turn off failure checker, while debugging un-label issues
  packages/failurechecker/src/failurechecker.ts
  packages/failurechecker/test/failurechecker.ts
Labels: cla: yes

#830 docs(label-sync): add a README!
  packages/label-sync/README.md
Labels: cla: yes

#835 feat(data-processor): add a Cloud Functions data processor
  packages/monitoring-system/data-processor/config/config.yml
  packages/monitoring-system/data-processor/package.json
  packages/monitoring-system/data-processor/src/config-util.ts
  packages/monitoring-system/data-processor/src/data-processor-factory.ts
  packages/monitoring-system/data-processor/src/data-processors/cloud-functions-data-processor.ts
  packages/monitoring-system/data-processor/src/task-service.ts
  packages/monitoring-system/data-processor/test/unit/data-processor-factory.spec.ts
  packages/monitoring-system/data-processor/test/unit/data-processors/cloud-functions-data-processor.spec.ts
  packages/monitoring-system/data-processor/test/unit/data-processors/mocks/mock-cloud-functions-client.ts
Labels: automerge, cla: yes

#831 feat(release-please): support Go
  packages/release-please/package.json
  packages/release-please/src/release-please.ts
Labels: cla: yes

#838 fix(buildcop): treat errors as a failure as well
  packages/buildcop/__snapshots__/buildcop.js
  packages/buildcop/src/buildcop.ts
  packages/buildcop/test/buildcop.ts
  packages/buildcop/test/fixtures/testdata/python_one_error.xml
Labels: cla: yes

#840 docs: update schema of slo rules
  packages/slo-stat-bot/data/schema.json
Labels: cla: yes

#806 feat(data-processor): implement Cloud Logs data processor, add more type checking, move constants to config
  packages/monitoring-system/data-processor/config/config.yml
  packages/monitoring-system/data-processor/src/data-processor-factory.ts
  packages/monitoring-system/data-processor/src/data-processors/cloud-functions-data-processor.ts
  packages/monitoring-system/data-processor/src/data-processors/cloud-logs-data-processor.ts
  packages/monitoring-system/data-processor/src/data-processors/cloud-tasks-data-processor.ts
  packages/monitoring-system/data-processor/src/data-processors/data-processor-abstract.ts
  packages/monitoring-system/data-processor/src/data-processors/github-data-processor.ts
  packages/monitoring-system/data-processor/src/types/cloud-logs.ts
  packages/monitoring-system/data-processor/src/types/firestore-schema.ts
  packages/monitoring-system/data-processor/src/types/type-check-util.ts
  packages/monitoring-system/data-processor/src/util/config-util.ts
  packages/monitoring-system/data-processor/test/unit/data-processor-factory.spec.ts
  packages/monitoring-system/data-processor/test/unit/data-processors/github-data-processor.spec.ts
  packages/monitoring-system/data-processor/test/unit/data-processors/mocks/mock-pubsub-subscription.ts
  packages/monitoring-system/data-processor/test/unit/types/firestore-schema.spec.ts
  packages/monitoring-system/data-processor/test/unit/types/type-check-util.spec.ts
  packages/monitoring-system/data-processor/test/unit/util/config-util.spec.ts
Labels: automerge, cla: yes

#846 chore(header-checker-lint): ignore snapshot files
  .github/header-checker-lint.yml
Labels: cla: yes

#844 feat(snippet-bot): check matching region tags
  .github/snippet-bot.yml
  packages/snippet-bot/README.md
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/package.json
  packages/snippet-bot/src/region-tag-parser.ts
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/test/fixtures/config/ignore-config.yml
  packages/snippet-bot/test/fixtures/config/valid-config.yml
  packages/snippet-bot/test/fixtures/events/issue_opened.json
  packages/snippet-bot/test/fixtures/events/pull_request_opened.json
  packages/snippet-bot/test/fixtures/failure_blob.json
  packages/snippet-bot/test/fixtures/pr_event.json
  packages/snippet-bot/test/fixtures/pr_files_added.json
  packages/snippet-bot/test/fixtures/pr_files_deleted.json
  packages/snippet-bot/test/snippet-bot.ts
Labels: cla: yes

#841 fix(data-processor): remove severity as a required property in type-checking Cloud Log entries
  packages/monitoring-system/data-processor/src/types/cloud-logs.ts
Labels: automerge, cla: yes

#849 chore(snippet-bot): update to the gcf-utils 5.5.1
  packages/snippet-bot/package.json
Labels: cla: yes

#850 chore(snippet-bot): remove problematic deps
  packages/snippet-bot/package.json
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/test/snippet-bot.ts
Labels: cla: yes

#847 build: include package-lock files again
  .gitignore
  packages/auto-label/.npmrc
  packages/auto-label/package-lock.json
  packages/blunderbuss/.npmrc
  packages/blunderbuss/package-lock.json
  packages/buildcop/.npmrc
  packages/buildcop/package-lock.json
  packages/conventional-commit-lint/.gitignore
  packages/conventional-commit-lint/.npmrc
  packages/conventional-commit-lint/package-lock.json
  packages/failurechecker/.npmrc
  packages/failurechecker/package-lock.json
  packages/gcf-utils/.npmrc
  packages/gcf-utils/package-lock.json
  packages/generate-bot/.npmrc
  packages/generate-bot/package-lock.json
  packages/header-checker-lint/package-lock.json
  packages/label-sync/.npmrc
  packages/label-sync/package-lock.json
  packages/merge-on-green/.npmrc
  packages/merge-on-green/package-lock.json
  packages/publish/.npmrc
  packages/publish/package-lock.json
  packages/release-please/.npmrc
  packages/release-please/package-lock.json
  packages/slo-stat-bot/package-lock.json
  packages/snippet-bot/package-lock.json
  packages/sync-repo-settings/.npmrc
  packages/sync-repo-settings/package-lock.json
  packages/trusted-contribution/.npmrc
  packages/trusted-contribution/package-lock.json
Labels: cla: yes

#855 process(github): add data processor to ci checks
  .github/workflows/ci.yaml
Labels: cla: yes

#853 fix(data-processor): add a `private` field to GitHub repositories to reduce unnecessary API calls
  packages/monitoring-system/data-processor/package-lock.json
  packages/monitoring-system/data-processor/package.json
  packages/monitoring-system/data-processor/src/data-processors/github-data-processor.ts
  packages/monitoring-system/data-processor/src/types/firestore-schema.ts
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/github-processor/github-processor-fixture-1.json
Labels: automerge, cla: yes

#856 feat(snippet-bot): require the config file to enable the bot
  packages/snippet-bot/README.md
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/test/snippet-bot.ts
Labels: cla: yes

#829 docs: readme tweaks
  README.md
Labels: automerge, cla: yes

#813 fix(slo-stat-bot): Does not throw error when org level config is missing but logs an error
  packages/slo-stat-bot/src/slo-bot.ts
  packages/slo-stat-bot/src/slo-label.ts
Labels: automerge, cla: yes

#854 chore(release-please): switch to gcf-utils logger
  packages/release-please/src/release-please.ts
Labels: cla: yes

#860 chore(mog): clean up dependencies
  packages/merge-on-green/.c8rc.json
  packages/merge-on-green/package-lock.json
  packages/merge-on-green/package.json
Labels: cla: yes

#857 test(auto-label): throw on logger errors in tests
  packages/auto-label/src/auto-label.ts
  packages/auto-label/test/auto-label.ts
Labels: cla: yes

#858 fix(release-please): clean up dependencies
  packages/release-please/.c8rc.json
  packages/release-please/.gitignore
  packages/release-please/package-lock.json
  packages/release-please/package.json
  packages/release-please/src/release-please.ts
  packages/release-please/test/release-please.ts
Labels: cla: yes, do not merge

#861 refactor(auto-label): further simplify auto-label
  packages/auto-label/src/auto-label.ts
  packages/auto-label/test/auto-label.ts
  packages/auto-label/test/fixtures/events/emptydownloadedfile.json
Labels: cla: yes

#867 feat(release-please): allow changelog path to be configured
  packages/release-please/package-lock.json
  packages/release-please/package.json
  packages/release-please/src/release-please.ts
Labels: cla: yes

#868 chore(header-checker-lint): fixed the config file
  .github/header-checker-lint.yml
Labels: cla: yes

#866 fix(header-checker-lint): catch configuration parse errors and log
  .bots/header-checker-lint.json
  packages/header-checker-lint/src/header-checker-lint.ts
  packages/header-checker-lint/test/fixtures/invalid_yaml.yml
  packages/header-checker-lint/test/header-checker-lint.ts
Labels: cla: yes

#864 chore(buildcop): clean up dependencies
  packages/buildcop/.c8rc.json
  packages/buildcop/.gitignore
  packages/buildcop/package-lock.json
  packages/buildcop/package.json
  packages/buildcop/src/buildcop.ts
  packages/buildcop/test/buildcop.ts
Labels: cla: yes

#873 fix(buildcop): fix parsing CDATA from Java errors
  packages/buildcop/__snapshots__/buildcop.js
  packages/buildcop/src/buildcop.ts
  packages/buildcop/test/buildcop.ts
  packages/buildcop/test/fixtures/testdata/java_one_error.xml
Labels: cla: yes

#874 chore: start tracking obsolete files
  synth.metadata
Labels: cla: yes, context: full

#881 chore(snippet-bot): only submit the check when region tags are detected
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/src/region-tag-parser.ts
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/test/fixtures/blob_no_region_tags.json
  packages/snippet-bot/test/snippet-bot.ts
Labels: cla: yes

#879 docs: add snippet-bot
  README.md
Labels: automerge, cla: yes

#871 fix(auto-label): add labels to PRs by default
  packages/auto-label/src/auto-label.ts
Labels: cla: yes

#883 feat(auto-label): auto-detect from Conventional Commit scopes
  packages/auto-label/src/auto-label.ts
  packages/auto-label/test/auto-label.ts
Labels: cla: yes

#896 feat(monitoring-system): add authentication to the metrics dashboard
  packages/monitoring-system/metrics-dashboard/firebase.json
  packages/monitoring-system/metrics-dashboard/package-lock.json
  packages/monitoring-system/metrics-dashboard/package.json
  packages/monitoring-system/metrics-dashboard/src/app.html
  packages/monitoring-system/metrics-dashboard/src/css/style.css
  packages/monitoring-system/metrics-dashboard/src/index.html
  packages/monitoring-system/metrics-dashboard/src/ts/auth.ts
  packages/monitoring-system/metrics-dashboard/src/ts/firestore/firestore-client.ts
  packages/monitoring-system/metrics-dashboard/src/ts/firestore/firestore-config.json
  packages/monitoring-system/metrics-dashboard/src/ts/firestore/firestore-listener.ts
  packages/monitoring-system/metrics-dashboard/src/ts/query-data/change-processor.ts
  packages/monitoring-system/metrics-dashboard/src/ts/render/render.ts
  packages/monitoring-system/metrics-dashboard/webpack.config.js
Labels: automerge, cla: yes

#901 build: parameterize functionRuntime
  packages/release-please/cloudbuild.yaml
  packages/release-please/package.json
  packages/snippet-bot/cloudbuild.yaml
  packages/snippet-bot/package.json
  scripts/publish-function.sh
Labels: cla: yes

#902 fix(snippet-bot): fix deployment for nodejs12 runtime
  packages/snippet-bot/package.json
Labels: cla: yes

#889 feat(snippet-bot): add full scan feature
  packages/snippet-bot/README.md
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/package.json
  packages/snippet-bot/src/region-tag-parser.ts
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/test/fixtures/issue_event.json
  packages/snippet-bot/test/fixtures/issue_event_no_scan.json
  packages/snippet-bot/test/fixtures/tmatsuo-python-docs-samples-abcde.tar.gz
  packages/snippet-bot/test/snippet-bot.ts
Labels: cla: yes

#904 chore(snippet-bot): listen to pullrequest.synchronized
  packages/snippet-bot/README.md
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/src/snippet-bot.ts
Labels: cla: yes

#908 chore: opt in 4 bots to use nodejs12 runtime
  packages/auto-label/cloudbuild.yaml
  packages/auto-label/package.json
  packages/blunderbuss/cloudbuild.yaml
  packages/blunderbuss/package.json
  packages/buildcop/cloudbuild.yaml
  packages/buildcop/package.json
  packages/conventional-commit-lint/cloudbuild.yaml
  packages/conventional-commit-lint/package.json
Labels: cla: yes

#907 fix(trusted-contribution): stop responding to pull_request.edited, use kokoro:force-run
  packages/trusted-contribution/.c8rc.json
  packages/trusted-contribution/src/trusted-contribution.ts
Labels: cla: yes

#909 chore: update generate-bot template
  packages/generate-bot/templates/package.json
Labels: cla: yes

#900 docs(monitoring-system, gcf-utils): add documentation to READMEs for monitoring system components
  packages/gcf-utils/README.md
  packages/monitoring-system/README.md
  packages/monitoring-system/data-processor/README.md
  packages/monitoring-system/data-processor/docs/assets/class-diagram.png
  packages/monitoring-system/data-processor/docs/assets/sequence-diagram.png
  packages/monitoring-system/docs/assets/architecture-overview.png
  packages/monitoring-system/metrics-dashboard/README.md
Labels: cla: yes

#913 chore(snippet-bot): fix cosmetic issue for full scan
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/src/snippet-bot.ts
Labels: cla: yes

#916 feat(auto-label): support common Java issue titles
  packages/auto-label/README.md
  packages/auto-label/src/auto-label.ts
  packages/auto-label/test/auto-label.ts
  packages/auto-label/test/fixtures/events/downloadedfile.json
Labels: cla: yes

#911 chore: opt in 4 bots to use nodejs12 runtime
  packages/failurechecker/cloudbuild.yaml
  packages/failurechecker/package.json
  packages/header-checker-lint/cloudbuild.yaml
  packages/header-checker-lint/package.json
  packages/label-sync/cloudbuild.yaml
  packages/label-sync/package.json
  packages/merge-on-green/cloudbuild.yaml
  packages/merge-on-green/package.json
Labels: cla: yes

#919 chore: opt in remaining bots to nodejs12
  packages/slo-stat-bot/cloudbuild.yaml
  packages/slo-stat-bot/package.json
  packages/sync-repo-settings/cloudbuild.yaml
  packages/sync-repo-settings/package.json
  packages/trusted-contribution/cloudbuild.yaml
  packages/trusted-contribution/package.json
Labels: cla: yes

#915 docs: remove internal links from docs
  packages/gcf-utils/README.md
  packages/monitoring-system/README.md
  packages/monitoring-system/data-processor/README.md
Labels: automerge, cla: yes

#877 fix(mog): rate limit issues
  packages/merge-on-green/package-lock.json
  packages/merge-on-green/src/merge-logic.ts
  packages/merge-on-green/src/merge-on-green.ts
  packages/merge-on-green/test/Fixtures/events/pull_request_labeled.json
  packages/merge-on-green/test/Fixtures/events/pull_request_opened.json
  packages/merge-on-green/test/merge-on-green.ts
Labels: cla: yes, kokoro:force-run

#922 testing: introduce `node` matrix
  .github/workflows/ci.yaml
Labels: cla: yes

#925 fix(trusted-contribution): don't use Cloud Tasks
  packages/trusted-contribution/src/app.ts
Labels: cla: yes

#923 chore: add label-sync cron job, clean up some readme's
  packages/auto-label/README.md
  packages/label-sync/README.md
  packages/label-sync/src/label-sync.ts
  packages/label-sync/test/test.ts
Labels: cla: yes

#921 feat(gcf-utils): log event type with trigger information
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/src/logging/trigger-info-builder.ts
  packages/gcf-utils/test/fixtures/github-webhook-payload-all-info.json
  packages/gcf-utils/test/fixtures/github-webhook-payload-missing-info.json
  packages/gcf-utils/test/fixtures/github-webhook-payloads/issue-labeled.json
  packages/gcf-utils/test/fixtures/github-webhook-payloads/issue-opened-missing-info.json
  packages/gcf-utils/test/fixtures/github-webhook-payloads/issue-opened.json
  packages/gcf-utils/test/fixtures/github-webhook-payloads/label-deleted.json
  packages/gcf-utils/test/fixtures/github-webhook-payloads/pull-request-labeled.json
  packages/gcf-utils/test/fixtures/github-webhook-payloads/pull-request-opened.json
  packages/gcf-utils/test/fixtures/github-webhook-payloads/pull-request-sync.json
  packages/gcf-utils/test/fixtures/github-webhook-payloads/release-released.json
  packages/gcf-utils/test/trigger-info-builder.ts
Labels: automerge, cla: yes

#928 feat(metrics): add context aware commits to dashboard
  metrics/dashboards.sql
Labels: automerge, cla: yes

#932 feat(auto-label): auto-detect before underscores
  packages/auto-label/README.md
  packages/auto-label/src/auto-label.ts
  packages/auto-label/test/auto-label.ts
Labels: cla: yes

#878 test(mog): throw when errors are written in tests
  packages/merge-on-green/package.json
  packages/merge-on-green/src/merge-on-green.ts
  packages/merge-on-green/test/merge-on-green.ts
Labels: cla: yes
