Repository googleapis/repo-automation-bots, pull requests merged in 2020-11, with the labels that each got.

#1071 feat(snippet-bot): add a summary of the region tag changes on PRs
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/package.json
  packages/snippet-bot/src/region-tag-parser.ts
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/test/fixtures/diff.txt
  packages/snippet-bot/test/region-tag-parser.ts
  packages/snippet-bot/test/snippet-bot.ts
Labels: cla: yes

#1076 fix(generated-files-bot): handle missing external manifest files
  packages/generated-files-bot/__snapshots__/template-bot.js
  packages/generated-files-bot/package.json
  packages/generated-files-bot/src/generated-files-bot.ts
  packages/generated-files-bot/test/template-bot.ts
Labels: cla: yes

#1075 chore(deps): update gts to 3.0.0
  packages/auto-label/package-lock.json
  packages/auto-label/package.json
  packages/blunderbuss/package-lock.json
  packages/blunderbuss/package.json
  packages/buildcop/package-lock.json
  packages/buildcop/package.json
  packages/buildcop/src/buildcop.ts
  packages/conventional-commit-lint/package-lock.json
  packages/conventional-commit-lint/package.json
  packages/conventional-commit-lint/src/index.d.ts
  packages/failurechecker/package-lock.json
  packages/failurechecker/package.json
  packages/gcf-utils/package-lock.json
  packages/gcf-utils/package.json
  packages/generate-bot/package-lock.json
  packages/generate-bot/package.json
  packages/generate-bot/templates/package.json
  packages/header-checker-lint/package-lock.json
  packages/header-checker-lint/package.json
  packages/label-sync/package-lock.json
  packages/label-sync/package.json
  packages/label-sync/src/app.ts
  packages/merge-on-green/package-lock.json
  packages/merge-on-green/package.json
  packages/release-please/package-lock.json
  packages/release-please/package.json
  packages/slo-stat-bot/package-lock.json
  packages/slo-stat-bot/package.json
  packages/slo-stat-bot/src/slo-compliant.ts
  packages/slo-stat-bot/test/slo-bot.ts
  packages/slo-stat-bot/test/slo-compliant.ts
  packages/slo-stat-bot/test/slo-label.ts
  packages/slo-stat-bot/test/slo-lint.ts
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/package.json
  packages/sync-repo-settings/package-lock.json
  packages/sync-repo-settings/package.json
  packages/trusted-contribution/package-lock.json
  packages/trusted-contribution/package.json
Labels: cla: yes

#1080 feat(snippet-bot): add `snippet-bot:force-run` label for refreshing the result
  packages/snippet-bot/README.md
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/test/fixtures/pr_event_label_added.json
  packages/snippet-bot/test/fixtures/pr_event_label_ignored.json
  packages/snippet-bot/test/snippet-bot.ts
Labels: cla: yes

#1083 feat(release-please): latest and greatest dep
  packages/release-please/package-lock.json
  packages/release-please/package.json
  packages/release-please/src/release-please.ts
Labels: cla: yes

#1085 fix(snippet-bot): ignore 404 errors upon label deletion
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/test/snippet-bot.ts
Labels: cla: yes

#1087 feat(snippet-bot): track start tags in the files
  packages/snippet-bot/src/region-tag-parser.ts
  packages/snippet-bot/src/snippet-bot.ts
Labels: cla: yes

#1090 refactor(snippet-bot): use diff to get the list of files
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/src/region-tag-parser.ts
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/test/fixtures/diff.txt
  packages/snippet-bot/test/snippet-bot.ts
Labels: automerge, cla: yes

#1091 fix: remove commenting functionality
  packages/merge-on-green/src/merge-logic.ts
  packages/merge-on-green/src/merge-on-green.ts
  packages/merge-on-green/test/merge-on-green.ts
Labels: cla: yes

#1095 feat(release-please): support go monorepo release process
  packages/release-please/package-lock.json
  packages/release-please/package.json
  packages/release-please/src/release-please.ts
Labels: cla: yes

#1099 feat(snippet-bot): check if region tags have product prefix
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/package.json
  packages/snippet-bot/src/api-labels.ts
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/src/violations.ts
  packages/snippet-bot/test/fixtures/diff.txt
  packages/snippet-bot/test/snippet-bot.ts
Labels: cla: yes

#1102 fix(release-please): pass relaseType config
  packages/release-please/package-lock.json
  packages/release-please/package.json
  packages/release-please/src/release-please.ts
Labels: cla: yes

#1105 fix(snippet-bot): use products.json for region_tag_prefix
  packages/snippet-bot/README.md
  packages/snippet-bot/src/api-labels.ts
  packages/snippet-bot/src/violations.ts
  packages/snippet-bot/test/snippet-bot.ts
Labels: cla: yes

#1107 fix(snippet-bot): apply ignoreFiles to violation checks
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/src/configuration.ts
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/src/violations.ts
Labels: cla: yes

#1109 fix(snippet-bot): avoid 404 errors
  packages/snippet-bot/src/region-tag-parser.ts
  packages/snippet-bot/src/snippet-bot.ts
Labels: cla: yes

#1100 feat: give all DPEs write all the time
  packages/sync-repo-settings/src/sync-repo-settings.ts
Labels: cla: yes

#1111 fix(snippet-bot): ignore 403 error as well
  packages/snippet-bot/src/snippet-bot.ts
Labels: cla: yes

#1112 fix(merge-on-green): add cleanup cron job, fix blocking issue for removing
  packages/merge-on-green/src/merge-on-green.ts
  packages/merge-on-green/test/merge-on-green.ts
Labels: cla: yes

#1118 feat(gcf-utils): add addOrUpdateIssueComment
  packages/gcf-utils/__snapshots__/gcf-utils.js
  packages/gcf-utils/package.json
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/fixtures/issue_event.json
  packages/gcf-utils/test/fixtures/list_issue_comments.json
  packages/gcf-utils/test/gcf-utils.ts
Labels: cla: yes

#1129 chore: update Go genproto later in day on Monday
  renovate.json
Labels: cla: yes

#1124 fix(blunderbuss): handle assign_issues_by only config
  packages/blunderbuss/src/blunderbuss.ts
  packages/blunderbuss/test/blunderbuss.ts
  packages/blunderbuss/test/fixtures/config/assign_by.yml
Labels: cla: yes

#1120 chore(auto-label): clean up types
  packages/auto-label/package.json
  packages/auto-label/src/auto-label.ts
  packages/auto-label/src/helper.ts
  packages/auto-label/tsconfig.json
Labels: cla: yes

#1133 testing(go tests): use actions/setup-go@v2
  .github/workflows/ci.yaml
Labels: cla: yes

#1116 feat(snippet-bot): give warnings for removing region tags in use
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/src/snippets.ts
  packages/snippet-bot/src/violations.ts
  packages/snippet-bot/test/fixtures/products.json
  packages/snippet-bot/test/fixtures/snippets.json
  packages/snippet-bot/test/snippet-bot.ts
Labels: cla: yes

#1125 fix(data-processor): add logging for errors
  packages/monitoring-system/data-processor/package-lock.json
  packages/monitoring-system/data-processor/package.json
  packages/monitoring-system/data-processor/src/task-service.ts
Labels: cla: yes

#1122 fix: set max duration for task queue
  scripts/publish-function.sh
Labels: cla: yes

#1138 chore: enable lock file maintenance
  renovate.json
Labels: cla: yes

#1137 fix(auto-label): bump min required dependencies
  packages/auto-label/package-lock.json
  packages/auto-label/package.json
  packages/auto-label/src/auto-label.ts
Labels: cla: yes

#1131 feat(gcf-utils): change the method signature of addOrUpdateIssueComment
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/gcf-utils.ts
Labels: automerge, cla: yes

#626 build: experiment with optional CI jobs
  .github/sync-repo-settings.yaml
  .github/workflows/ci.yaml
  .github/workflows/finale.js
  .github/workflows/interrogate.js
  package.json
Labels: cla: yes

#1144 cleanup(snippet-bot): reduce memory footprint for large diffs
  packages/snippet-bot/src/region-tag-parser.ts
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/test/region-tag-parser.ts
Labels: cla: yes

#1141 feat(snippet-bot): cache Snippets data
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/package.json
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/src/snippets.ts
  packages/snippet-bot/test/snippet-bot.ts
Labels: cla: yes

#1146 fix(snippet-bot): disable warning for removal of region tags in use
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/src/snippet-bot.ts
Labels: cla: yes

#1150 chore(data-processor): use @google-cloud/functions
  .github/workflows/interrogate.js
  packages/monitoring-system/data-processor/.gitignore
  packages/monitoring-system/data-processor/package-lock.json
  packages/monitoring-system/data-processor/package.json
  packages/monitoring-system/data-processor/src/data-processors/cloud-functions-data-processor.ts
  packages/monitoring-system/data-processor/test/unit/data-processors/cloud-functions-data-processor.spec.ts
  packages/monitoring-system/data-processor/test/unit/data-processors/mocks/mock-cloud-functions-client.ts
Labels: cla: yes

#1155 feat(snippet-bot): only link the filename part
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/src/snippet-bot.ts
Labels: cla: yes

#1152 cleanup(snippet-bot): factor out the core logic
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/package.json
  packages/snippet-bot/src/snippet-bot.ts
Labels: cla: yes

#1163 fix(release-please): pass credentials to go submodules
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: cla: yes

#1161 feat(snippet-bot): provide a checkbox for refreshing
  packages/snippet-bot/README.md
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/test/fixtures/pr_event_comment_edited.json
  packages/snippet-bot/test/fixtures/pr_event_comment_edited_irelevant.json
  packages/snippet-bot/test/fixtures/pr_response.json
  packages/snippet-bot/test/snippet-bot.ts
Labels: cla: yes, do not merge

#1166 fix: improve the generate bot
  packages/generate-bot/.c8rc.json
  packages/generate-bot/.gitignore
  packages/generate-bot/README.md
  packages/generate-bot/__snapshots__/generate-bot.js
  packages/generate-bot/package-lock.json
  packages/generate-bot/package.json
  packages/generate-bot/src/main.ts
  packages/generate-bot/src/run.ts
  packages/generate-bot/templates/.c8rc.json
  packages/generate-bot/templates/.eslintignore
  packages/generate-bot/templates/.gitignore
  packages/generate-bot/templates/README.md
  packages/generate-bot/templates/__snapshots__/.gitkeep
  packages/generate-bot/templates/package.json
  packages/generate-bot/templates/test/test.ts
  packages/generate-bot/test/test.ts
  packages/generate-bot/tsconfig.json
Labels: cla: yes

#1169 build(blunderbuss): use v1 lock file and update dependencies
  packages/blunderbuss/.c8rc.json
  packages/blunderbuss/package-lock.json
  packages/blunderbuss/package.json
Labels: cla: yes

#1172 build(conventional-commit-lint): use lock file v1
  packages/conventional-commit-lint/.c8rc.json
  packages/conventional-commit-lint/package-lock.json
  packages/conventional-commit-lint/package.json
  packages/conventional-commit-lint/test/conventional-commit-lint.ts
Labels: cla: yes

#1170 build(buildcop): use lockfile v1 and address lint issues
  packages/buildcop/package-lock.json
  packages/buildcop/package.json
  packages/buildcop/src/buildcop.ts
  packages/buildcop/test/buildcop.ts
Labels: cla: yes

#1174 build(header-checker-lint): use lock format v1, update dependencies
  packages/header-checker-lint/.c8rc.json
  packages/header-checker-lint/package-lock.json
  packages/header-checker-lint/package.json
  packages/header-checker-lint/test/header-checker-lint.ts
Labels: cla: yes

#1173 feat(gcf-utils): export a function for the comment mark
  packages/gcf-utils/src/gcf-utils.ts
Labels: cla: yes

#1177 build(merge-on-green): update lock file and deps
  packages/merge-on-green/package-lock.json
  packages/merge-on-green/package.json
  packages/merge-on-green/src/merge-logic.ts
  packages/merge-on-green/src/merge-on-green.ts
  packages/merge-on-green/test/merge-on-green.ts
Labels: cla: yes

#1179 build(release-please): clean up imports and types
  packages/release-please/package-lock.json
  packages/release-please/package.json
  packages/release-please/src/release-please.ts
  packages/release-please/src/runner.ts
  packages/release-please/test/release-please.ts
Labels: cla: yes

#1181 build(snippet-bot): clean up dependencies
  packages/snippet-bot/.gitignore
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/package.json
Labels: cla: yes

#1182 fix(snippet-bot): exits early for PRs with null head
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/test/fixtures/pr_event_null_head.json
  packages/snippet-bot/test/snippet-bot.ts
Labels: cla: yes

#1184 cleanup(snippet-bot): exits early if the PR is closed
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/test/fixtures/pr_event_closed.json
  packages/snippet-bot/test/snippet-bot.ts
Labels: cla: yes

#1188 feat(do-not-merge): create Do Not Merge bot
  README.md
  packages/do-not-merge/.c8rc.json
  packages/do-not-merge/.eslintignore
  packages/do-not-merge/.eslintrc.json
  packages/do-not-merge/.gitignore
  packages/do-not-merge/.prettierignore
  packages/do-not-merge/.prettierrc.js
  packages/do-not-merge/README.md
  packages/do-not-merge/__snapshots__/test.js
  packages/do-not-merge/package-lock.json
  packages/do-not-merge/package.json
  packages/do-not-merge/src/app.ts
  packages/do-not-merge/src/do-not-merge.ts
  packages/do-not-merge/src/index.d.ts
  packages/do-not-merge/test/fixtures/events/pull_request_labeled.json
  packages/do-not-merge/test/fixtures/events/pull_request_labeled_closed.json
  packages/do-not-merge/test/fixtures/events/pull_request_labeled_other.json
  packages/do-not-merge/test/test.ts
  packages/do-not-merge/tsconfig.json
Labels: cla: yes

#1190 chore(generated-files-bot): clean up dependencies
  packages/generated-files-bot/.c8rc.json
  packages/generated-files-bot/package-lock.json
  packages/generated-files-bot/package.json
  packages/generated-files-bot/src/generated-files-bot.ts
  packages/generated-files-bot/test/template-bot.ts
Labels: cla: yes

#1193 chore(failurechecker): update to latest dependencies
  packages/failurechecker/.c8rc.json
  packages/failurechecker/package-lock.json
  packages/failurechecker/package.json
  packages/failurechecker/src/failurechecker.ts
  packages/failurechecker/test/failurechecker.ts
Labels: cla: yes
