Repository googleapis/repo-automation-bots, pull requests merged in 2020-07, with the labels that each got.

#631 chore(deps): upgrade to nock 13
  packages/auto-label/package.json
  packages/auto-label/src/index.d.ts
  packages/blunderbuss/package.json
  packages/blunderbuss/src/index.d.ts
  packages/buildcop/package.json
  packages/buildcop/src/index.d.ts
  packages/conventional-commit-lint/package.json
  packages/conventional-commit-lint/src/index.d.ts
  packages/failurechecker/package.json
  packages/failurechecker/src/index.d.ts
  packages/gcf-utils/package.json
  packages/generate-bot/__snapshots__/generate-bot.js
  packages/generate-bot/templates/package.json
  packages/generate-bot/templates/src/index.d.ts
  packages/header-checker-lint/package.json
  packages/header-checker-lint/src/index.d.ts
  packages/label-sync/package.json
  packages/label-sync/src/index.d.ts
  packages/merge-on-green/package.json
  packages/merge-on-green/src/index.d.ts
  packages/merge-on-green/src/merge-logic.ts
  packages/merge-on-green/test/merge-on-green.ts
  packages/publish/package.json
  packages/publish/src/index.d.ts
  packages/release-please/package.json
  packages/snippet-bot/src/index.d.ts
  packages/sync-repo-settings/package.json
  packages/sync-repo-settings/test/test.ts
  packages/trusted-contribution/package.json
  packages/trusted-contribution/src/index.d.ts
Labels: automerge, cla: yes

#636 docs(release-please): add links to upstream repo, npm package
  packages/release-please/README.md
Labels: automerge, cla: yes

#637 fix(sync-repo-settings): remove invalid checks for google-oauth|api-java-client
  packages/sync-repo-settings/src/required-checks.json
  packages/sync-repo-settings/test/test.ts
Labels: automerge, cla: yes

#640 feat(commit-lint): use title if automerge label
  packages/conventional-commit-lint/__snapshots__/conventional-commit-lint.js
  packages/conventional-commit-lint/src/conventional-commit-lint.ts
  packages/conventional-commit-lint/test/conventional-commit-lint.ts
  packages/conventional-commit-lint/test/fixtures/pull_request_automerge.json
Labels: cla: yes

#639 feat(release-please)!: run nightly around 1 am for snapshots
  packages/release-please/cron
  packages/release-please/package.json
  packages/release-please/src/release-please.ts
  packages/release-please/test/release-please.ts
Labels: automerge, cla: yes

#651 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#647 fix(gcf-utils): prepackage required type modules and interfaces
  packages/gcf-utils/package.json
  packages/gcf-utils/src/promise-events.ts
Labels: cla: yes

#652 revert: "feat(release-please)!: run nightly around 1 am for snapshots"
  packages/release-please/cron
  packages/release-please/package.json
  packages/release-please/src/release-please.ts
  packages/release-please/test/release-please.ts
Labels: automerge, cla: yes

#645 feat(gcf-utils,label-sync)!: use /installation/repositories to get repo list
  packages/gcf-utils/package.json
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/fixtures/installations.json
  packages/gcf-utils/test/gcf-utils.ts
  packages/label-sync/src/label-sync.ts
  packages/label-sync/test/test.ts
Labels: cla: yes

#655 fix(gcf-utils): populate repository.owner
  packages/gcf-utils/src/gcf-utils.ts
Labels: cla: yes

#624 revert: "revert: "build(java): update required status checks for dependencies""
  packages/sync-repo-settings/src/required-checks.json
Labels: automerge, cla: yes

#657 feat(release-please)!: run nightly around 1 am for snapshots
  packages/release-please/cron
  packages/release-please/package.json
  packages/release-please/src/release-please.ts
  packages/release-please/test/release-please.ts
Labels: cla: yes

#644 feat(gcf-utils): export an interface for CronPayload
  packages/gcf-utils/src/gcf-utils.ts
Labels: cla: yes

#601 feat(sync-repo-settings): allow configuring extra team permissions by language
  packages/sync-repo-settings/package.json
  packages/sync-repo-settings/src/sync-repo-settings.ts
  packages/sync-repo-settings/src/teams.json
  packages/sync-repo-settings/test/fixtures/repos.json
  packages/sync-repo-settings/test/test.ts
Labels: automerge, cla: yes

#658 fix: paginate result set when listing installations
  packages/gcf-utils/package.json
  packages/gcf-utils/src/gcf-utils.ts
Labels: cla: yes

#625 feat(merge-on-green): add a second label system that makes automerging more secure
  packages/merge-on-green/src/merge-logic.ts
  packages/merge-on-green/src/merge-on-green.ts
  packages/merge-on-green/test/merge-on-green.ts
Labels: cla: yes

#662 chore: test new label system
  packages/merge-on-green/src/merge-logic.ts
Labels: automerge: secure, cla: yes

#666 chore(merge-on-green): add to mog read me
  packages/merge-on-green/README.md
  packages/merge-on-green/src/merge-logic.ts
Labels: cla: yes

#667 feat(buildcop): use tested config type
  packages/buildcop/buildcop.go
  packages/buildcop/buildcop_test.go
Labels: cla: yes

#649 feat(buildcop): add build_url flag
  packages/buildcop/README.md
  packages/buildcop/buildcop.go
  packages/buildcop/buildcop_test.go
Labels: cla: yes

#656 feat(blunderbuss): add delay and label fetch for new issues
  packages/blunderbuss/src/blunderbuss.ts
  packages/blunderbuss/test/blunderbuss.ts
Labels: cla: yes

#646 refactor(failurechecker): clean up dependencies and exports
  packages/failurechecker/.gitignore
  packages/failurechecker/package.json
  packages/failurechecker/src/app.ts
  packages/failurechecker/src/failurechecker.ts
  packages/failurechecker/test/failurechecker.ts
Labels: cla: yes

#633 feat(auto-label): add nightly cron job
  packages/auto-label/src/auto-label.ts
  packages/auto-label/test/auto-label.ts
  packages/auto-label/test/fixtures/events/installation.json
Labels: cla: yes

#671 fix(buildcop): add extra newline to prevent title formatting
  packages/buildcop/__snapshots__/buildcop.js
  packages/buildcop/src/buildcop.ts
Labels: cla: yes

#654 feat(gcf-utils): provide a standardized logger for repo automation bots
  packages/gcf-utils/README.md
  packages/gcf-utils/package.json
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/gcf-bootstrapper.ts
  packages/gcf-utils/test/gcf-logger.ts
  packages/gcf-utils/test/integration/gcf-bootstrapper-integration.ts
  packages/gcf-utils/test/integration/gcf-logger-integration.ts
  packages/gcf-utils/test/test-helpers.ts
Labels: cla: yes

#672 chore: update GCF Utils
  packages/auto-label/package.json
Labels: cla: yes

#669 build: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#677 fix(release-please): default to java language for snapshots
  packages/release-please/src/release-please.ts
  packages/release-please/test/release-please.ts
Labels: cla: yes

#678 refactor: clean up trusted contrib bot
  packages/trusted-contribution/package.json
  packages/trusted-contribution/src/trusted-contribution.ts
Labels: cla: yes

#679 refactor(conventional-commit-lint): update deps and simplify
  packages/conventional-commit-lint/.gitignore
  packages/conventional-commit-lint/.npmrc
  packages/conventional-commit-lint/package.json
  packages/conventional-commit-lint/src/conventional-commit-lint.ts
  packages/conventional-commit-lint/src/index.d.ts
  packages/conventional-commit-lint/src/local.ts
  packages/conventional-commit-lint/tsconfig.json
Labels: cla: yes

#674 fix: page iterator in auto-label needs to iterate over issues also
  packages/auto-label/src/auto-label.ts
  packages/auto-label/test/auto-label.ts
Labels: cla: yes

#684 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#688 fix(label-sync): upgrade to latest gcf-utils, more improvements
  packages/label-sync/.gitignore
  packages/label-sync/cron
  packages/label-sync/package.json
  packages/label-sync/src/app.ts
  packages/label-sync/src/label-sync.ts
  packages/label-sync/src/labels.json
  packages/label-sync/test/test.ts
  packages/label-sync/tsconfig.json
Labels: cla: yes

#690 build(cloudbuild): increase deploy timeout
  cloudbuild.yaml
Labels: automerge, cla: yes

#682 refactor(blunderbuss): update gcf-utils and clean up
  packages/blunderbuss/.gitignore
  packages/blunderbuss/package.json
  packages/blunderbuss/src/app.ts
  packages/blunderbuss/src/blunderbuss.ts
  packages/blunderbuss/src/local.ts
  packages/blunderbuss/test/blunderbuss.ts
Labels: cla: yes

#692 fix(label-sync): handle drift data with no short name
  packages/label-sync/src/label-sync.ts
  packages/label-sync/test/test.ts
Labels: cla: yes

#670 feat(gcf-utils): Log bot execution trigger information from gcf-utils
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/fixtures/github-webhook-payload-all-info.json
  packages/gcf-utils/test/fixtures/github-webhook-payload-missing-info.json
  packages/gcf-utils/test/gcf-bootstrapper.ts
Labels: bot: merge on green, cla: yes

#693 feat: release gcf-utils with logging
  packages/gcf-utils/package.json
Labels: cla: yes

#694 fix(header-checker-lint): upgrade to latest gcf-utils
  packages/header-checker-lint/.gitignore
  packages/header-checker-lint/package.json
  packages/header-checker-lint/src/header-checker-lint.ts
Labels: cla: yes

#696 fix(gcf-utils): add missing dev dependency @types/sonic-boom
  packages/gcf-utils/package.json
Labels: cla: yes

#695 fix(label-sync): add language specific labels
  packages/label-sync/src/labels.json
Labels: cla: yes

#698 fix(auto-label): clean up dependencies
  packages/auto-label/package.json
  packages/auto-label/src/auto-label.ts
  packages/auto-label/test/auto-label.ts
Labels: cla: yes

#700 feat(gcf-utils): some bots have large payloads not appropriate for cloud task payload
  packages/buildcop/package.json
  packages/buildcop/src/app.ts
  packages/gcf-utils/package.json
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/gcf-bootstrapper.ts
Labels: cla: yes

#704 build: upgrade some bots to gcf-utils 5.2.2
  packages/auto-label/package.json
  packages/blunderbuss/package.json
  packages/conventional-commit-lint/package.json
Labels: cla: yes

#705 chore: update automerge secure label name
  packages/merge-on-green/README.md
  packages/merge-on-green/src/merge-on-green.ts
  packages/merge-on-green/test/merge-on-green.ts
Labels: cla: yes

#702 feat: auto label adds sample tag, and fixes broken tests
  packages/auto-label/src/auto-label.ts
  packages/auto-label/test/auto-label.ts
  packages/auto-label/test/fixtures/events/issue_opened_no_match_repo.json
Labels: cla: yes

#703 feat(monitoring-system): create a REST service for the Data Processor
  packages/monitoring-system/data-processor/.eslintignore
  packages/monitoring-system/data-processor/.eslintrc.json
  packages/monitoring-system/data-processor/.prettierignore
  packages/monitoring-system/data-processor/.prettierrc.js
  packages/monitoring-system/data-processor/Dockerfile
  packages/monitoring-system/data-processor/LICENSE
  packages/monitoring-system/data-processor/package.json
  packages/monitoring-system/data-processor/src/data-processor-factory.ts
  packages/monitoring-system/data-processor/src/data-processors/cloud-functions-data-processor.ts
  packages/monitoring-system/data-processor/src/data-processors/cloud-logs-data-processor.ts
  packages/monitoring-system/data-processor/src/data-processors/cloud-tasks-data-processor.ts
  packages/monitoring-system/data-processor/src/data-processors/data-processor-abstract.ts
  packages/monitoring-system/data-processor/src/data-processors/github-data-processor.ts
  packages/monitoring-system/data-processor/src/task-service.ts
  packages/monitoring-system/data-processor/test/data-processor-factory.spec.ts
  packages/monitoring-system/data-processor/test/task-service.spec.ts
  packages/monitoring-system/data-processor/tsconfig.json
Labels: automerge, cla: yes

#609 feat: Slo-status-label bot currently with linting feature
  packages/slo-stat-bot/.eslintignore
  packages/slo-stat-bot/.estlintrc.json
  packages/slo-stat-bot/.prettierignore
  packages/slo-stat-bot/.prettierrc.js
  packages/slo-stat-bot/README.md
  packages/slo-stat-bot/__snapshots__/.gitkeep
  packages/slo-stat-bot/__snapshots__/slo-stat-label.js
  packages/slo-stat-bot/data/schema.json
  packages/slo-stat-bot/package.json
  packages/slo-stat-bot/src/app.ts
  packages/slo-stat-bot/src/index.d.ts
  packages/slo-stat-bot/src/slo-stat-label.ts
  packages/slo-stat-bot/test/fixtures/config/valid-config.yml
  packages/slo-stat-bot/test/fixtures/events/contains_slo_file.json
  packages/slo-stat-bot/test/fixtures/events/invalid_blob.json
  packages/slo-stat-bot/test/fixtures/events/issue_opened.json
  packages/slo-stat-bot/test/fixtures/events/issue_slo_rules/invalid_slos/incorr_time_format.json
  packages/slo-stat-bot/test/fixtures/events/issue_slo_rules/invalid_slos/missing_resp_field.json
  packages/slo-stat-bot/test/fixtures/events/issue_slo_rules/invalid_slos/missing_time_unit.json
  packages/slo-stat-bot/test/fixtures/events/issue_slo_rules/invalid_slos/no_resolution_time.json
  packages/slo-stat-bot/test/fixtures/events/issue_slo_rules/invalid_slos/not_uri.json
  packages/slo-stat-bot/test/fixtures/events/issue_slo_rules/valid_slos/empty_array.json
  packages/slo-stat-bot/test/fixtures/events/issue_slo_rules/valid_slos/gitlabels_array_and_assignee.json
  packages/slo-stat-bot/test/fixtures/events/issue_slo_rules/valid_slos/include_pr.json
  packages/slo-stat-bot/test/fixtures/events/issue_slo_rules/valid_slos/issue_bug_and_assignee.json
  packages/slo-stat-bot/test/fixtures/events/issue_slo_rules/valid_slos/no_responders.json
  packages/slo-stat-bot/test/fixtures/events/issue_slo_rules/valid_slos/no_slo.json
  packages/slo-stat-bot/test/fixtures/events/issue_slo_rules/valid_slos/not_labeled_external.json
  packages/slo-stat-bot/test/fixtures/events/issue_slo_rules/valid_slos/responders.json
  packages/slo-stat-bot/test/fixtures/events/issue_slo_rules/valid_slos/triageme.json
  packages/slo-stat-bot/test/fixtures/events/not_contains_slo_file.json
  packages/slo-stat-bot/test/fixtures/events/pull_request_opened.json
  packages/slo-stat-bot/test/fixtures/events/valid_blob.json
  packages/slo-stat-bot/test/slo-stat-label.ts
  packages/slo-stat-bot/tsconfig.json
Labels: cla: yes

#707 chore: add config files for cloud-rad for node.js
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#706 fix(sync-repo-settings): run on all installed repositories
  packages/sync-repo-settings/package.json
  packages/sync-repo-settings/src/sync-repo-settings.ts
  packages/sync-repo-settings/test/fixtures/repos.json
  packages/sync-repo-settings/test/test.ts
Labels: cla: yes

#710 fix: exclude monitoring-system from builds
  scripts/build-functions.sh
  scripts/cron-deploy.sh
  scripts/migrate-secrets.sh
  scripts/publish-functions.sh
Labels: cla: yes

#713 fix(sync-repo-settings): always add team memberships
  packages/sync-repo-settings/src/app.ts
  packages/sync-repo-settings/src/sync-repo-settings.ts
  packages/sync-repo-settings/test/test.ts
Labels: cla: yes

#712 fix: further cloud build issues
  packages/slo-stat-bot/package.json
Labels: cla: yes

#714 fix: remove slo-stat-bot from deployment
  scripts/build-functions.sh
  scripts/cron-deploy.sh
  scripts/migrate-secrets.sh
  scripts/publish-functions.sh
Labels: cla: yes

#709 chore: add repo override for proto-plus-python
  packages/sync-repo-settings/src/required-checks.json
Labels: cla: yes

#686 feat(gcf-util): add a plugin for Octokit to automatically log bot actions
  packages/gcf-utils/package.json
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/src/logging-octokit-plugin.ts
  packages/gcf-utils/test/integration/gcf-bootstrapper-integration.ts
  packages/gcf-utils/test/logging-octokit-plugin.ts
Labels: automerge, cla: yes

#715 chore: further auto-label cleanup
  packages/auto-label/src/auto-label.ts
  packages/auto-label/test/auto-label.ts
Labels: automerge, cla: yes

#723 fix(sync-repo-settings): ignore googleapis/aip
  packages/sync-repo-settings/src/required-checks.json
Labels: cla: yes

#719 fix(mog): do not double schedule work
  packages/gcf-utils/package.json
  packages/gcf-utils/src/gcf-utils.ts
  packages/merge-on-green/package.json
  packages/merge-on-green/src/app.ts
Labels: cla: yes

#722 fix(sync-repo-settings): catch specific categories of errors
  packages/sync-repo-settings/src/sync-repo-settings.ts
Labels: cla: yes

#729 fix(slo-stat-bot): fixed build error in app.ts
  packages/slo-stat-bot/src/app.ts
Labels: cla: yes

#733 feat: logger must be turned on with config option
  packages/buildcop/package.json
  packages/buildcop/src/app.ts
  packages/gcf-utils/package.json
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/src/logging-octokit-plugin.ts
  packages/gcf-utils/test/gcf-bootstrapper.ts
  packages/gcf-utils/test/logging-octokit-plugin.ts
  packages/merge-on-green/package.json
  packages/merge-on-green/src/app.ts
  packages/release-please/package.json
Labels: cla: yes

#738 build: upgrade and enable Octokit logging for auto-label
  packages/auto-label/package.json
  packages/auto-label/src/app.ts
  packages/auto-label/test/auto-label.ts
Labels: cla: yes

#740 fix(release-please): now pinning @octokit/types breaks compile
  packages/release-please/package.json
Labels: cla: yes

#739 chore: ignore ggj from required checks
  packages/sync-repo-settings/src/required-checks.json
Labels: automerge, cla: yes

#742 chore(sync-repo-settings): ignore release-please
  packages/sync-repo-settings/src/required-checks.json
Labels: cla: yes

#741 build: upgrade blunderbuss, failurechecker and conventional commit to gcf-utils 5.2.6 and enable logging
  packages/blunderbuss/package.json
  packages/blunderbuss/src/app.ts
  packages/conventional-commit-lint/package.json
  packages/conventional-commit-lint/src/app.ts
  packages/failurechecker/package.json
  packages/failurechecker/src/app.ts
Labels: automerge, cla: yes

#735 fix(conventional-commit-lint): handle PRs with no commits
  packages/conventional-commit-lint/src/conventional-commit-lint.ts
  packages/conventional-commit-lint/test/conventional-commit-lint.ts
Labels: cla: yes

#743 build: upgrade all bots to 5.2.6 and enable logging on compatible bots
  packages/header-checker-lint/package.json
  packages/header-checker-lint/src/app.ts
  packages/label-sync/package.json
  packages/label-sync/src/app.ts
  packages/merge-on-green/src/app.ts
  packages/publish/package.json
  packages/publish/src/app.ts
  packages/slo-stat-bot/package.json
  packages/slo-stat-bot/src/app.ts
  packages/snippet-bot/package.json
  packages/snippet-bot/src/app.ts
  packages/sync-repo-settings/package.json
  packages/sync-repo-settings/src/app.ts
  packages/trusted-contribution/package.json
  packages/trusted-contribution/src/app.ts
Labels: automerge, cla: yes

#717 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#745 fix(merge-on-green): stringify object before logging
  packages/merge-on-green/src/merge-on-green.ts
Labels: automerge, cla: yes

#734 fix: use console.error for errors
  packages/auto-label/.gitignore
  packages/auto-label/src/auto-label.ts
  packages/auto-label/test/auto-label.ts
  packages/conventional-commit-lint/src/conventional-commit-lint.ts
  packages/label-sync/src/label-sync.ts
  packages/merge-on-green/src/merge-logic.ts
  packages/merge-on-green/src/merge-on-green.ts
  packages/monitoring-system/data-processor/src/data-processor-factory.ts
  packages/publish/test/publish.ts
  packages/slo-stat-bot/src/slo-stat-label.ts
Labels: cla: yes

#746 feat(GCFLogger): support Cloud Logging/Stackdriver severity levels
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/test-helpers.ts
Labels: automerge, cla: yes

#747 refactor(repo-automation-bots): migrate some bots from console logging to GCF Logger
  packages/auto-label/src/auto-label.ts
  packages/conventional-commit-lint/src/conventional-commit-lint.ts
  packages/failurechecker/src/failurechecker.ts
  packages/gcf-utils/src/gcf-utils.ts
  packages/label-sync/src/label-sync.ts
  packages/merge-on-green/src/merge-logic.ts
  packages/merge-on-green/src/merge-on-green.ts
Labels: automerge, cla: yes

#750 refactor: migrate bots to gcf logger
  packages/slo-stat-bot/src/slo-stat-label.ts
  packages/snippet-bot/src/snippet-bot.ts
  packages/sync-repo-settings/src/sync-repo-settings.ts
Labels: cla: yes

#749 fix(sync-repo-settings): stop managing checks for googleapis/disco-to-proto3-converter
  packages/sync-repo-settings/src/required-checks.json
Labels: cla: yes

#751 fix(generate-bot): remove unused dependencies from template
  packages/generate-bot/__snapshots__/generate-bot.js
  packages/generate-bot/templates/package.json
  packages/generate-bot/templates/tsconfig.json
Labels: cla: yes

#748 build: minor bump to gcf-utils version
  packages/gcf-utils/package.json
Labels: cla: yes

#752 build: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#756 build: bump some bots to gcf-utils 5.3.0 for next testing
  packages/auto-label/package.json
  packages/blunderbuss/package.json
  packages/buildcop/package.json
  packages/conventional-commit-lint/package.json
  packages/failurechecker/package.json
Labels: cla: yes

#731 feat(monitoring-system): add a data processor for Cloud Tasks data
  packages/monitoring-system/README.md
  packages/monitoring-system/data-processor/README.md
  packages/monitoring-system/data-processor/config/config.yml
  packages/monitoring-system/data-processor/package.json
  packages/monitoring-system/data-processor/src/config-util.ts
  packages/monitoring-system/data-processor/src/data-processor-factory.ts
  packages/monitoring-system/data-processor/src/data-processors/cloud-tasks-data-processor.ts
  packages/monitoring-system/data-processor/src/data-processors/data-processor-abstract.ts
  packages/monitoring-system/data-processor/test/unit/config-util.spec.ts
  packages/monitoring-system/data-processor/test/unit/data-processor-factory.spec.ts
  packages/monitoring-system/data-processor/test/unit/data-processors/cloud-tasks-data-processor.spec.ts
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/mock-firestore-data-1.json
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/mock-firestore-data-2.json
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/mock-firestore-data-3.json
  packages/monitoring-system/data-processor/test/unit/data-processors/fixtures/mock-task-queue-data-1.json
  packages/monitoring-system/data-processor/test/unit/data-processors/mock-cloud-tasks-client.ts
  packages/monitoring-system/data-processor/test/unit/data-processors/mock-firestore.ts
  packages/monitoring-system/data-processor/test/unit/fixtures/sample-config.yml
  packages/monitoring-system/data-processor/test/unit/fixtures/sample-invalid-config.yml
  packages/monitoring-system/data-processor/test/unit/task-service.spec.ts
  packages/monitoring-system/data-processor/tsconfig.json
Labels: automerge, cla: yes

#754 feat(sync-repo-settings): support repo level config
  packages/sync-repo-settings/.c8rc.json
  packages/sync-repo-settings/README.md
  packages/sync-repo-settings/package.json
  packages/sync-repo-settings/src/required-checks.json
  packages/sync-repo-settings/src/sync-repo-settings.ts
  packages/sync-repo-settings/src/teams.json
  packages/sync-repo-settings/src/types.ts
  packages/sync-repo-settings/test/fixtures/localConfig.yaml
  packages/sync-repo-settings/test/test.ts
Labels: cla: yes

#759 build: use release-please/publish for gcf-utils
  .github/publish.yml
  .github/release-please.yml
  packages/gcf-utils/package.json
  packages/publish/src/publish.ts
  packages/release-please/package.json
  packages/release-please/src/release-please.ts
Labels: cla: yes

#758 fix(gcf-utils): add repository details to payload for pub/sub triggered executions
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/gcf-bootstrapper.ts
Labels: cla: yes

#763 fix: append opts.path at end of install path
  packages/publish/src/publish.ts
Labels: cla: yes

#765 build: bump buildcop to gcf-utils 5.3.1 for testing
  packages/buildcop/package.json
Labels: cla: yes

#764 build: update remaining bots to gcf-utils 5.3.0
  packages/header-checker-lint/package.json
  packages/label-sync/package.json
  packages/merge-on-green/package.json
  packages/publish/package.json
  packages/release-please/package.json
  packages/slo-stat-bot/package.json
  packages/snippet-bot/package.json
  packages/sync-repo-settings/package.json
  packages/trusted-contribution/package.json
Labels: automerge, cla: yes

#757 chore(sync-repo-settings): java-spanner should require standard checks
  packages/sync-repo-settings/src/required-checks.json
Labels: cla: yes

#767 fix(sync-repo-settings): send magic header
  packages/sync-repo-settings/src/sync-repo-settings.ts
Labels: cla: yes

#769 refactor(gcf-utils): extract Octokit request parsing logic to separate module
  packages/gcf-utils/src/logging-octokit-plugin.ts
  packages/gcf-utils/src/octokit-request-parser.ts
Labels: automerge, cla: yes

#771 fix(buildcop): add support for Ruby logs
  packages/buildcop/__snapshots__/buildcop.js
  packages/buildcop/src/buildcop.ts
  packages/buildcop/test/buildcop.ts
  packages/buildcop/test/fixtures/testdata/ruby_one_failed.xml
Labels: cla: yes

#772 fix(sync-repo-settings): add a little more logging for overrides
  packages/sync-repo-settings/src/sync-repo-settings.ts
Labels: automerge, cla: yes

#774 docs(sync-repo-settings): fix example config yaml comments
  packages/sync-repo-settings/README.md
Labels: cla: yes

#775 fix(gcf-utils): log entire errors in specific cases
  packages/gcf-utils/src/gcf-utils.ts
Labels: cla: yes

#770 test(data-processor): implement an octokit middleware to help github related testing
  packages/monitoring-system/data-processor/package.json
  packages/monitoring-system/data-processor/src/data-processor-factory.ts
  packages/monitoring-system/data-processor/test/unit/data-processors/cloud-tasks-data-processor.spec.ts
  packages/monitoring-system/data-processor/test/unit/data-processors/mocks/mock-cloud-tasks-client.ts
  packages/monitoring-system/data-processor/test/unit/data-processors/mocks/mock-firestore.ts
  packages/monitoring-system/data-processor/test/unit/data-processors/mocks/mock-octokit-plugin.ts
  packages/monitoring-system/data-processor/test/unit/data-processors/mocks/octokit-middleware.ts
  packages/monitoring-system/data-processor/test/unit/data-processors/mocks/octokit-request-parser.ts
Labels: automerge, cla: yes

#780 fix: await datastore deletion
  packages/merge-on-green/src/merge-on-green.ts
Labels: cla: yes

#785 fix(merge-on-green): payload switches between Buffer and object
  packages/gcf-utils/src/gcf-utils.ts
Labels: cla: yes

#784 refactor(gcf-utils): move GCFLogger and buildTriggerInfo to separate files to ensure readability of code
  packages/gcf-utils/package.json
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/src/logging/gcf-logger.ts
  packages/gcf-utils/src/logging/logging-octokit-plugin.ts
  packages/gcf-utils/src/logging/octokit-request-parser.ts
  packages/gcf-utils/src/logging/trigger-info-builder.ts
  packages/gcf-utils/test/gcf-bootstrapper.ts
  packages/gcf-utils/test/gcf-logger.ts
  packages/gcf-utils/test/integration/gcf-bootstrapper-integration.ts
  packages/gcf-utils/test/integration/gcf-logger-integration.ts
  packages/gcf-utils/test/logging-octokit-plugin.ts
  packages/gcf-utils/test/trigger-info-builder.ts
Labels: automerge, cla: yes
