Repository googleapis/repo-automation-bots, pull requests merged in 2020-09, with the labels that each got.

#933 feat(auto-label): use apis.json to get full API list for auto-detect
  packages/auto-label/src/auto-label.ts
  packages/auto-label/test/auto-label.ts
Labels: cla: yes

#836 feat(slo-stat-bot): Lints for contradicting SLOs
  packages/slo-stat-bot/__snapshots__/slo-label.js
  packages/slo-stat-bot/__snapshots__/slo-lint.js
  packages/slo-stat-bot/src/slo-appliesTo.ts
  packages/slo-stat-bot/src/slo-compliant.ts
  packages/slo-stat-bot/src/slo-lint.ts
  packages/slo-stat-bot/test/fixtures/events/issue_slo_rules/invalid_slos/contradicting_slo.json
  packages/slo-stat-bot/test/fixtures/events/issue_slo_rules/valid_slos/issue_bug_and_assignee.json
Labels: cla: yes

#910 build: automate deployment for dashboard
  packages/monitoring-system/metrics-dashboard/cloudbuild.yaml
  packages/monitoring-system/metrics-dashboard/scripts/deploy.sh
  packages/monitoring-system/metrics-dashboard/scripts/get-token.sh
Labels: cla: yes

#917 build: automate deployments for data processor
  packages/monitoring-system/data-processor/cloudbuild.yaml
Labels: cla: yes

#926 feat: bind trigger information to all logs
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/src/logging/gcf-logger.ts
  packages/gcf-utils/src/logging/trigger-info-builder.ts
  packages/gcf-utils/test/gcf-bootstrapper.ts
  packages/gcf-utils/test/gcf-logger.ts
  packages/gcf-utils/test/integration/gcf-logger-integration.ts
  packages/gcf-utils/test/trigger-info-builder.ts
Labels: cla: yes

#943 feat(release-please): release-please with code-suggester
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: cla: yes

#939 feat(sync-repo-settings): add config validation
  packages/sync-repo-settings/package-lock.json
  packages/sync-repo-settings/package.json
  packages/sync-repo-settings/src/schema.json
  packages/sync-repo-settings/src/sync-repo-settings.ts
  packages/sync-repo-settings/test/fixtures/bogusConfig.yaml
  packages/sync-repo-settings/test/fixtures/invalidYamlConfig.yaml
  packages/sync-repo-settings/test/test.ts
  packages/sync-repo-settings/tsconfig.json
Labels: cla: yes

#946 feat(blunderbuss): expand GitHub teams
  packages/blunderbuss/__snapshots__/blunderbuss.js
  packages/blunderbuss/src/blunderbuss.ts
  packages/blunderbuss/test/blunderbuss.ts
  packages/blunderbuss/test/fixtures/config/on_label.yml
  packages/blunderbuss/test/fixtures/config/pr_with_team.yml
  packages/blunderbuss/test/fixtures/events/issue_labeled_for_team.json
Labels: automerge, cla: yes

#947 build: update sync-repo-settings config
  .github/CODEOWNERS
  .github/sync-repo-settings.yaml
  packages/sync-repo-settings/src/required-checks.json
Labels: cla: yes

#948 feat(auto-label): add basic auto-detect for sample issues
  packages/auto-label/src/auto-label.ts
  packages/auto-label/test/auto-label.ts
Labels: automerge, cla: yes

#949 build: fix required status checks
  .github/sync-repo-settings.yaml
Labels: cla: yes

#950 chore: clean up merge-on-green
  packages/merge-on-green/package-lock.json
  packages/merge-on-green/src/merge-logic.ts
  packages/merge-on-green/src/merge-on-green.ts
  packages/merge-on-green/test/merge-on-green.ts
Labels: cla: yes

#951 build: maybe fix the required checks
  .github/sync-repo-settings.yaml
Labels: api: cloudbuild, cla: yes

#960 chore: fix required checks
  .github/sync-repo-settings.yaml
Labels: cla: yes

#969 chore(java): remove unnecessary settings overrides
  packages/sync-repo-settings/package-lock.json
  packages/sync-repo-settings/src/required-checks.json
  packages/sync-repo-settings/test/test.ts
Labels: cla: yes

#977 fix(buildcop): sort dup closed issues by closed_at
  packages/buildcop/__snapshots__/buildcop.js
  packages/buildcop/src/buildcop.ts
  packages/buildcop/test/buildcop.ts
Labels: cla: yes

#979 feat(label-sync): allow a repo to be ignored
  packages/label-sync/src/label-sync.ts
  packages/label-sync/test/test.ts
Labels: cla: yes

#981 fix(sync-repo-settings): do not crash on file access errors
  packages/sync-repo-settings/src/sync-repo-settings.ts
Labels: cla: yes

#982 fix(label-sync): use public HTTP request to fetch labels
  packages/label-sync/.c8rc.json
  packages/label-sync/package-lock.json
  packages/label-sync/package.json
  packages/label-sync/src/label-sync.ts
  packages/label-sync/test/test.ts
Labels: cla: yes

#963 refactor(probot)!: upgrade gcf-utils to probot@10, @octokit/rest@18
  packages/gcf-utils/package-lock.json
  packages/gcf-utils/package.json
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/src/logging/octokit-request-parser.ts
  packages/gcf-utils/test/gcf-bootstrapper.ts
  packages/gcf-utils/test/integration/gcf-bootstrapper-integration.ts
  packages/gcf-utils/test/logging-octokit-plugin.ts
  packages/release-please/package-lock.json
  packages/release-please/package.json
  packages/release-please/src/release-please.ts
  packages/release-please/test/release-please.ts
Labels: cla: yes

#973 feat: require codeowner approval for python
  packages/sync-repo-settings/src/required-checks.json
Labels: cla: yes

#985 fix(sync-repo-settings): maintain and triage not available yet
  packages/sync-repo-settings/README.md
  packages/sync-repo-settings/src/schema.json
  packages/sync-repo-settings/src/sync-repo-settings.ts
  packages/sync-repo-settings/src/types.ts
Labels: cla: yes

#987 fix(sync-repo-settings): require codeowners reviews for java, remove java repo exceptions
  packages/sync-repo-settings/src/required-checks.json
Labels: cla: yes

#983 feat(gcf-utils): write payload to tmp bucket
  packages/gcf-utils/package-lock.json
  packages/gcf-utils/package.json
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/gcf-bootstrapper.ts
  scripts/publish-function.sh
Labels: cla: yes

#993 chore(deps): update Auto-Label package to latest gcf-utils v6 and probot@10
  packages/auto-label/package-lock.json
  packages/auto-label/package.json
  packages/auto-label/src/auto-label.ts
  packages/auto-label/test/auto-label.ts
Labels: cla: yes

#994 chore(deps): upgrade to latest and greatest gcf-utils
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: cla: yes

#995 chore(deps): update deps due to security warning
  packages/auto-label/package-lock.json
Labels: cla: yes
