Repository googleapis/repo-automation-bots, pull requests merged in 2020-05, with the labels that each got.

#518 fix(deps): the most recent release of moment seems to have broken types
  packages/failurechecker/package.json
Labels: cla: yes

#512 feat(Build Cop): add more detail when marking an issue flaky
  packages/buildcop/__snapshots__/buildcop.js
  packages/buildcop/src/buildcop.ts
  packages/buildcop/test/buildcop.ts
Labels: cla: yes

#520 fix(sync-repo-settings): update checks for java-bigquerystorage
  packages/sync-repo-settings/src/required-checks.json
Labels: cla: yes

#517 fix(sync-repo-settings): update checks for google-api-java-client-services
  packages/sync-repo-settings/src/required-checks.json
Labels: automerge, cla: yes

#516 fix(Build Cop): ignore skipped tests
  packages/buildcop/src/buildcop.ts
  packages/buildcop/test/buildcop.ts
  packages/buildcop/test/fixtures/testdata/go_skip.xml
Labels: automerge, cla: yes

#519 feat(Build Cop): include test logs in comments
  packages/buildcop/__snapshots__/buildcop.js
  packages/buildcop/src/buildcop.ts
  packages/buildcop/test/buildcop.ts
Labels: cla: yes

#514 fix: address bugs, add readme
  packages/generate-bot/README.md
  packages/generate-bot/__snapshots__/generate-bot.js
  packages/generate-bot/main.js
  packages/generate-bot/templates/.eslintignore
  packages/generate-bot/templates/.estlintrc.json
  packages/generate-bot/templates/.prettierignore
  packages/generate-bot/templates/package.json
  packages/generate-bot/templates/test/{{programName}}.ts
Labels: cla: yes

#524 fix(sync-repo-settings): fix google-cloud-java checks
  packages/sync-repo-settings/src/required-checks.json
Labels: cla: yes

#528 chore: add repo overrides for java-bigtable-hbase
  packages/sync-repo-settings/src/required-checks.json
Labels: cla: yes

#522 feat(auto-label): detect labels from issue titles
  packages/auto-label/__snapshots__/auto-label.js
  packages/auto-label/src/auto-label.ts
  packages/auto-label/test/auto-label.ts
  packages/auto-label/test/fixtures/events/issue_opened_spanner.json
Labels: cla: yes

#531 fix(auto-label): don't add an api: label if there already is one
  packages/auto-label/src/auto-label.ts
  packages/auto-label/test/auto-label.ts
Labels: automerge, cla: yes

#530 fix(auto-label): handle repos without a github_label
  packages/auto-label/src/auto-label.ts
  packages/auto-label/test/auto-label.ts
  packages/auto-label/test/fixtures/events/issue_opened_spanner.json
Labels: automerge, cla: yes

#533 chore(Build Cop): add more logging
  packages/buildcop/src/buildcop.ts
Labels: cla: yes

#534 fix: disable sync-repo-settings for google-api-ruby-client
  packages/sync-repo-settings/src/required-checks.json
Labels: cla: yes

#537 chore: fix nit (duplicate)
  packages/sync-repo-settings/src/required-checks.json
Labels: cla: yes

#540 chore(Build Cop): update gcf-utils, drop try/catch
  packages/buildcop/package.json
  packages/buildcop/src/buildcop.ts
Labels: cla: yes

#541 fix(Build Cop): await async function calls
  packages/buildcop/src/buildcop.ts
Labels: cla: yes

#544 feat: update required checks on repos
  packages/sync-repo-settings/src/required-checks.json
Labels: cla: yes, do not merge

#506 feat(gcf-utils)!: Use Secret Manager as opposed to KMS + GCS
  cloudbuild.yaml
  packages/gcf-utils/README.md
  packages/gcf-utils/package.json
  packages/gcf-utils/src/bin/README.md
  packages/gcf-utils/src/bin/genkey-util.ts
  packages/gcf-utils/src/bin/genkey.ts
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/gcf-utils.ts
  packages/gcf-utils/test/genkey-util.ts
  scripts/migrate-secrets.sh
  scripts/serverless-scheduler-proxy-deploy.sh
  serverless-scheduler-proxy/main.go
Labels: cla: yes

#553 fix(sync-repo-settings): fix java config
  packages/sync-repo-settings/src/required-checks.json
Labels: automerge, cla: yes

#554 feat(deps): newest release please with simple version.txt releaser
  packages/release-please/package.json
  packages/release-please/src/release-please.ts
Labels: cla: yes

#559 fix(Build Cop): downgrade gcf-utils to stop using Tasks
  packages/buildcop/package.json
Labels: cla: yes

#563 fix(sync-repo-settings): Java Pub/Sub Lite is Java 8+
  packages/sync-repo-settings/src/required-checks.json
Labels: automerge, cla: yes

#565 fix(sync-repo-settings): manage gax-java required checks
  packages/sync-repo-settings/src/required-checks.json
Labels: automerge, cla: yes
