Repository googleapis/repo-automation-bots, pull requests merged in 2020-12, with the labels that each got.

#1196 feat(auto-label): label spannertest issues as spanner
  packages/auto-label/src/auto-label.ts
Labels: cla: yes

#1197 build: use HEAD~1 if on main branch
  .github/workflows/interrogate.js
Labels: cla: yes

#1192 cleanup(snippet-bot): use Violation for unmatched region tags
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/src/region-tag-parser.ts
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/src/violations.ts
Labels: cla: yes

#1189 build(sync-repo-settings): update lock file and address test issues
  packages/sync-repo-settings/package-lock.json
  packages/sync-repo-settings/package.json
  packages/sync-repo-settings/src/sync-repo-settings.ts
  packages/sync-repo-settings/test/test.ts
  packages/sync-repo-settings/tsconfig.json
Labels: cla: yes

#1198 build: fetch the main branch
  .github/workflows/ci.yaml
  .github/workflows/interrogate.js
  packages/release-please/README.md
Labels: cla: yes

#1199 fix(build): builds failing due to format
  packages/release-please/README.md
  scripts/publish-function.sh
Labels: api: cloudbuild, cla: yes

#1200 build: also need to escape newline
  packages/release-please/README.md
  scripts/publish-function.sh
Labels: cla: yes

#1201 feat(trusted-contribution): trust the yoshi-code-bot
  packages/trusted-contribution/src/trusted-contribution.ts
Labels: cla: yes

#1204 build(do-not-merge): add cloudbuild.yaml
  packages/do-not-merge/cloudbuild.yaml
Labels: cla: yes

#1205 fix(dnm): export with underscores
  packages/do-not-merge/src/app.ts
Labels: automerge, cla: yes

#1206 feat(sync-repo-settings): auto-add cloud devrel pgms
  packages/sync-repo-settings/src/sync-repo-settings.ts
  packages/sync-repo-settings/test/test.ts
Labels: cla: yes

#1210 fix(release-please): do not close submodule PRs
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: cla: yes

#1202 feat(snippet-bot): start warning about removal of used tags
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/src/region-tag-parser.ts
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/src/snippets.ts
  packages/snippet-bot/src/violations.ts
  packages/snippet-bot/test/fixtures/snippets.json
  packages/snippet-bot/test/snippet-bot.ts
Labels: cla: yes

#1216 feat(snippet-bot): provide usage links easier to click
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/src/snippet-bot.ts
Labels: cla: yes

#1214 fix: update to latest @octokit/* dependencies
  packages/buildcop/package-lock.json
  packages/buildcop/package.json
  packages/buildcop/src/buildcop.ts
  packages/conventional-commit-lint/package-lock.json
  packages/conventional-commit-lint/package.json
  packages/conventional-commit-lint/src/conventional-commit-lint.ts
  packages/failurechecker/package-lock.json
  packages/failurechecker/package.json
  packages/failurechecker/src/failurechecker.ts
  packages/header-checker-lint/package-lock.json
  packages/header-checker-lint/package.json
  packages/header-checker-lint/src/header-checker-lint.ts
  packages/label-sync/package-lock.json
  packages/label-sync/package.json
  packages/label-sync/src/label-sync.ts
  packages/monitoring-system/data-processor/package-lock.json
  packages/monitoring-system/data-processor/package.json
Labels: cla: yes

#1221 build(metrics): update deps and lock files for metrics dash
  packages/monitoring-system/metrics-dashboard/package-lock.json
  packages/monitoring-system/metrics-dashboard/package.json
Labels: cla: yes

#1220 build(publish): update lockfiles and typescript version
  packages/publish/package-lock.json
  packages/publish/package.json
  packages/publish/src/app.ts
  packages/publish/src/index.d.ts
  packages/publish/src/publish.ts
  packages/publish/test/publish.ts
Labels: cla: yes

#1224 fix(sync-repo-settings): rename team for write
  packages/sync-repo-settings/src/sync-repo-settings.ts
  packages/sync-repo-settings/test/test.ts
Labels: cla: yes

#1229 fix(sync-repo-settings): ensure cloud dpes are always added
  packages/sync-repo-settings/src/sync-repo-settings.ts
  packages/sync-repo-settings/test/test.ts
Labels: cla: yes

#1232 docs: add link to generated-files-bot pages
  README.md
Labels: automerge, cla: yes

#1228 fix(snippet-bot): ignore empty file content
  packages/snippet-bot/src/snippet-bot.ts
Labels: automerge, cla: yes

#1233 feat(failurechecker): track multiple failures and autoclose after success
  packages/failurechecker/__snapshots__/failurechecker.js
  packages/failurechecker/src/failurechecker.ts
  packages/failurechecker/test/failurechecker.ts
Labels: cla: yes

#1236 build: update octokit test approach
  packages/blunderbuss/test/blunderbuss.ts
  packages/buildcop/package.json
  packages/buildcop/test/buildcop.ts
  packages/conventional-commit-lint/test/conventional-commit-lint.ts
  packages/do-not-merge/test/test.ts
  packages/failurechecker/package.json
  packages/failurechecker/test/failurechecker.ts
  packages/generate-bot/templates/test/test.ts
  packages/header-checker-lint/package.json
  packages/header-checker-lint/test/header-checker-lint.ts
  packages/merge-on-green/package.json
  packages/merge-on-green/test/merge-on-green.ts
  packages/release-please/test/release-please.ts
  packages/snippet-bot/package.json
  packages/snippet-bot/test/snippet-bot.ts
  packages/sync-repo-settings/package-lock.json
  packages/sync-repo-settings/package.json
  packages/sync-repo-settings/test/test.ts
  packages/trusted-contribution/package-lock.json
  packages/trusted-contribution/package.json
  packages/trusted-contribution/test/trusted-contribution.ts
Labels: cla: yes

#1209 fix(generate-bot): replace - with _ in export to match Cloud Function name
  packages/generate-bot/src/main.ts
  packages/generate-bot/templates/src/app.ts
  packages/generate-bot/test/test.ts
Labels: automerge, cla: yes

#1213 fix(merge-on-green): do not merge PRs with DNM label
  packages/merge-on-green/src/merge-logic.ts
  packages/merge-on-green/test/merge-on-green.ts
Labels: automerge, cla: yes

#1186 refactor(auto-label): product labeling code into helper file
  packages/auto-label/README.md
  packages/auto-label/src/auto-label.ts
  packages/auto-label/src/helper.ts
  packages/auto-label/test/auto-label.ts
Labels: automerge, cla: yes

#1237 chore(sync-repo-settings): use openapi types
  packages/sync-repo-settings/package-lock.json
  packages/sync-repo-settings/package.json
  packages/sync-repo-settings/src/sync-repo-settings.ts
Labels: cla: yes

#1239 build: auto assign issues and pull requests by bot
  .github/CODEOWNERS
  .github/auto-label.yml
  .github/blunderbuss.yml
Labels: cla: yes

#1243 feat(snippet-bot): add FYI comment for sample browser page removal
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/src/snippets.ts
  packages/snippet-bot/src/violations.ts
  packages/snippet-bot/test/fixtures/snippets.json
Labels: cla: yes, samples

#1247 fix(label-sync): update label descriptions
  packages/label-sync/src/labels.json
Labels: cla: yes

#1246 fix(generated-files-bot): use addOrUpdateIssueComment
  packages/generated-files-bot/__snapshots__/generated-files-bot.js
  packages/generated-files-bot/__snapshots__/template-bot.js
  packages/generated-files-bot/package-lock.json
  packages/generated-files-bot/package.json
  packages/generated-files-bot/src/generated-files-bot.ts
  packages/generated-files-bot/test/generated-files-bot.ts
Labels: cla: yes

#1249 chore(slo-stat-bot): fix lock file version and lint issues
  packages/slo-stat-bot/.eslintignore
  packages/slo-stat-bot/.prettierignore
  packages/slo-stat-bot/__snapshots__/slo-label.js
  packages/slo-stat-bot/__snapshots__/slo-lint.js
  packages/slo-stat-bot/package-lock.json
  packages/slo-stat-bot/src/slo-bot.ts
  packages/slo-stat-bot/test/slo-bot.ts
  packages/slo-stat-bot/test/slo-label.ts
  packages/slo-stat-bot/test/slo-lint.ts
Labels: automerge, cla: yes

#1252 docs(header-checker-lint): fix README configuration file name
  packages/header-checker-lint/README.md
Labels: automerge, cla: yes

#1245 feat(snippet-bot): allow `UNTRACKED` SnippetStatus
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/src/snippets.ts
  packages/snippet-bot/src/violations.ts
  packages/snippet-bot/test/fixtures/diff.txt
  packages/snippet-bot/test/fixtures/snippets.json
Labels: cla: yes

#1256 fix(snippet-bot): allow any string value for SnippetStatus
  packages/snippet-bot/src/snippets.ts
Labels: automerge, cla: yes

#1254 feat(generated-files-bot): configurable list of PR authors to ignore
  packages/generated-files-bot/README.md
  packages/generated-files-bot/src/generated-files-bot.ts
  packages/generated-files-bot/test/fixtures/config/ignore-authors.yml
  packages/generated-files-bot/test/generated-files-bot.ts
Labels: automerge, cla: yes

#1260 docs: add instructions for authenticating for system tests
  CONTRIBUTING.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#1217 fix: add cron job to pick up hanging prs
  packages/merge-on-green/src/merge-on-green.ts
  packages/merge-on-green/test/merge-on-green.ts
Labels: cla: yes
