Repository googleapis/repo-automation-bots, pull requests merged in 2021-09, with the labels that each got.

#2389 build: add workflow for updating lock files
  .github/workflows/deps.yaml
  .github/workflows/list-node-paths.js
Labels: cla: yes, automerge

#2430 chore: disable renovate dependency dashboard
  renovate.json
Labels: cla: yes, automerge: exact

#2435 chore: listen to post processors being published to cloud-devrel-public-resources
  packages/owl-bot/create-post-processor-subscription.sh
  packages/owl-bot/src/handlers.ts
Labels: cla: yes

#2436 fix: typos in subscription to cloud-devrel-public-resources
  packages/owl-bot/create-post-processor-subscription.sh
  packages/owl-bot/src/handlers.ts
Labels: cla: yes

#2433 feat: support mono repos
  packages/owl-bot/.gitignore
  packages/owl-bot/bootstrap-scan-configs.sh
  packages/owl-bot/cloud-build/copy-code-again.yaml
  packages/owl-bot/package-lock.json
  packages/owl-bot/package.json
  packages/owl-bot/src/bin/commands/copy-code-and-create-pull-request.ts
  packages/owl-bot/src/bin/commands/copy-code-into-pull-request.ts
  packages/owl-bot/src/bin/commands/copy-exists.ts
  packages/owl-bot/src/bin/commands/scan-configs.ts
  packages/owl-bot/src/config-files.ts
  packages/owl-bot/src/configs-store.ts
  packages/owl-bot/src/copy-code.ts
  packages/owl-bot/src/copy-tasks-store.ts
  packages/owl-bot/src/core.ts
  packages/owl-bot/src/database.ts
  packages/owl-bot/src/fetch-configs.ts
  packages/owl-bot/src/handlers.ts
  packages/owl-bot/src/octokit-util.ts
  packages/owl-bot/src/owl-bot.ts
  packages/owl-bot/src/scan-googleapis-gen-and-create-pull-requests.ts
  packages/owl-bot/test/copy-code.ts
  packages/owl-bot/test/core.ts
  packages/owl-bot/test/database.ts
  packages/owl-bot/test/fake-configs-store.ts
  packages/owl-bot/test/handlers.ts
  packages/owl-bot/test/make-repos.ts
  packages/owl-bot/test/owl-bot.ts
  packages/owl-bot/test/scan-googleapis-gen-and-create-pull-requests.ts
Labels: cla: yes, bot: owl-bot

#2443 fix: set default release type for manifest releaser
  packages/release-please/src/release-please.ts
  packages/release-please/test/fixtures/push_to_master_weird_language.json
  packages/release-please/test/release-please.ts
Labels: cla: yes

#2449 build: allow manual trigger of dependency update
  .github/workflows/deps.yaml
Labels: cla: yes

#2441 fix(owl-bot): Fallback to Pull, Push when Push Fails When Creating PR
  packages/owl-bot/cloud-build/copy-code-again.yaml
  packages/owl-bot/cloud-build/scan-googleapis-gen-and-create-pull-requests.yaml
  packages/owl-bot/cloud-build/update-lock-branch.yaml
  packages/owl-bot/src/create-pr.ts
Labels: cla: yes, automerge

#2476 fix: release-please tagging releases should handle alternate branches
  packages/release-please/src/release-please.ts
  packages/release-please/test/fixtures/config/valid_handle_gh_release_alternate_branch.yml
  packages/release-please/test/release-please.ts
Labels: cla: yes, automerge

#2471 docs: add README and links for release-trigger
  README.md
  packages/release-trigger/README.md
Labels: cla: yes, automerge

#2473 fix: loadOwlBotYaml should use path to .OwlBot.yaml file
  packages/owl-bot/src/bin/commands/copy-bazel-bin.ts
  packages/owl-bot/src/bin/commands/copy-code.ts
Labels: cla: yes, automerge

#2477 fix: check branch and PR if auto-approve config is modified in pieces
  packages/auto-approve/__snapshots__/auto-approve.test.js
  packages/auto-approve/__snapshots__/check-config.test.js
  packages/auto-approve/src/auto-approve.ts
  packages/auto-approve/src/check-config.ts
  packages/auto-approve/test/auto-approve.test.ts
  packages/auto-approve/test/check-config.test.ts
Labels: cla: yes

#2504 Revert "fix(owl-bot): Fallback to Pull, Push when Push Fails When Creating PR"
  packages/owl-bot/cloud-build/copy-code-again.yaml
  packages/owl-bot/cloud-build/scan-googleapis-gen-and-create-pull-requests.yaml
  packages/owl-bot/cloud-build/update-lock-branch.yaml
  packages/owl-bot/src/create-pr.ts
Labels: cla: yes, automerge: exact

#2482 fix(owl-bot): Determine loop by the last few commits
  packages/owl-bot/src/core.ts
  packages/owl-bot/test/owl-core.ts
Labels: cla: yes, automerge

#2506 Revert "fix(owl-bot): Determine loop by the last few commits"
  packages/owl-bot/src/core.ts
  packages/owl-bot/test/owl-core.ts
Labels: cla: yes

#2508 fix(owl-bot): Determine loop by the last few commits (2)
  packages/owl-bot/src/core.ts
  packages/owl-bot/test/owl-core.ts
Labels: cla: yes

#2509 feat(owl-bot): Open Status Check on Loop
  packages/owl-bot/src/owl-bot.ts
  packages/owl-bot/test/owl-bot.ts
Labels: cla: yes

#2510 feat(owl-bot): Remove OwlBot Run Label Before Post Processor
  packages/owl-bot/src/owl-bot.ts
  packages/owl-bot/test/owl-bot.ts
Labels: cla: yes

#2512 fix(release-please): release-please with fix for max PR length
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: cla: yes, automerge

#2516 fix(mono-repo-publish): root node_modules folder broke typescript compilation
  packages/mono-repo-publish/bin/mono-repo-publish.js
  packages/mono-repo-publish/src/main.js
  packages/mono-repo-publish/test/main.test.js
Labels: cla: yes

#2518 build: release-please should handle releases
  .github/release-please.yml
Labels: cla: yes

#2519 revert: "chore(deps): update dependency gcp-releasetool to v1.8.1"
  packages/release-trigger/requirements.txt
Labels: cla: yes, automerge

#2521 chore(docs): fix links to release-trigger app
  README.md
Labels: cla: yes

#2520 feat(release-please): handle closed labeling
  packages/release-please/src/release-please.ts
  packages/release-please/test/fixtures/pr_closed.json
  packages/release-please/test/fixtures/pr_closed_non_release.json
  packages/release-please/test/fixtures/pr_merged.json
  packages/release-please/test/fixtures/pr_reopened.json
  packages/release-please/test/fixtures/pr_reopened_non_release.json
  packages/release-please/test/release-please.ts
Labels: cla: yes

#2529 fix(owl-bot): Increase circuit breaker
  packages/owl-bot/src/core.ts
  packages/owl-bot/test/owl-core.ts
Labels: cla: yes

#2528 fix(flakybot): add a new comparator for finding existing issue
  packages/flakybot/__snapshots__/flakybot.test.js
  packages/flakybot/src/flakybot.ts
  packages/flakybot/test/flakybot.test.ts
Labels: cla: yes

#2560 build: lower concurrency on docs test
  .github/workflows/ci.yaml
Labels: cla: yes

#2562 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: cla: yes, automerge

#2565 feat(policy): add a check for default branch name
  packages/policy/policy-bigquery-schema.json
  packages/policy/src/policy.ts
  packages/policy/test/test.changer.ts
  packages/policy/test/test.policy.ts
Labels: cla: yes

#2531 feat: new secret-rotator service
  packages/secret-rotator/.dockerignore
  packages/secret-rotator/.eslintignore
  packages/secret-rotator/.eslintrc.json
  packages/secret-rotator/.gitignore
  packages/secret-rotator/.mocharc.js
  packages/secret-rotator/.nycrc
  packages/secret-rotator/.prettierignore
  packages/secret-rotator/.prettierrc.js
  packages/secret-rotator/Dockerfile
  packages/secret-rotator/README.md
  packages/secret-rotator/cloudbuild.yaml
  packages/secret-rotator/package-lock.json
  packages/secret-rotator/package.json
  packages/secret-rotator/src/app.ts
  packages/secret-rotator/src/index.ts
  packages/secret-rotator/src/secret-rotator.ts
  packages/secret-rotator/test/test.app.ts
  packages/secret-rotator/test/test.helper.ts
  packages/secret-rotator/tsconfig.json
  scripts/publish-cloud-run-secret-rotator.sh
Labels: cla: yes, automerge

#2569 build: fix deployment script for secret rotator
  scripts/publish-cloud-run-secret-rotator.sh
Labels: cla: yes

#2570 build: fix project ids for secret rotator deployment
  scripts/publish-cloud-run-secret-rotator.sh
Labels: cla: yes

#2573 fix(owlbot): always run post-processor if "owlbot:run" label added
  packages/owl-bot/src/owl-bot.ts
  packages/owl-bot/test/owl-bot.ts
Labels: cla: yes

#2577 fix(owlbot): break loop if bot account added label
  packages/owl-bot/src/owl-bot.ts
  packages/owl-bot/test/owl-bot.ts
Labels: cla: yes

#2579 feat(snippet-bot): allow api_shortname for samplegen samples
  packages/snippet-bot/src/violations.ts
  packages/snippet-bot/test/fixtures/violations-test-apiLabels.json
  packages/snippet-bot/test/violations.ts
Labels: cla: yes, samples

#2610 fix: improved error reporting lock.yaml failures
  packages/owl-bot/src/bin/commands/trigger-build.ts
  packages/owl-bot/src/core.ts
  packages/owl-bot/src/owl-bot.ts
  packages/owl-bot/test/owl-bot.ts
  packages/owl-bot/test/owl-core.ts
Labels: cla: yes

#2575 chore: removing linkage-monitor from required checks
  packages/sync-repo-settings/src/required-checks.json
Labels: cla: yes

#2571 feat: retry failed update-lock builds
  packages/owl-bot/src/bin/commands/scan-and-retry-failed-lock-updates.ts
  packages/owl-bot/src/bin/owl-bot.ts
  packages/owl-bot/src/scan-and-retry-failed-lock-updates.ts
  packages/owl-bot/test/scan-and-retry-failed-lock-updates.ts
Labels: cla: yes

#2613 fix: convert retry-builds into cloud run job
  packages/owl-bot/bootstrap-scan-and-retry-failed-lock-updates.sh
  packages/owl-bot/src/bin/commands/scan-and-retry-failed-lock-updates.ts
  packages/owl-bot/src/bin/commands/scan-configs.ts
  packages/owl-bot/src/serve.ts
Labels: cla: yes

#2618 fix(release-brancher): provide default branch name for PRs
  packages/release-brancher/__snapshots__/release-brancher.js
  packages/release-brancher/src/release-brancher.ts
  packages/release-brancher/test/release-brancher.ts
Labels: cla: yes, automerge

#2615 feat(release-brancher): add argument to override pull request title
  packages/release-brancher/__snapshots__/release-brancher.js
  packages/release-brancher/src/bin/commands/create-pull-request.ts
  packages/release-brancher/src/release-brancher.ts
  packages/release-brancher/test/release-brancher.ts
  packages/release-please/src/config-schema.json
Labels: cla: yes

#2621 build: remove unsupported Kokoro config field
  .kokoro/release/publish.cfg
Labels: cla: yes, automerge

#2620 fix: get installation Ids for m-o-g
  packages/merge-on-green/src/merge-on-green.ts
  packages/merge-on-green/test/merge-on-green.ts
Labels: cla: yes, automerge

#2616 fix: final tweaks used to actually create cloud run job
  packages/owl-bot/bootstrap-scan-and-retry-failed-lock-updates.sh
Labels: cla: yes

#2627 fix: uses installation IDs to clean up PRs if there
  packages/merge-on-green/src/merge-on-green.ts
Labels: cla: yes

#2622 fix(release-brancher): use "ci:" (non-releasable) in init
  packages/release-brancher/__snapshots__/release-brancher.js
  packages/release-brancher/src/release-brancher.ts
  packages/release-brancher/test/release-brancher.ts
Labels: cla: yes, automerge

#2629 feat: sync settings on repository transfer
  packages/sync-repo-settings/src/bot.ts
  packages/sync-repo-settings/test/fixtures/repository_transferred.json
  packages/sync-repo-settings/test/test.bot.ts
Labels: cla: yes, automerge

#2626 feat: flag tells owl-bot to squash first post-processor update
  packages/owl-bot/src/bin/commands/commit-post-processor-update.ts
  packages/owl-bot/src/bin/owl-bot.ts
  packages/owl-bot/src/config-files.ts
  packages/owl-bot/src/owl-bot-yaml-schema.json
  packages/owl-bot/test/commit-post-processor-update.ts
  packages/owl-bot/test/config-files.ts
  packages/owl-bot/test/dir-tree.ts
Labels: cla: yes

#2628 feat(do-not-merge): add configuration for `alwaysCreateStatusCheck`
  packages/do-not-merge/__snapshots__/test.js
  packages/do-not-merge/package-lock.json
  packages/do-not-merge/package.json
  packages/do-not-merge/src/config-schema.json
  packages/do-not-merge/src/configuration.ts
  packages/do-not-merge/src/do-not-merge.ts
  packages/do-not-merge/test/fixtures/always_create.yaml
  packages/do-not-merge/test/test.ts
  packages/do-not-merge/tsconfig.json
Labels: cla: yes, automerge
