Repository googleapis/repo-automation-bots, pull requests merged in 2021-01, with the labels that each got.

#1261 fix: hanging cron pr
  packages/merge-on-green/src/merge-on-green.ts
  packages/merge-on-green/test/merge-on-green.ts
Labels: cla: yes

#1264 fix(merge-on-green): revert adding cron job
  packages/merge-on-green/src/merge-on-green.ts
  packages/merge-on-green/test/merge-on-green.ts
Labels: cla: yes

#1266 fix(conventional-commit): Allow longer body line length
  packages/conventional-commit-lint/__snapshots__/conventional-commit-lint.js
  packages/conventional-commit-lint/package-lock.json
  packages/conventional-commit-lint/src/conventional-commit-lint.ts
  packages/conventional-commit-lint/test/conventional-commit-lint.ts
  packages/conventional-commit-lint/test/fixtures/commit_with_long_body_line_length.json
Labels: cla: yes

#1250 refactor: remove publish bot
  .github/CODEOWNERS
  .github/auto-label.yml
  .github/blunderbuss.yml
  README.md
  packages/publish/.c8rc.json
  packages/publish/.eslintignore
  packages/publish/.eslintrc.json
  packages/publish/.gitignore
  packages/publish/.mocharc.js
  packages/publish/.prettierignore
  packages/publish/.prettierrc.js
  packages/publish/CHANGELOG.md
  packages/publish/README.md
  packages/publish/__snapshots__/publish.js
  packages/publish/cloudbuild.yaml
  packages/publish/package-lock.json
  packages/publish/package.json
  packages/publish/src/app.ts
  packages/publish/src/index.d.ts
  packages/publish/src/publish.ts
  packages/publish/test/fixtures/config/valid-config.yml
  packages/publish/test/fixtures/events/pull_request_labeled.json
  packages/publish/test/fixtures/events/release_released.json
  packages/publish/test/fixtures/tiny-tarball-1.0.0.tgz
  packages/publish/test/fixtures/tiny-tarball-packument-1.json
  packages/publish/test/fixtures/tiny-tarball-packument-2.json
  packages/publish/test/publish.ts
  packages/publish/tsconfig.json
Labels: cla: yes

#1267 deps(release-please): pull in latest release-please
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: cla: yes

#1268 deps(auto-label): update deps
  packages/auto-label/package-lock.json
Labels: cla: yes

#1276 build: update snapshots for new year
  packages/header-checker-lint/__snapshots__/header-checker-lint.js
Labels: cla: yes

#1269 fix(merge-on-green): second attempt to add cron to pick up hanging PRs
  packages/merge-on-green/src/merge-logic.ts
  packages/merge-on-green/src/merge-on-green.ts
  packages/merge-on-green/test/merge-logic.ts
  packages/merge-on-green/test/merge-on-green.ts
Labels: cla: yes

#1280 fix(deps): upgrade to Probot 11
  packages/gcf-utils/package-lock.json
  packages/gcf-utils/package.json
  packages/gcf-utils/src/bin/genkey-util.ts
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/gcf-bootstrapper.ts
  packages/gcf-utils/test/gcf-utils.ts
  packages/gcf-utils/test/genkey-util.ts
  packages/gcf-utils/test/integration/gcf-bootstrapper-integration.ts
Labels: cla: yes

#1278 feat(owlbot): implementing OwlBot post-processing flow
  packages/owl-bot-post-processor/.eslintignore
  packages/owl-bot-post-processor/.eslintrc.json
  packages/owl-bot-post-processor/.mocharc.js
  packages/owl-bot-post-processor/.nycrc
  packages/owl-bot-post-processor/.prettierignore
  packages/owl-bot-post-processor/.prettierrc.js
  packages/owl-bot-post-processor/README.md
  packages/owl-bot-post-processor/cloud-build/update-pr.yaml
  packages/owl-bot-post-processor/package-lock.json
  packages/owl-bot-post-processor/package.json
  packages/owl-bot-post-processor/src/bin/commands/trigger-build.ts
  packages/owl-bot-post-processor/src/bin/owl-bot.ts
  packages/owl-bot-post-processor/src/core.ts
  packages/owl-bot-post-processor/src/index.d.ts
  packages/owl-bot-post-processor/src/index.ts
  packages/owl-bot-post-processor/test/owl-core.ts
  packages/owl-bot-post-processor/tsconfig.json
Labels: cla: yes

#1289 fix(metrics): extend metrics to 2022
  metrics/dashboards.sql
Labels: cla: yes

#1291 feat(sync-repo-settings): add a delete head branch option
  packages/sync-repo-settings/README.md
  packages/sync-repo-settings/src/schema.json
  packages/sync-repo-settings/src/sync-repo-settings.ts
  packages/sync-repo-settings/src/types.ts
  packages/sync-repo-settings/test/test.ts
Labels: cla: yes

#1290 feat(release-please): enable configuring multiple base branches
  packages/release-please/README.md
  packages/release-please/src/release-please.ts
  packages/release-please/test/fixtures/config/multi_branch.yml
  packages/release-please/test/fixtures/config/release_type_no_primary_branch.yml
  packages/release-please/test/fixtures/pull_request_labeled_feature_branch.json
  packages/release-please/test/fixtures/repository.json
  packages/release-please/test/release-please.ts
Labels: automerge, cla: yes

#1279 feat: bazel bot is bash script
  packages/bazel-bot/.gitignore
  packages/bazel-bot/README.md
  packages/bazel-bot/cloudbuild.yaml
  packages/bazel-bot/docker-image/Dockerfile
  packages/bazel-bot/docker-image/docker-main.sh
  packages/bazel-bot/docker-image/generate-googleapis-gen.sh
  packages/bazel-bot/package.json
  packages/bazel-bot/test-generate-googleapis-gen.sh
Labels: cla: yes

#1304 fix: add additional acceptance criteria for MIT headers
  packages/header-checker-lint/src/header-parser.ts
  packages/header-checker-lint/test/fixtures/mit-header.txt
  packages/header-checker-lint/test/header-parser.ts
Labels: cla: yes, type: bug

#1307 deps: update release-please to 9.3.0
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: automerge, cla: yes

#1311 fix(do-not-merge): upgrade to probot 11/gcf-utils 7
  packages/do-not-merge/package-lock.json
  packages/do-not-merge/package.json
  packages/do-not-merge/src/do-not-merge.ts
  packages/do-not-merge/test/test.ts
Labels: cla: yes

#1310 fix(conventional-commit-lint): upgrade to gcf-utils 7/Probot 11
  packages/conventional-commit-lint/package-lock.json
  packages/conventional-commit-lint/package.json
  packages/conventional-commit-lint/src/conventional-commit-lint.ts
  packages/conventional-commit-lint/test/conventional-commit-lint.ts
Labels: cla: yes

#1309 fix(buildcop): upgrade buildcop to probot 11/gcf-utils 7
  packages/buildcop/package-lock.json
  packages/buildcop/package.json
  packages/buildcop/src/buildcop.ts
  packages/buildcop/src/main.ts
  packages/buildcop/test/buildcop.ts
Labels: cla: yes

#1312 fix(failurechecker): upgrade to probot 11; gcf-utils 7
  packages/failurechecker/package-lock.json
  packages/failurechecker/package.json
  packages/failurechecker/src/failurechecker.ts
  packages/failurechecker/test/failurechecker.ts
Labels: cla: yes

#1293 fix(sync-repo-settings): update dependency ajv to v7
  packages/sync-repo-settings/package-lock.json
  packages/sync-repo-settings/package.json
Labels: cla: yes

#1319 Revert "fix(conventional-commit-lint): upgrade to gcf-utils 7/Probot 11"
  packages/conventional-commit-lint/package-lock.json
  packages/conventional-commit-lint/package.json
  packages/conventional-commit-lint/src/conventional-commit-lint.ts
  packages/conventional-commit-lint/test/conventional-commit-lint.ts
Labels: cla: yes

#1321 Revert "fix(failurechecker): upgrade to probot 11; gcf-utils 7"
  packages/failurechecker/package-lock.json
  packages/failurechecker/package.json
  packages/failurechecker/src/failurechecker.ts
  packages/failurechecker/test/failurechecker.ts
Labels: automerge, cla: yes

#1318 fix(label-sync): auto-delete old buildcop labels
  packages/label-sync/package-lock.json
  packages/label-sync/src/label-sync.ts
Labels: cla: yes

#1322 Revert "fix(do-not-merge): upgrade to probot 11/gcf-utils 7"
  packages/do-not-merge/package-lock.json
  packages/do-not-merge/package.json
  packages/do-not-merge/src/do-not-merge.ts
  packages/do-not-merge/test/test.ts
Labels: automerge, cla: yes

#1324 fix(flakybot): downgrade gcf-utils
  packages/flakybot/package-lock.json
  packages/flakybot/package.json
Labels: cla: yes

#1325 fix(flakybot): actually downgrade to probot 10
  packages/flakybot/package-lock.json
  packages/flakybot/package.json
  packages/flakybot/src/flakybot.ts
  packages/flakybot/src/main.ts
Labels: cla: yes

#1300 fix: authenticate with github app secret
  packages/bazel-bot/cloudbuild.yaml
  packages/bazel-bot/docker-image/Dockerfile
  packages/bazel-bot/docker-image/docker-main.sh
  packages/bazel-bot/docker-image/generate-googleapis-gen.sh
  packages/bazel-bot/docker-image/install-credentials.sh
  packages/bazel-bot/test-generate-googleapis-gen.sh
Labels: cla: yes

#1328 feat: add canary bot to test bot deployments end-to-end
  packages/canary-bot/.c8rc.json
  packages/canary-bot/.eslintignore
  packages/canary-bot/.eslintrc.json
  packages/canary-bot/.gitignore
  packages/canary-bot/.prettierignore
  packages/canary-bot/.prettierrc.js
  packages/canary-bot/README.md
  packages/canary-bot/package-lock.json
  packages/canary-bot/package.json
  packages/canary-bot/src/app.ts
  packages/canary-bot/src/canary-bot.ts
  packages/canary-bot/src/index.d.ts
  packages/canary-bot/test/fixtures/events/issue_opened.json
  packages/canary-bot/test/fixtures/events/issue_opened_wrong_title.json
  packages/canary-bot/test/test.ts
  packages/canary-bot/tsconfig.json
Labels: cla: yes

#1329 build(canary-bot): add cloudbuild file
  packages/canary-bot/cloudbuild.yaml
Labels: cla: yes

#1331 chore(auto-label): detect media and spansql titles
  packages/auto-label/src/helper.ts
Labels: automerge, cla: yes
