Repository googleapis/repo-automation-bots, pull requests merged in 2021-06, with the labels that each got.

#1888 feat(snippet-bot): add aggregateChecks config
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/package.json
  packages/snippet-bot/src/config-schema.json
  packages/snippet-bot/src/configuration.ts
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/src/utils.ts
  packages/snippet-bot/test/snippet-bot.ts
Labels: cla: yes

#1925 chore: add the "owlbot:run" label to labels list
  packages/label-sync/src/labels.json
Labels: cla: yes

#1921 feat(trusted-contribution): start validating config schema
  packages/trusted-contribution/package-lock.json
  packages/trusted-contribution/package.json
  packages/trusted-contribution/src/trusted-contribution.ts
Labels: automerge, cla: yes

#1920 feat(snippet-bot): start validating config schema upon retrieval
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/package.json
  packages/snippet-bot/src/snippet-bot.ts
Labels: automerge, cla: yes

#1918 feat(header-checker-lint): start validating config schema upon retrieval
  packages/header-checker-lint/package-lock.json
  packages/header-checker-lint/package.json
  packages/header-checker-lint/src/header-checker-lint.ts
Labels: automerge, cla: yes

#1919 feat(release-please): start validating config schema upon retrieval
  packages/release-please/package-lock.json
  packages/release-please/package.json
  packages/release-please/src/release-please.ts
Labels: automerge, cla: yes

#1928 Revert "feat(snippet-bot): start validating config schema upon retrieval"
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/package.json
  packages/snippet-bot/src/snippet-bot.ts
Labels: cla: yes

#1929 fix(bot-config-utils): handle an empty config file
  packages/bot-config-utils/src/bot-config-utils.ts
  packages/bot-config-utils/test/bot-config-utils.ts
  packages/bot-config-utils/test/fixtures/empty.yaml
Labels: cla: yes

#1926 chore: update blunderbuss config
  .github/blunderbuss.yml
Labels: automerge, cla: yes

#1913 chore: add release config for object-selector
  .release-please-manifest.json
  release-please-config.json
Labels: automerge, cla: yes

#1905 fix: copy .dot files, but ignore .git/ directory
  packages/owl-bot/src/copy-code.ts
  packages/owl-bot/test/copy-code.ts
  packages/owl-bot/test/dir-tree.ts
Labels: cla: yes

#1936 fix: cope with invalid regular expressions in .OwlBot.yaml
  packages/owl-bot/src/config-files.ts
  packages/owl-bot/src/database.ts
  packages/owl-bot/test/database.ts
Labels: cla: yes

#1942 fix(snippet-bot): handle renaming cases correctly
  .github/snippet-bot.yml
  packages/snippet-bot/src/region-tag-parser.ts
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/src/utils.ts
  packages/snippet-bot/test/fixtures/afterFile.txt
  packages/snippet-bot/test/fixtures/beforeFile.txt
  packages/snippet-bot/test/fixtures/diff-rename.txt
  packages/snippet-bot/test/region-tag-parser.ts
Labels: cla: yes, snippet-bot:no-prefix-req

#1941 chore: fix wrong label name in blunderbuss config
  .github/blunderbuss.yml
Labels: automerge, cla: yes

#1938 docs(flakybot): add issuePriority documentation
  packages/flakybot/README.md
Labels: cla: yes

#1931 chore: update bot-config-utils to 3.1.1
  packages/header-checker-lint/package-lock.json
  packages/header-checker-lint/package.json
  packages/release-please/package-lock.json
  packages/release-please/package.json
  packages/trusted-contribution/package-lock.json
  packages/trusted-contribution/package.json
Labels: cla: yes

#1915 feat(auto-label): start validating config schema upon retrieval
  packages/auto-label/__snapshots__/config-compatibility.js
  packages/auto-label/package-lock.json
  packages/auto-label/package.json
  packages/auto-label/src/auto-label.ts
  packages/auto-label/test/auto-label.ts
  packages/auto-label/test/config-compatibility.ts
Labels: cla: yes

#1948 fix(header-checker-lint, trusted-contribution): use sinon.assert
  packages/header-checker-lint/package-lock.json
  packages/header-checker-lint/package.json
  packages/header-checker-lint/test/header-checker-lint.ts
  packages/trusted-contribution/package-lock.json
  packages/trusted-contribution/package.json
  packages/trusted-contribution/src/trusted-contribution.ts
  packages/trusted-contribution/src/utils.ts
  packages/trusted-contribution/test/trusted-contribution.ts
Labels: cla: yes

#1947 feat(generated-files-bot): validate config schema upon retrieval
  packages/generated-files-bot/package-lock.json
  packages/generated-files-bot/package.json
  packages/generated-files-bot/src/generated-files-bot.ts
  packages/generated-files-bot/test/generated-files-bot.ts
Labels: cla: yes

#1944 fix(datastore-lock): use hashed value for datastore key
  packages/datastore-lock/.mocharc.js
  packages/datastore-lock/package-lock.json
  packages/datastore-lock/package.json
  packages/datastore-lock/src/datastore-lock.ts
Labels: automerge, cla: yes

#1952 cleanup(slo-stat-bot): remove slo-stat-bot
  .github/workflows/interrogate.js
  packages/slo-stat-bot/.eslintignore
  packages/slo-stat-bot/.eslintrc.json
  packages/slo-stat-bot/.gitignore
  packages/slo-stat-bot/.prettierignore
  packages/slo-stat-bot/.prettierrc.js
  packages/slo-stat-bot/README.md
  packages/slo-stat-bot/__snapshots__/slo-label.js
  packages/slo-stat-bot/__snapshots__/slo-lint.js
  packages/slo-stat-bot/cloudbuild.yaml
  packages/slo-stat-bot/cron.yaml
  packages/slo-stat-bot/data/schema.json
  packages/slo-stat-bot/package-lock.json
  packages/slo-stat-bot/package.json
  packages/slo-stat-bot/src/app.ts
  packages/slo-stat-bot/src/index.d.ts
  packages/slo-stat-bot/src/slo-appliesTo.ts
  packages/slo-stat-bot/src/slo-bot.ts
  packages/slo-stat-bot/src/slo-compliant.ts
  packages/slo-stat-bot/src/slo-label.ts
  packages/slo-stat-bot/src/slo-lint.ts
  packages/slo-stat-bot/src/types.ts
  packages/slo-stat-bot/test/fixtures/config/slo-stat-bot.yaml
  packages/slo-stat-bot/test/fixtures/events/issue_ooslo.json
  packages/slo-stat-bot/test/fixtures/events/issue_opened.json
  packages/slo-stat-bot/test/fixtures/events/issue_slo_rules/invalid_slos/contradicting_slo.json
  packages/slo-stat-bot/test/fixtures/events/issue_slo_rules/invalid_slos/incorr_time_format.json
  packages/slo-stat-bot/test/fixtures/events/issue_slo_rules/invalid_slos/missing_resp_field.json
  packages/slo-stat-bot/test/fixtures/events/issue_slo_rules/invalid_slos/missing_time_unit.json
  packages/slo-stat-bot/test/fixtures/events/issue_slo_rules/invalid_slos/no_resolution_time.json
  packages/slo-stat-bot/test/fixtures/events/issue_slo_rules/invalid_slos/not_uri.json
  packages/slo-stat-bot/test/fixtures/events/issue_slo_rules/valid_slos/empty_array.json
  packages/slo-stat-bot/test/fixtures/events/issue_slo_rules/valid_slos/gitlabels_array_and_assignee.json
  packages/slo-stat-bot/test/fixtures/events/issue_slo_rules/valid_slos/include_pr.json
  packages/slo-stat-bot/test/fixtures/events/issue_slo_rules/valid_slos/no_responders.json
  packages/slo-stat-bot/test/fixtures/events/issue_slo_rules/valid_slos/no_slo.json
  packages/slo-stat-bot/test/fixtures/events/issue_slo_rules/valid_slos/not_labeled_external.json
  packages/slo-stat-bot/test/fixtures/events/issue_slo_rules/valid_slos/responders.json
  packages/slo-stat-bot/test/fixtures/events/issue_slo_rules/valid_slos/triageme.json
  packages/slo-stat-bot/test/fixtures/events/pull_request_opened.json
  packages/slo-stat-bot/test/fixtures/events/slo.json
  packages/slo-stat-bot/test/slo-appliesTo.ts
  packages/slo-stat-bot/test/slo-bot.ts
  packages/slo-stat-bot/test/slo-compliant.ts
  packages/slo-stat-bot/test/slo-label.ts
  packages/slo-stat-bot/test/slo-lint.ts
  packages/slo-stat-bot/tsconfig.json
Labels: cla: yes

#1956 fix(label-utils): use datastore-lock@2.0.1
  packages/label-utils/package-lock.json
  packages/label-utils/package.json
Labels: automerge, cla: yes

#1916 feat(blunderbuss): start validating config schema upon retrieval
  packages/blunderbuss/package-lock.json
  packages/blunderbuss/package.json
  packages/blunderbuss/src/blunderbuss.ts
Labels: automerge, cla: yes

#1957 fix(blunderbuss,flakybot): use datastore-lock@2.0.1
  packages/blunderbuss/package-lock.json
  packages/blunderbuss/package.json
  packages/flakybot/package-lock.json
  packages/flakybot/package.json
  packages/flakybot/test/flakybot.test.ts
Labels: cla: yes

#1932 feat(snippet-bot): start validating config schema upon retrieval
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/package.json
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/test/fixtures/empty.yaml
  packages/snippet-bot/test/snippet-bot.ts
Labels: cla: yes

#1917 feat(flakybot): start validating config schema upon retrieval
  packages/flakybot/package-lock.json
  packages/flakybot/package.json
  packages/flakybot/src/flakybot.ts
  packages/flakybot/test/flakybot.test.ts
Labels: cla: yes

#1964 chore: address lock file issues
  packages/auto-approve/.prettierignore
  packages/auto-approve/__snapshots__/auto-approve.test.js
  packages/auto-approve/package-lock.json
  packages/auto-label/package-lock.json
  packages/auto-label/package.json
  packages/auto-label/test/language-path-tests.ts
  packages/blunderbuss/package-lock.json
  packages/policy/package-lock.json
Labels: cla: yes

#1965 chore: address lock file issues
  packages/owl-bot/package-lock.json
  packages/owl-bot/src/bin/commands/open-pr.ts
  packages/owl-bot/src/handlers.ts
  packages/owl-bot/test/create-pr.ts
  packages/owl-bot/test/fake-octokit.ts
  packages/owl-bot/test/handlers.ts
  packages/owl-bot/test/owl-core.ts
  packages/owl-bot/test/update-lock.ts
  packages/policy/package-lock.json
  packages/policy/src/changer.ts
  packages/policy/src/policy.ts
  packages/policy/test/test.changer.ts
  packages/policy/test/test.cli.ts
  packages/release-please/package-lock.json
  packages/release-please/src/release-please.ts
  packages/snippet-bot/.prettierignore
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/src/utils.ts
  packages/sync-repo-settings/package-lock.json
  packages/sync-repo-settings/src/bot.ts
Labels: cla: yes

#1945 feat(blunderbuss): start syncing blunderbuss label
  packages/blunderbuss/cloudbuild.yaml
  packages/blunderbuss/cron.yaml
  packages/blunderbuss/package-lock.json
  packages/blunderbuss/package.json
  packages/blunderbuss/src/blunderbuss.ts
  packages/blunderbuss/src/utils.ts
  packages/blunderbuss/test/blunderbuss.ts
Labels: automerge, cla: yes

#1966 chore(deps)(merge-on-green): update lock file
  packages/merge-on-green/package-lock.json
  packages/merge-on-green/package.json
  packages/merge-on-green/test/merge-logic.ts
  packages/merge-on-green/test/merge-on-green.ts
Labels: cla: yes

#1973 chore(blunderbuss): update lock file
  packages/blunderbuss/package-lock.json
Labels: cla: yes

#1972 fix(snippet-bot): add missing schema check
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/test/snippet-bot.ts
Labels: cla: yes

#1970 chore(deps)(label-sync): update lock file label sync
  packages/label-sync/package-lock.json
  packages/label-sync/package.json
  packages/label-sync/test/test.ts
Labels: cla: yes

#1975 fix(snippet-bot): fix remaining wrong calledOnceWith
  packages/snippet-bot/test/snippet-bot.ts
Labels: cla: yes

#1933 fix(bot-config-utils): ignore 404 errors
  packages/bot-config-utils/src/bot-config-utils.ts
  packages/bot-config-utils/test/bot-config-utils.ts
Labels: cla: yes

#1978 chore: add a script for updating package-lock.json
  scripts/update-package-locks.sh
Labels: cla: yes

#1981 chore: lock file maintainance
  packages/mono-repo-publish/package-lock.json
  packages/release-brancher/package-lock.json
  packages/sync-repo-settings/package-lock.json
  packages/trusted-contribution/package-lock.json
Labels: cla: yes

#1980 chore: lock file maintainance
  packages/failurechecker/package-lock.json
  packages/generate-bot/package-lock.json
  packages/header-checker-lint/package-lock.json
  packages/header-checker-lint/src/header-checker-lint.ts
  packages/header-checker-lint/src/header-parser.ts
  packages/merge-on-green/package-lock.json
Labels: automerge, cla: yes

#1979 chore: lock file maintainance
  packages/canary-bot/package-lock.json
  packages/conventional-commit-lint/package-lock.json
  packages/cron-utils/package-lock.json
  packages/do-not-merge/package-lock.json
Labels: cla: yes

#1986 fix(gcf-utils): create tasks in parallel
  packages/gcf-utils/package-lock.json
  packages/gcf-utils/package.json
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/gcf-bootstrapper.ts
Labels: cla: yes

#1991 fix(snippet-bot): use gcf-utils@8.0.2
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/package.json
  packages/snippet-bot/src/utils.ts
Labels: automerge, cla: yes

#1992 feat: allow bad SHAs to be skipped
  packages/bazel-bot/docker-image/generate-googleapis-gen.sh
Labels: cla: yes

#1996 fix: _BROKEN_SHAS should be passed to job
  packages/bazel-bot/cloudbuild.yaml
Labels: cla: yes

#1995 chore: Also run `npm update` in update-package-locks.sh
  scripts/update-package-locks.sh
Labels: cla: yes

#1998 fix: upgrade to gcf-utils@8.0.2
  packages/auto-label/package-lock.json
  packages/blunderbuss/package-lock.json
  packages/failurechecker/package-lock.json
  packages/label-sync/package-lock.json
Labels: cla: yes

#1999 fix: fix scheduler with gcf-utils@8.0.2
  packages/policy/package-lock.json
  packages/release-please/package-lock.json
  packages/sync-repo-settings/package-lock.json
Labels: cla: yes

#2001 chore(gcf-utils)!: lock file maintenance
  packages/gcf-utils/package-lock.json
  packages/gcf-utils/package.json
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/src/logging/logging-octokit-plugin.ts
  packages/gcf-utils/test/gcf-bootstrapper.ts
  packages/gcf-utils/test/integration/gcf-bootstrapper-integration.ts
Labels: cla: yes

#2008 chore: update lock file for header-checker-lint
  packages/header-checker-lint/package-lock.json
  packages/header-checker-lint/src/header-checker-lint.ts
  packages/header-checker-lint/src/header-parser.ts
Labels: cla: yes

#2005 feat(canary-bot): add a cron handler
  packages/canary-bot/cloudbuild.yaml
  packages/canary-bot/cron.yaml
  packages/canary-bot/package-lock.json
  packages/canary-bot/package.json
  packages/canary-bot/src/canary-bot.ts
  packages/canary-bot/test/test.ts
Labels: automerge, cla: yes

#2016 fix(snippet-bot): change the aggregateChecks default to true
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/src/configuration.ts
  packages/snippet-bot/test/snippet-bot.ts
Labels: cla: yes

#1940 feat(owl-bot): create issues if it finds malformed config
  packages/owl-bot/src/handlers.ts
  packages/owl-bot/src/octokit-util.ts
  packages/owl-bot/test/handlers.ts
  packages/owl-bot/test/octokit-utils.ts
Labels: bot: owl-bot, cla: yes

#1974 chore(merge-on-green): use Octokit from @octokit/rest
  packages/merge-on-green/package-lock.json
  packages/merge-on-green/package.json
  packages/merge-on-green/src/merge-logic.ts
  packages/merge-on-green/src/merge-on-green.ts
  packages/merge-on-green/test/merge-logic.ts
  packages/merge-on-green/test/merge-on-green.ts
Labels: automerge, cla: yes

#2020 build: add to CODEOWNERS
  .github/CODEOWNERS
Labels: cla: yes

#2023 fix(auto-approve): address typo with auto-approve
  packages/auto-approve/__snapshots__/auto-approve.test.js
  packages/auto-approve/__snapshots__/check-config.test.js
  packages/auto-approve/package.json
  packages/auto-approve/src/check-config.ts
  packages/auto-approve/test/auto-approve.test.ts
  packages/auto-approve/test/check-config.test.ts
Labels: cla: yes

#1891 fix: ensure that release PRs are not merged on a Friday
  packages/auto-approve/package-lock.json
  packages/auto-approve/package.json
  packages/auto-approve/src/check-pr.ts
  packages/auto-approve/src/utils-for-pr-checking.ts
  packages/auto-approve/test/additional-validation-for-versioning.test.ts
Labels: cla: yes

#2024 feat(gcf-utils)!: add onlyUpdate option to addOrUpdateIssueComment
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/fixtures/issue_only_update_event.json
  packages/gcf-utils/test/gcf-utils.ts
Labels: cla: yes

#2031 fix(snippet-bot): do not add a useless comment
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/package.json
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/test/snippet-bot.ts
Labels: cla: yes

#2028 fix(canary-bot): quieter canary
  packages/canary-bot/src/canary-bot.ts
  packages/canary-bot/test/test.ts
Labels: cla: yes

#2035 chore(canary-bot): update package.json and lock file
  packages/canary-bot/package-lock.json
  packages/canary-bot/package.json
Labels: cla: yes

#2047 fix: don't attempt to delete files that aren't there
  packages/owl-bot/.dockerignore
  packages/owl-bot/src/copy-code.ts
Labels: cla: yes

#2051 build(auto-approve): stub out date for tests
  packages/auto-approve/test/check-pr.test.ts
Labels: cla: yes

#2053 chore: update package.json and package-lock.json
  packages/auto-approve/package-lock.json
  packages/auto-approve/package.json
  packages/auto-label/package-lock.json
  packages/auto-label/package.json
  packages/blunderbuss/package-lock.json
  packages/blunderbuss/package.json
  packages/bot-config-utils/package-lock.json
  packages/bot-config-utils/package.json
Labels: cla: yes

#2054 chore: update package.json and package-lock.json
  packages/canary-bot/package-lock.json
  packages/canary-bot/package.json
  packages/conventional-commit-lint/package-lock.json
  packages/conventional-commit-lint/package.json
  packages/cron-utils/package-lock.json
  packages/cron-utils/package.json
  packages/datastore-lock/package-lock.json
  packages/datastore-lock/package.json
Labels: cla: yes

#2056 chore: update package.json and package-lock.json
  packages/do-not-merge/package-lock.json
  packages/do-not-merge/package.json
  packages/failurechecker/package-lock.json
  packages/failurechecker/package.json
  packages/flakybot/package-lock.json
  packages/flakybot/package.json
  packages/gcf-utils/package-lock.json
Labels: automerge, cla: yes

#2060 chore(blunderbuss): address warning from dependabot
  packages/blunderbuss/package-lock.json
Labels: automerge, cla: yes

#2057 chore: update package.json and package-lock.json
  packages/generate-bot/package-lock.json
  packages/generate-bot/package.json
  packages/generated-files-bot/package-lock.json
  packages/generated-files-bot/package.json
  packages/header-checker-lint/package-lock.json
  packages/header-checker-lint/package.json
  packages/header-checker-lint/src/header-checker-lint.ts
  packages/header-checker-lint/src/header-parser.ts
  packages/label-sync/package-lock.json
  packages/label-sync/package.json
Labels: automerge, cla: yes

#2059 chore: update package.json and package-lock.json
  packages/release-please/package-lock.json
  packages/release-please/package.json
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/package.json
  packages/sync-repo-settings/package-lock.json
  packages/sync-repo-settings/package.json
  packages/trusted-contribution/package-lock.json
  packages/trusted-contribution/package.json
Labels: automerge, cla: yes

#2052 fix: skip task queue retries if payload expired
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/gcf-bootstrapper.ts
Labels: automerge, cla: yes

#2058 chore: update package.json and package-lock.json
  packages/label-utils/package-lock.json
  packages/label-utils/package.json
  packages/merge-on-green/package-lock.json
  packages/merge-on-green/package.json
  packages/mono-repo-publish/package-lock.json
  packages/mono-repo-publish/package.json
  packages/policy/package-lock.json
  packages/release-brancher/package-lock.json
  packages/release-brancher/package.json
Labels: automerge, cla: yes

#2062 chore(generated-files-bot): fix warning from dependabot
  packages/generated-files-bot/package-lock.json
Labels: automerge, cla: yes

#2061 build: default all function timeouts to 9 minutes
  scripts/publish-function.sh
Labels: automerge, cla: yes

#2041 build: add npm-check-updates to update-package.locks.sh
  scripts/update-dependencies.sh
Labels: automerge, cla: yes

#2066 cleanup(gcf-utils): use Probot constructor instead of createProbot
  packages/gcf-utils/src/gcf-utils.ts
Labels: cla: yes

#2065 feat(flakybot): starts to sync its label
  packages/flakybot/cloudbuild.yaml
  packages/flakybot/cron.yaml
  packages/flakybot/package-lock.json
  packages/flakybot/package.json
  packages/flakybot/src/flakybot.ts
  packages/flakybot/src/labels.ts
  packages/flakybot/test/flakybot.test.ts
Labels: cla: yes

#1912 feat(object-selector)!: initial release of object-selector
  packages/object-selector/.c8rc.json
  packages/object-selector/.eslintignore
  packages/object-selector/.eslintrc.json
  packages/object-selector/.gitignore
  packages/object-selector/.mocharc.js
  packages/object-selector/.prettierignore
  packages/object-selector/.prettierrc.js
  packages/object-selector/CHANGELOG.md
  packages/object-selector/LICENSE
  packages/object-selector/README.md
  packages/object-selector/package-lock.json
  packages/object-selector/package.json
  packages/object-selector/recipes/archived.yaml
  packages/object-selector/recipes/cpp.yaml
  packages/object-selector/recipes/disabled.yaml
  packages/object-selector/recipes/dotnet.yaml
  packages/object-selector/recipes/go.yaml
  packages/object-selector/recipes/java.yaml
  packages/object-selector/recipes/nodejs.yaml
  packages/object-selector/recipes/php.yaml
  packages/object-selector/recipes/private.yaml
  packages/object-selector/recipes/python.yaml
  packages/object-selector/recipes/ruby.yaml
  packages/object-selector/src/cli.ts
  packages/object-selector/src/object-selector.ts
  packages/object-selector/src/selectors-schema.json
  packages/object-selector/test/cli.ts
  packages/object-selector/test/fixtures/correct.yaml
  packages/object-selector/test/fixtures/objs.json
  packages/object-selector/test/fixtures/repos.json
  packages/object-selector/test/fixtures/wrong.yaml
  packages/object-selector/test/object-selector.ts
  packages/object-selector/tsconfig.json
Labels: cla: yes

#2071 feat(release-please): start syncing label
  packages/release-please/package-lock.json
  packages/release-please/package.json
  packages/release-please/src/labels.ts
  packages/release-please/src/release-please.ts
  packages/release-please/test/release-please.ts
Labels: automerge, cla: yes

#2069 fix(gcf-utils): correctly handle scheduler task for non-background apps
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/gcf-bootstrapper.ts
Labels: automerge, cla: yes

#2077 chore(canary-bot): deploy with gcf-utils@10.0.2
  packages/canary-bot/package-lock.json
  packages/canary-bot/package.json
  packages/canary-bot/src/app.ts
Labels: cla: yes

#2078 fix(flakybot): fix the broken scheduler job
  packages/flakybot/package-lock.json
  packages/flakybot/package.json
Labels: automerge, cla: yes

#2079 feat(merge-on-green): start syncing labels
  packages/merge-on-green/cron.yaml
  packages/merge-on-green/package-lock.json
  packages/merge-on-green/package.json
  packages/merge-on-green/src/labels.ts
  packages/merge-on-green/src/merge-on-green.ts
  packages/merge-on-green/test/merge-on-green.ts
Labels: cla: yes

#2080 fix(merge-on-green): restore missing MOG scheduler job for GCP
  packages/merge-on-green/cron.yaml
  packages/merge-on-green/package-lock.json
  packages/merge-on-green/package.json
Labels: cla: yes

#2076 docs(gcf-utils): comment cleanup
  packages/gcf-utils/src/gcf-utils.ts
Labels: automerge, cla: yes

#2083 Revert "chore(canary-bot): deploy with gcf-utils@10.0.2"
  packages/canary-bot/package-lock.json
  packages/canary-bot/package.json
  packages/canary-bot/src/app.ts
Labels: cla: yes

#1868 feat(cron): add new schedule.global and schedule.installation cron handlers
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/fixtures/app_installations.json
  packages/gcf-utils/test/fixtures/app_installations_multiple.json
  packages/gcf-utils/test/gcf-bootstrapper.ts
Labels: automerge, cla: yes

#2087 Revert "cleanup(gcf-utils): use Probot constructor instead of createProbot"
  packages/gcf-utils/src/gcf-utils.ts
Labels: cla: yes

#2081 fix: include a link to Owl Bot's README in "Updates from Owl Bot" com…
  packages/owl-bot/README.md
  packages/owl-bot/cloud-build/update-pr.yaml
Labels: cla: yes

#2093 fix!: verify payload signatures
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/gcf-bootstrapper.ts
Labels: automerge, cla: yes

#2096 feat: add installation/global crons
  packages/canary-bot/cron.yaml
  packages/canary-bot/package-lock.json
  packages/canary-bot/package.json
  packages/canary-bot/src/canary-bot.ts
Labels: automerge, cla: yes

#2099 fix: temporarily disable canary payload verification
  packages/canary-bot/src/app.ts
Labels: cla: yes

#2091 fix(owl-bot): set credentials earlier in the build
  packages/owl-bot/README.md
  packages/owl-bot/cloud-build/update-pr.yaml
  packages/owl-bot/src/core.ts
Labels: cla: yes

#2100 feat(owlbot): indicate success if OwlBot is not enabled
  packages/owl-bot/src/owl-bot.ts
  packages/owl-bot/test/owl-bot.ts
Labels: cla: yes

#2104 Revert "fix: temporarily disable canary payload verification"
  packages/canary-bot/src/app.ts
Labels: automerge, cla: yes

#2101 fix: fix serverless proxy signing
  serverless-scheduler-proxy/main.go
Labels: automerge, cla: yes

#2108 fix: only provide the installationId if set
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/gcf-bootstrapper.ts
Labels: automerge, cla: yes

#2111 fix(deps): update gcf-utils to v11.0.1 in canary-bot
  packages/canary-bot/package-lock.json
  packages/canary-bot/package.json
Labels: automerge, cla: yes

#2110 feat(owlbot): require OwlBot before merging
  packages/sync-repo-settings/src/required-checks.json
  packages/sync-repo-settings/test/test.bot.ts
Labels: cla: yes

#2106 fix(owlbot): add owbot:run for trusted contributors
  packages/owl-bot/src/core.ts
  packages/owl-bot/src/owl-bot.ts
  packages/owl-bot/test/owl-bot.ts
  packages/owl-bot/test/owl-core.ts
  packages/trusted-contribution/src/config-schema.json
  packages/trusted-contribution/src/config.ts
  packages/trusted-contribution/src/trusted-contribution.ts
  packages/trusted-contribution/test/trusted-contribution.ts
Labels: cla: yes

#2027 feat(auto-approve): add logic to check incoming renovate-bot PRs for Node
  packages/auto-approve/__snapshots__/check-config.test.js
  packages/auto-approve/src/auto-approve.ts
  packages/auto-approve/src/check-config.ts
  packages/auto-approve/src/check-pr.ts
  packages/auto-approve/src/get-pr-info.ts
  packages/auto-approve/src/language-versioning-rules.json
  packages/auto-approve/src/language-versioning-rules.ts
  packages/auto-approve/src/utils-for-pr-checking.ts
  packages/auto-approve/src/valid-pr-schema.json
  packages/auto-approve/test/additional-validation-for-versioning.test.ts
  packages/auto-approve/test/check-pr.test.ts
  packages/auto-approve/test/fixtures/config/valid-schemas/valid-schema5.yml
  packages/auto-approve/test/fixtures/events/pull_request_opened_special_validation_dependency_update.json
Labels: cla: yes

#2117 fix: update libraries to gcf-utils 11
  packages/bot-config-utils/package-lock.json
  packages/bot-config-utils/package.json
  packages/cron-utils/package-lock.json
  packages/cron-utils/package.json
  packages/datastore-lock/package-lock.json
  packages/datastore-lock/package.json
  packages/label-utils/package-lock.json
  packages/label-utils/package.json
  packages/object-selector/package-lock.json
  packages/object-selector/package.json
Labels: automerge, cla: yes

#2120 fix: upgrade to gcf-utils@11
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/package.json
  packages/sync-repo-settings/package-lock.json
  packages/sync-repo-settings/package.json
  packages/trusted-contribution/package-lock.json
  packages/trusted-contribution/package.json
  packages/trusted-contribution/src/app.ts
Labels: cla: yes

#2121 fix: queue in repository tasks in parallel
  packages/gcf-utils/src/gcf-utils.ts
Labels: automerge, cla: yes

#2116 feat: add max retries config options
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/gcf-bootstrapper.ts
Labels: automerge, cla: yes

#2124 fix: update to gcf-utils@11.0.2
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/package.json
  packages/sync-repo-settings/package-lock.json
  packages/sync-repo-settings/package.json
  packages/trusted-contribution/package-lock.json
  packages/trusted-contribution/package.json
Labels: automerge, cla: yes

#2132 Revert "fix(deps): update dependency gcf-utils to v10.1.0"
  packages/merge-on-green/package-lock.json
  packages/merge-on-green/package.json
Labels: cla: yes

#2131 fix: upgrade canary-bot to gcf-utils@11.1.0
  packages/canary-bot/package-lock.json
  packages/canary-bot/package.json
Labels: automerge, cla: yes

#2129 fix: upgrades bots to gcf-utils 11
  packages/header-checker-lint/package-lock.json
  packages/header-checker-lint/package.json
  packages/header-checker-lint/src/header-checker-lint.ts
  packages/header-checker-lint/src/header-parser.ts
  packages/label-sync/package-lock.json
  packages/label-sync/package.json
  packages/owl-bot/package-lock.json
  packages/owl-bot/package.json
  packages/policy/package-lock.json
  packages/policy/package.json
  packages/policy/src/changer.ts
  packages/policy/src/cli.ts
  packages/policy/src/policy.ts
  packages/policy/test/test.bot.ts
  packages/policy/test/test.changer.ts
  packages/policy/test/test.cli.ts
  packages/policy/test/test.policy.ts
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: cla: yes

#2130 fix: upgrades bots to gcf-utils 11
  packages/conventional-commit-lint/package-lock.json
  packages/conventional-commit-lint/package.json
  packages/do-not-merge/package-lock.json
  packages/do-not-merge/package.json
  packages/failurechecker/package-lock.json
  packages/failurechecker/package.json
  packages/flakybot/package-lock.json
  packages/flakybot/package.json
  packages/generated-files-bot/package-lock.json
  packages/generated-files-bot/package.json
Labels: cla: yes

#2133 fix: upgrade bots to gcf-utils 11
  packages/auto-approve/package-lock.json
  packages/auto-approve/package.json
  packages/auto-label/package-lock.json
  packages/auto-label/package.json
  packages/blunderbuss/package-lock.json
  packages/blunderbuss/package.json
Labels: cla: yes

#2137 chore: use the new cron type for snippet-bot cron
  packages/label-utils/README.md
  packages/snippet-bot/cron.yaml
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/package.json
Labels: cla: yes

#2135 fix: don't invoke the post processor for pull requests with the
  packages/owl-bot/src/bin/commands/trigger-build.ts
  packages/owl-bot/src/core.ts
  packages/owl-bot/src/owl-bot.ts
  packages/owl-bot/test/owl-bot.ts
  packages/owl-bot/test/owl-core.ts
Labels: cla: yes

#2138 doc: add a note describing owlbot:ignore label
  packages/owl-bot/README.md
  packages/owl-bot/src/core.ts
Labels: cla: yes

#2128 feat: add helper to build a http.Server instance from a bot function
  packages/gcf-utils/package.json
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/src/server/server.ts
  packages/gcf-utils/test/gcf-bootstrapper.ts
  packages/gcf-utils/test/server.ts
Labels: automerge, cla: yes

#2119 refactor: use new cron types for merge-on-green
  packages/merge-on-green/cron.yaml
  packages/merge-on-green/package-lock.json
  packages/merge-on-green/package.json
  packages/merge-on-green/src/app.ts
  packages/merge-on-green/src/merge-on-green.ts
  packages/merge-on-green/test/merge-logic.ts
  packages/merge-on-green/test/merge-on-green.ts
Labels: automerge, cla: yes

#2153 build: add index.yaml for datastore indexes
  packages/merge-on-green/index.yaml
Labels: automerge, cla: yes

#2150 feat: allow configuration of GCFBootstrapper via constructor arguments
  cloudbuild-test/Dockerfile
  packages/gcf-utils/package-lock.json
  packages/gcf-utils/package.json
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/gcf-bootstrapper.ts
  packages/gcf-utils/test/server.ts
Labels: automerge, cla: yes

#2158 fix(gcf-utils): skip suspended installations
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/fixtures/suspended_installations.json
  packages/gcf-utils/test/gcf-bootstrapper.ts
Labels: cla: yes

#2160 fix(merge-on-green): fix the syncLabels cron handler
  packages/merge-on-green/package-lock.json
  packages/merge-on-green/package.json
Labels: cla: yes

#2141 feat(owl-bot): start syncing labels
  packages/owl-bot/cron.yaml
  packages/owl-bot/package-lock.json
  packages/owl-bot/package.json
  packages/owl-bot/src/core.ts
  packages/owl-bot/src/labels.ts
  packages/owl-bot/src/owl-bot.ts
  packages/owl-bot/test/owl-bot.ts
  packages/owl-bot/test/owl-core.ts
Labels: cla: yes

#2038 feat(owl-bot): update configs when a PR is merged
  packages/owl-bot/src/handlers.ts
  packages/owl-bot/src/owl-bot.ts
  packages/owl-bot/test/owl-bot.ts
Labels: cla: yes

#2164 fix(owl-bot): deploy scheduler jobs in cron.yaml
  packages/owl-bot/cloudbuild.yaml
Labels: cla: yes

#2166 fix(cron-utils): set attemptDeadline=540s
  packages/cron-utils/src/cron-utils.ts
Labels: cla: yes

#2172 build(owlbot): turn off signature verification until we can debug payload
  packages/gcf-utils/package.json
  packages/gcf-utils/src/gcf-utils.ts
  packages/owl-bot/package-lock.json
  packages/owl-bot/package.json
  packages/owl-bot/src/app.ts
Labels: cla: yes

#2173 chore(flakybot): temporary patch for Pub/Sub requests
  packages/flakybot/src/app.ts
Labels: cla: yes

#2170 feat: pass default branch name to post processor
  packages/owl-bot/cloud-build/update-lock-branch.yaml
Labels: cla: yes

#2168 fix(cron-utils): correctly set attemptDeadline at top level
  packages/cron-utils/src/cron-utils.ts
Labels: cla: yes

#2176 fix(gcf-utils): use raw body for signature verification
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/fixtures/payload.json
  packages/gcf-utils/test/gcf-bootstrapper.ts
Labels: cla: yes

#2177 chore: update codeowners
  .github/CODEOWNERS
Labels: automerge, cla: yes

#2181 chore(canary-bot): update to gcf-utils@11.3.1
  packages/canary-bot/package-lock.json
  packages/canary-bot/package.json
Labels: cla: yes

#2185 fix(owl-bot, flakybot): update to gcf-utils@11.3.1
  packages/flakybot/package-lock.json
  packages/flakybot/package.json
  packages/flakybot/src/app.ts
  packages/owl-bot/package-lock.json
  packages/owl-bot/package.json
  packages/owl-bot/src/app.ts
Labels: cla: yes

#2161 fix(conventional-commit-lint): allow long footer line lengths
  packages/conventional-commit-lint/__snapshots__/conventional-commit-lint.js
  packages/conventional-commit-lint/src/conventional-commit-lint.ts
  packages/conventional-commit-lint/test/conventional-commit-lint.ts
  packages/conventional-commit-lint/test/fixtures/commit_with_full_stop_in_subject.json
  packages/conventional-commit-lint/test/fixtures/commit_with_long_footer_length.json
Labels: cla: yes

#2165 fix(snippet-bot): update gcf-utils to 11.3.1
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/package.json
  packages/snippet-bot/src/app.ts
Labels: cla: yes

#2159 feat: allow queuing Cloud Tasks to hit Cloud Run service
  packages/gcf-utils/package-lock.json
  packages/gcf-utils/package.json
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/gcf-bootstrapper.ts
Labels: cla: yes

#2193 fix(auto-approve): update readme, update gcf-utils, fix owner config
  packages/auto-approve/README.md
  packages/auto-approve/package-lock.json
  packages/auto-approve/package.json
  packages/auto-approve/src/app.ts
  packages/auto-approve/src/auto-approve.ts
  packages/auto-approve/src/get-pr-info.ts
Labels: cla: yes

#2195 fix: express server should save rawBody
  packages/gcf-utils/src/server/server.ts
  packages/gcf-utils/test/server.ts
Labels: automerge, cla: yes

#2205 fix: allow google-github-actions to use merge-on-green
  packages/merge-on-green/src/merge-on-green.ts
Labels: automerge, cla: yes

#2201 fix: canary comments on issue instead of updating issue body
  packages/canary-bot/src/canary-bot.ts
  packages/canary-bot/test/test.ts
Labels: automerge, cla: yes

#2202 build: allow configuring GCF function identity
  scripts/publish-function.sh
Labels: automerge, cla: yes

#2142 build: create a duplicate canary-bot deployment to Cloud Run
  packages/canary-bot/.dockerignore
  packages/canary-bot/Dockerfile
  packages/canary-bot/cloudbuild-test.yaml
  packages/canary-bot/cloudbuild.yaml
  packages/canary-bot/package.json
  packages/canary-bot/src/server.ts
  scripts/publish-cloud-run.sh
  scripts/publish-function.sh
Labels: automerge, cla: yes

#2213 Revert "build: allow configuring GCF function identity"
  scripts/publish-function.sh
Labels: automerge, cla: yes

#2214 fix: canary on Cloud Run should target cloud run with its task
  packages/canary-bot/src/server.ts
Labels: cla: yes

#2211 fix(auto-label): skip explicit creation of labels
  packages/auto-label/src/auto-label.ts
  packages/auto-label/src/colors.json
  packages/auto-label/test/auto-label.ts
Labels: automerge, cla: yes

#2215 build: allow configuring GCF function identity
  scripts/publish-function.sh
Labels: cla: yes

#2216 fix: correctly dasherize service name for Cloud Run
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/gcf-bootstrapper.ts
Labels: automerge, cla: yes
