Repository googleapis/repo-automation-bots, pull requests merged in 2021-05, with the labels that each got.

#1712 chore: configure Renovate to update genproto later
  renovate.json
Labels: cla: yes

#1716 deps(release-please): update release-please to 11.10.0
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: cla: yes

#1720 fix(serverless-scheduler-proxy): Close secretmanager Client
  serverless-scheduler-proxy/main.go
Labels: cla: yes

#1721 fix(trusted-contribution): policy-bot is trusted
  metrics/trusted-contribution-label-added.sql
  packages/trusted-contribution/src/trusted-contribution.ts
Labels: automerge, cla: yes

#1722 fix(trusted-contribution): should use latest gcf-utils for logs
  packages/trusted-contribution/package-lock.json
  packages/trusted-contribution/package.json
Labels: cla: yes

#1715 fix: a test in database.ts
  packages/owl-bot/test/database.ts
Labels: cla: yes

#1704 feat(snippet-bot): new status checks
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/test/fixtures/config/ignore-and-always-config.yml
  packages/snippet-bot/test/fixtures/pr_event_no_prefix_req.json
  packages/snippet-bot/test/snippet-bot.ts
Labels: cla: yes

#1723 build: add next major label
  packages/label-sync/src/labels.json
Labels: cla: yes

#1669 fix: Adding HTML tags to header parser
  packages/header-checker-lint/src/header-parser.ts
  packages/header-checker-lint/test/fixtures/html-style-header.txt
  packages/header-checker-lint/test/header-parser.ts
Labels: cla: yes

#1724 fix: only create pull requests when new docker image yields changes
  packages/owl-bot/cloud-build/update-lock-branch.yaml
  packages/owl-bot/cloud-build/update-pr.yaml
  packages/owl-bot/src/bin/commands/maybe-create-pull-request-for-lock-update.ts
  packages/owl-bot/src/bin/commands/open-pr.ts
  packages/owl-bot/src/bin/commands/write-lock.ts
  packages/owl-bot/src/bin/owl-bot.ts
  packages/owl-bot/src/cmd.ts
  packages/owl-bot/src/configs-store.ts
  packages/owl-bot/src/copy-code.ts
  packages/owl-bot/src/create-pr.ts
  packages/owl-bot/src/database.ts
  packages/owl-bot/src/github-repo.ts
  packages/owl-bot/src/handlers.ts
  packages/owl-bot/src/scan-googleapis-gen-and-create-pull-requests.ts
  packages/owl-bot/src/update-lock.ts
  packages/owl-bot/test/copy-code.ts
  packages/owl-bot/test/database.ts
  packages/owl-bot/test/fake-configs-store.ts
  packages/owl-bot/test/fake-octokit.ts
  packages/owl-bot/test/github-repo.ts
  packages/owl-bot/test/handlers.ts
  packages/owl-bot/test/make-repos.ts
  packages/owl-bot/test/scan-googleapis-gen-and-create-pull-requests.ts
  packages/owl-bot/test/update-lock.ts
Labels: cla: yes

#1725 fix: issue 1709
  packages/owl-bot/src/copy-code.ts
  packages/owl-bot/src/core.ts
  packages/owl-bot/src/update-lock.ts
  packages/owl-bot/test/owl-bot.ts
Labels: cla: yes

#1735 fix: fix typo in secret name
  packages/owl-bot/cloud-build/update-lock-branch.yaml
Labels: automerge, cla: yes

#1734 fix: look at bot name, provide more helpful error message
  packages/generate-bot/src/main.ts
Labels: cla: yes

#1737 fix(label-sync): quit when failed to get config
  packages/label-sync/src/label-sync.ts
Labels: cla: yes

#1727 cleanup(snippet-bot): cleanup type
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/package.json
  packages/snippet-bot/src/snippet-bot.ts
Labels: cla: yes

#1741 fix: use a token when cloning library repos
  packages/owl-bot/src/copy-code.ts
Labels: cla: yes

#1731 feat(release-please): inject gcf-utils logger into release-please
  packages/release-please/package-lock.json
  packages/release-please/package.json
  packages/release-please/src/release-please.ts
Labels: cla: yes

#1747 fix(owlbot): await scanGoogleapisGenAndCreatePullRequests
  packages/owl-bot/src/bin/commands/scan-googleapis-gen-and-create-pull-requests.ts
Labels: cla: yes

#1754 fix: clone the pull request's branch directly
  packages/owl-bot/cloud-build/update-pr.yaml
Labels: cla: yes

#1763 fix(deps): update package-lock to update underscore to 1.12.1
  packages/generated-files-bot/package-lock.json
Labels: cla: yes

#1762 fix(deps): update package-lock to fix handlebars version
  packages/auto-label/package-lock.json
  packages/auto-label/src/auto-label.ts
Labels: automerge, cla: yes

#1758 feat(flakybot): add the config file and allow users to change the issue priority
  packages/flakybot/__snapshots__/config.js
  packages/flakybot/__snapshots__/flakybot.test.js
  packages/flakybot/package-lock.json
  packages/flakybot/package.json
  packages/flakybot/src/config-schema.json
  packages/flakybot/src/config.ts
  packages/flakybot/src/flakybot.ts
  packages/flakybot/test/config.ts
  packages/flakybot/test/fixtures/correctConfigResponse.json
  packages/flakybot/test/fixtures/filesResponse.json
  packages/flakybot/test/fixtures/pr_event.json
  packages/flakybot/test/fixtures/testdata/config.yaml
  packages/flakybot/test/fixtures/wrongConfigResponse.json
  packages/flakybot/test/fixtures/wrongFilesResponse.json
  packages/flakybot/test/flakybot.test.ts
  packages/flakybot/test/test-config-schema.json
  packages/flakybot/tsconfig.json
Labels: cla: yes

#1765 chore: add release please config for datastore-lock
  .release-please-manifest.json
  release-please-config.json
Labels: cla: yes

#1764 feat(datastore-lock)!: factoring out datastore-lock
  packages/datastore-lock/.c8rc.json
  packages/datastore-lock/.eslintignore
  packages/datastore-lock/.eslintrc.json
  packages/datastore-lock/.gitignore
  packages/datastore-lock/.mocharc.js
  packages/datastore-lock/.prettierignore
  packages/datastore-lock/.prettierrc.js
  packages/datastore-lock/CHANGELOG.md
  packages/datastore-lock/LICENSE
  packages/datastore-lock/README.md
  packages/datastore-lock/package-lock.json
  packages/datastore-lock/package.json
  packages/datastore-lock/src/datastore-lock.ts
  packages/datastore-lock/test/datastore-lock.ts
  packages/datastore-lock/tsconfig.json
Labels: cla: yes

#1767 deps(blunderbuss): update package-lock to update grpc version
  packages/blunderbuss/package-lock.json
Labels: cla: yes

#1768 cleanup(blunderbuss): switch to @github-automations/datastore-lock
  packages/blunderbuss/package-lock.json
  packages/blunderbuss/package.json
  packages/blunderbuss/src/blunderbuss.ts
  packages/blunderbuss/src/datastore-lock.ts
  packages/blunderbuss/test/datastore-lock.ts
Labels: cla: yes

#1772 chore: add metrics to confirm whether GHs mergeability is correct
  packages/merge-on-green/src/merge-logic.ts
  packages/merge-on-green/test/merge-logic.ts
Labels: cla: yes

#1769 cleanup(blunderbuss): use sinon instead of datastore-emulator
  packages/blunderbuss/package-lock.json
  packages/blunderbuss/package.json
  packages/blunderbuss/test/blunderbuss.ts
Labels: cla: yes

#1774 fix(m-o-g): grab all the last commits from a PR, not just the last 100
  packages/merge-on-green/src/merge-logic.ts
  packages/merge-on-green/test/merge-logic.ts
Labels: cla: yes

#1755 feat(auto-approve): authenticate with yoshi-approver account using secret stored in secret manager
  packages/auto-approve/__snapshots__/auto-approve.test.js
  packages/auto-approve/package-lock.json
  packages/auto-approve/package.json
  packages/auto-approve/src/auto-approve.ts
  packages/auto-approve/test/auto-approve.test.ts
Labels: cla: yes

#1771 chore: add release config for bot-config-utils
  .release-please-manifest.json
  release-please-config.json
Labels: cla: yes

#1770 feat(bot-config-utils)!: factoring out bot-config-utils
  packages/bot-config-utils/.c8rc.json
  packages/bot-config-utils/.eslintignore
  packages/bot-config-utils/.eslintrc.json
  packages/bot-config-utils/.gitignore
  packages/bot-config-utils/.mocharc.js
  packages/bot-config-utils/.prettierignore
  packages/bot-config-utils/.prettierrc.js
  packages/bot-config-utils/CHANGELOG.md
  packages/bot-config-utils/LICENSE
  packages/bot-config-utils/README.md
  packages/bot-config-utils/__snapshots__/bot-config-utils.js
  packages/bot-config-utils/package-lock.json
  packages/bot-config-utils/package.json
  packages/bot-config-utils/src/bot-config-utils.ts
  packages/bot-config-utils/test/bot-config-utils.ts
  packages/bot-config-utils/test/fixtures/brokenConfigResponse.json
  packages/bot-config-utils/test/fixtures/config.yaml
  packages/bot-config-utils/test/fixtures/correctConfigResponse.json
  packages/bot-config-utils/test/fixtures/filesResponse.json
  packages/bot-config-utils/test/fixtures/pr_event.json
  packages/bot-config-utils/test/fixtures/wrongConfigResponse.json
  packages/bot-config-utils/test/fixtures/wrongFilesResponse.json
  packages/bot-config-utils/test/fixtures/wrongFilesResponse2.json
  packages/bot-config-utils/test/test-config-schema.json
  packages/bot-config-utils/tsconfig.json
Labels: cla: yes

#1759 fix(generated-files-bot): Use `sender` in addition to PR user
  packages/generated-files-bot/src/generated-files-bot.ts
Labels: cla: yes

#1707 feat: additional validation for release PRs
  packages/auto-approve/src/auto-approve.ts
  packages/auto-approve/src/check-pr.ts
  packages/auto-approve/src/get-pr-info.ts
  packages/auto-approve/src/language-versioning-rules.json
  packages/auto-approve/src/utils-for-pr-checking.ts
  packages/auto-approve/test/additional-validation-for-versioning.test.ts
  packages/auto-approve/test/auto-approve.test.ts
  packages/auto-approve/test/check-pr.test.ts
  packages/auto-approve/test/fixtures/config/valid-schemas/valid-schema4.yml
  packages/auto-approve/test/fixtures/events/pull_request_opened_special_validation.json
  packages/auto-approve/test/get-pr-info.test.ts
Labels: cla: yes

#1785 fix(bot-config-utils): fix getConfig
  packages/bot-config-utils/src/bot-config-utils.ts
  packages/bot-config-utils/test/bot-config-utils.ts
Labels: cla: yes

#1789 fix!: rename organization to google-automations
  .release-please-manifest.json
  packages/bot-config-utils/package-lock.json
  packages/bot-config-utils/package.json
  packages/datastore-lock/package-lock.json
  packages/datastore-lock/package.json
Labels: cla: yes

#1792 docs(google-automations): fix the package name in README
  packages/bot-config-utils/README.md
  packages/datastore-lock/README.md
Labels: cla: yes

#1798 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#1795 fix: use the docker image provided by actools team for bazel bot
  packages/bazel-bot/docker-image/Dockerfile
Labels: cla: yes

#1776 fix(flakybot): use lock for updating an issue
  packages/flakybot/package-lock.json
  packages/flakybot/package.json
  packages/flakybot/src/flakybot.ts
  packages/flakybot/test/flakybot.test.ts
Labels: cla: yes

#1800 fix(release-please): prevent crashes in findBranchConfiguration
  packages/release-please/src/release-please.ts
Labels: cla: yes

#1797 feat(header-checker-lint): use bot-config-utils
  packages/header-checker-lint/package-lock.json
  packages/header-checker-lint/package.json
  packages/header-checker-lint/src/config-schema.json
  packages/header-checker-lint/src/config.ts
  packages/header-checker-lint/src/header-checker-lint.ts
  packages/header-checker-lint/test/fixtures/config_copyright_holder.yml
  packages/header-checker-lint/test/fixtures/config_ignored_files.yml
  packages/header-checker-lint/test/fixtures/pull_request_synchronized.json
  packages/header-checker-lint/test/header-checker-lint.ts
  packages/header-checker-lint/tsconfig.json
Labels: cla: yes

#1793 feat(bot-config-utils): allow fetching the config from the PR head
  packages/bot-config-utils/README.md
  packages/bot-config-utils/src/bot-config-utils.ts
  packages/bot-config-utils/test/bot-config-utils.ts
Labels: cla: yes

#1802 fix(bot-config-utils)!: match the return type of getConfigs
  packages/bot-config-utils/src/bot-config-utils.ts
  packages/bot-config-utils/test/bot-config-utils.ts
Labels: cla: yes

#1804 fix(header-checker-lint): use config from PR head
  packages/header-checker-lint/README.md
  packages/header-checker-lint/__snapshots__/header-checker-lint.js
  packages/header-checker-lint/package-lock.json
  packages/header-checker-lint/package.json
  packages/header-checker-lint/src/header-checker-lint.ts
  packages/header-checker-lint/test/header-checker-lint.ts
Labels: cla: yes

#1808 fix(snippet-bot): do not exit early if alwaysCreateStatusCheck is true
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/test/fixtures/diff_without_regiontag_changes.txt
  packages/snippet-bot/test/snippet-bot.ts
Labels: cla: yes

#1806 fix(sync-repo-settings): add more logging to sync-repo-settings
  packages/sync-repo-settings/src/bot.ts
  packages/sync-repo-settings/src/sync-repo-settings.ts
Labels: automerge, cla: yes

#1810 fix(sync-repo-settings): check against the correct ref structure
  packages/sync-repo-settings/src/bot.ts
  packages/sync-repo-settings/test/test.bot.ts
Labels: automerge, cla: yes

#1813 chore: release config for label-utils
  .release-please-manifest.json
  release-please-config.json
Labels: cla: yes

#1811 cleanup(header-checker-lint): use bot-config-utils 3.0.0
  packages/header-checker-lint/package-lock.json
  packages/header-checker-lint/package.json
  packages/header-checker-lint/src/header-checker-lint.ts
  packages/header-checker-lint/test/header-checker-lint.ts
Labels: cla: yes

#1812 feat(label-utils)!: label-utils initial release
  packages/label-utils/.c8rc.json
  packages/label-utils/.eslintignore
  packages/label-utils/.eslintrc.json
  packages/label-utils/.gitignore
  packages/label-utils/.mocharc.js
  packages/label-utils/.prettierignore
  packages/label-utils/.prettierrc.js
  packages/label-utils/CHANGELOG.md
  packages/label-utils/LICENSE
  packages/label-utils/README.md
  packages/label-utils/__snapshots__/label-utils.js
  packages/label-utils/package-lock.json
  packages/label-utils/package.json
  packages/label-utils/src/label-utils.ts
  packages/label-utils/test/label-utils.ts
  packages/label-utils/tsconfig.json
Labels: automerge, cla: yes

#1757 feat: support multiple .OwlBot.yamls in one repo
  packages/owl-bot/package-lock.json
  packages/owl-bot/package.json
  packages/owl-bot/src/bin/commands/copy-code-and-create-pull-request.ts
  packages/owl-bot/src/bin/commands/copy-exists.ts
  packages/owl-bot/src/configs-store.ts
  packages/owl-bot/src/copy-code.ts
  packages/owl-bot/src/copy-tasks-store.ts
  packages/owl-bot/src/database.ts
  packages/owl-bot/src/fetch-configs.ts
  packages/owl-bot/src/handlers.ts
  packages/owl-bot/src/scan-googleapis-gen-and-create-pull-requests.ts
  packages/owl-bot/test/copy-code.ts
  packages/owl-bot/test/database.ts
  packages/owl-bot/test/fake-configs-store.ts
  packages/owl-bot/test/handlers.ts
  packages/owl-bot/test/scan-googleapis-gen-and-create-pull-requests.ts
Labels: cla: yes

#1786 fix(blunderbuss): refresh the issue within the lock
  packages/blunderbuss/package-lock.json
  packages/blunderbuss/package.json
  packages/blunderbuss/src/blunderbuss.ts
  packages/blunderbuss/test/blunderbuss.ts
  packages/blunderbuss/test/fixtures/issues/no_assignees.json
  packages/blunderbuss/test/fixtures/issues/with_assignees.json
Labels: automerge, cla: yes

#1819 Revert "feat: support multiple .OwlBot.yamls in one repo"
  packages/owl-bot/package-lock.json
  packages/owl-bot/package.json
  packages/owl-bot/src/bin/commands/copy-code-and-create-pull-request.ts
  packages/owl-bot/src/bin/commands/copy-exists.ts
  packages/owl-bot/src/configs-store.ts
  packages/owl-bot/src/copy-code.ts
  packages/owl-bot/src/copy-tasks-store.ts
  packages/owl-bot/src/database.ts
  packages/owl-bot/src/fetch-configs.ts
  packages/owl-bot/src/handlers.ts
  packages/owl-bot/src/scan-googleapis-gen-and-create-pull-requests.ts
  packages/owl-bot/test/copy-code.ts
  packages/owl-bot/test/database.ts
  packages/owl-bot/test/fake-configs-store.ts
  packages/owl-bot/test/handlers.ts
  packages/owl-bot/test/scan-googleapis-gen-and-create-pull-requests.ts
Labels: cla: yes

#1821 feat: support multiple .OwlBot.yamls Redux
  packages/owl-bot/package-lock.json
  packages/owl-bot/package.json
  packages/owl-bot/src/bin/commands/copy-code-and-create-pull-request.ts
  packages/owl-bot/src/bin/commands/copy-exists.ts
  packages/owl-bot/src/configs-store.ts
  packages/owl-bot/src/copy-code.ts
  packages/owl-bot/src/copy-tasks-store.ts
  packages/owl-bot/src/database.ts
  packages/owl-bot/src/fetch-configs.ts
  packages/owl-bot/src/handlers.ts
  packages/owl-bot/src/scan-googleapis-gen-and-create-pull-requests.ts
  packages/owl-bot/test/copy-code.ts
  packages/owl-bot/test/database.ts
  packages/owl-bot/test/fake-configs-store.ts
  packages/owl-bot/test/handlers.ts
  packages/owl-bot/test/scan-googleapis-gen-and-create-pull-requests.ts
Labels: cla: yes

#1823 chore: Revert "feat: support multiple .OwlBot.yamls Redux (#1821)"
  packages/owl-bot/package-lock.json
  packages/owl-bot/package.json
  packages/owl-bot/src/bin/commands/copy-code-and-create-pull-request.ts
  packages/owl-bot/src/bin/commands/copy-exists.ts
  packages/owl-bot/src/configs-store.ts
  packages/owl-bot/src/copy-code.ts
  packages/owl-bot/src/copy-tasks-store.ts
  packages/owl-bot/src/database.ts
  packages/owl-bot/src/fetch-configs.ts
  packages/owl-bot/src/handlers.ts
  packages/owl-bot/src/scan-googleapis-gen-and-create-pull-requests.ts
  packages/owl-bot/test/copy-code.ts
  packages/owl-bot/test/database.ts
  packages/owl-bot/test/fake-configs-store.ts
  packages/owl-bot/test/handlers.ts
  packages/owl-bot/test/scan-googleapis-gen-and-create-pull-requests.ts
Labels: cla: yes

#1826 fix(gcf-utils)!: fix getAuthenticatedOctokit
  cloudbuild-test/Dockerfile
  cloudbuild-test/cloudbuild.yaml
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/integration/gcf-bootstrapper-integration.ts
  packages/gcf-utils/test/integration/gcf-logger-integration.ts
Labels: cla: yes

#1830 fix(snippet-bot): fix the scheduler handler
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/package.json
Labels: cla: yes

#1822 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  owlbot.py
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#1831 fix(auto-label,release-please): fix scheduler
  packages/auto-label/package-lock.json
  packages/auto-label/package.json
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: cla: yes

#1833 build: configure cron-utils packages for release
  .release-please-manifest.json
  release-please-config.json
Labels: automerge, cla: yes

#1824 feat!: add cron-utils package
  packages/cron-utils/.c8rc.json
  packages/cron-utils/.eslintignore
  packages/cron-utils/.eslintrc.json
  packages/cron-utils/.gitignore
  packages/cron-utils/.mocharc.js
  packages/cron-utils/.prettierignore
  packages/cron-utils/.prettierrc.js
  packages/cron-utils/LICENSE
  packages/cron-utils/README.md
  packages/cron-utils/package-lock.json
  packages/cron-utils/package.json
  packages/cron-utils/src/cli.ts
  packages/cron-utils/src/cron-utils.ts
  packages/cron-utils/test/cli.ts
  packages/cron-utils/test/cron-utils.ts
  packages/cron-utils/test/fixtures/cron-multiple.yaml
  packages/cron-utils/test/fixtures/cron.txt
  packages/cron-utils/test/fixtures/cron.yaml
  packages/cron-utils/tsconfig.json
Labels: automerge, cla: yes

#1837 fix(cron-utils): slice args
  packages/cron-utils/src/cli.ts
Labels: cla: yes

#1835 build: use cron-utils to deploy crons
  packages/failurechecker/cloudbuild.yaml
  packages/label-sync/cloudbuild.yaml
  packages/merge-on-green/cloudbuild.yaml
  packages/policy/cloudbuild.yaml
  packages/release-please/cloudbuild.yaml
  packages/slo-stat-bot/cloudbuild.yaml
  packages/sync-repo-settings/cloudbuild.yaml
  scripts/cron-deploy.sh
Labels: automerge, cla: yes

#1840 fix(cron-utils): set timezone to Americas/Los_Angeles
  packages/cron-utils/src/cron-utils.ts
Labels: cla: yes

#1843 build: function name for crons should be underscored, not dasherized
  scripts/cron-deploy.sh
Labels: cla: yes

#1853 fix(gcf-utils): skip archived repository for scheduler task
  packages/gcf-utils/src/gcf-utils.ts
Labels: cla: yes

#1842 build: convert release-please cron to cron.yaml
  packages/release-please/cron
  packages/release-please/cron.yaml
Labels: automerge, cla: yes

#1851 feat(generated-files-bot): migrate to bot-config-utils
  packages/generated-files-bot/__snapshots__/generated-files-bot.js
  packages/generated-files-bot/package-lock.json
  packages/generated-files-bot/package.json
  packages/generated-files-bot/src/config-schema.json
  packages/generated-files-bot/src/config.ts
  packages/generated-files-bot/src/generated-files-bot.ts
  packages/generated-files-bot/test/fixtures/config/broken.yml
  packages/generated-files-bot/test/fixtures/config/java.yml
  packages/generated-files-bot/test/fixtures/config/nodejs.yml
  packages/generated-files-bot/test/generated-files-bot.ts
  packages/generated-files-bot/tsconfig.json
Labels: cla: yes

#1844 build: migrate bots to cron.yaml
  packages/auto-label/cloudbuild.yaml
  packages/auto-label/cron.yaml
  packages/failurechecker/cron
  packages/failurechecker/cron.yaml
  packages/label-sync/cron
  packages/label-sync/cron.yaml
  packages/merge-on-green/cron
  packages/merge-on-green/cron.yaml
  packages/policy/cron
  packages/policy/cron.yaml
  packages/slo-stat-bot/cron
  packages/slo-stat-bot/cron.yaml
  packages/snippet-bot/cloudbuild.yaml
  packages/snippet-bot/cron.yaml
  packages/sync-repo-settings/cron
  packages/sync-repo-settings/cron.yaml
Labels: automerge, cla: yes

#1858 build: quote cron schedules
  packages/merge-on-green/cron.yaml
  packages/slo-stat-bot/cron.yaml
Labels: cla: yes

#1860 build(merge-on-green): fix yaml spacing
  packages/merge-on-green/cron.yaml
Labels: cla: yes

#1850 feat(auto-label): migrate to bot-config-utils
  packages/auto-label/__snapshots__/config-compatibility.js
  packages/auto-label/package-lock.json
  packages/auto-label/package.json
  packages/auto-label/src/auto-label.ts
  packages/auto-label/src/config-schema.json
  packages/auto-label/src/helper.ts
  packages/auto-label/test/auto-label.ts
  packages/auto-label/test/config-compatibility.ts
  packages/auto-label/test/fixtures/config/cloud-ops-sandbox-broken.yml
  packages/auto-label/test/fixtures/config/cloud-ops-sandbox.yml
  packages/auto-label/test/language-path-tests.ts
  packages/auto-label/test/test-helper.ts
Labels: cla: yes

#1859 feat(release-please): migrate to bot-config-utils
  packages/release-please/__snapshots__/compatibility-test.js
  packages/release-please/package-lock.json
  packages/release-please/package.json
  packages/release-please/src/config-constants.ts
  packages/release-please/src/config-schema.json
  packages/release-please/src/release-please.ts
  packages/release-please/test/compatibility-test.ts
  packages/release-please/test/fixtures/config/java-broken.yml
  packages/release-please/test/fixtures/config/java.yml
  packages/release-please/test/fixtures/config/manifest.yml
  packages/release-please/test/fixtures/pr_opened.json
  packages/release-please/test/release-please.ts
  packages/release-please/tsconfig.json
Labels: cla: yes

#1865 fix(snippet-bot, auto-label): skip archived repos
  packages/auto-label/package-lock.json
  packages/auto-label/package.json
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/package.json
Labels: cla: yes

#1867 fix(snippet-bot): schedule a task at a different time
  packages/snippet-bot/cron.yaml
Labels: cla: yes

#1870 fix!: stop parsing legacy cron format
  packages/cron-utils/README.md
  packages/cron-utils/src/cli.ts
  packages/cron-utils/src/cron-utils.ts
  packages/cron-utils/test/cli.ts
  packages/cron-utils/test/cron-utils.ts
  packages/cron-utils/test/fixtures/cron.txt
Labels: cla: yes

#1872 fix!: createOrUpdate can update all fields
  packages/cron-utils/src/cli.ts
  packages/cron-utils/src/cron-utils.ts
  packages/cron-utils/test/cron-utils.ts
Labels: cla: yes

#1879 chore: use /gcbrun annotation
  .github/trusted-contribution.yml
Labels: cla: yes

#1873 feat(trusted-contribution): migrate to bot-config-utils
  packages/trusted-contribution/__snapshots__/validation-test.js
  packages/trusted-contribution/package-lock.json
  packages/trusted-contribution/package.json
  packages/trusted-contribution/src/config-schema.json
  packages/trusted-contribution/src/config.ts
  packages/trusted-contribution/src/trusted-contribution.ts
  packages/trusted-contribution/test/fixtures/broken.yml
  packages/trusted-contribution/test/fixtures/disabled.yml
  packages/trusted-contribution/test/trusted-contribution.ts
  packages/trusted-contribution/test/validation-test.ts
  packages/trusted-contribution/tsconfig.json
Labels: cla: yes

#1882 fix(trusted-contribution): Use Github token from secret manager
  packages/trusted-contribution/package-lock.json
  packages/trusted-contribution/package.json
  packages/trusted-contribution/src/trusted-contribution.ts
  packages/trusted-contribution/src/utils.ts
  packages/trusted-contribution/test/trusted-contribution.ts
Labels: cla: yes

#1897 fix: never create a PR with a title > 255 characters
  packages/owl-bot/src/create-pr.ts
  packages/owl-bot/test/create-pr.ts
Labels: cla: yes

#1887 feat: pull the lock-update commit message from the docker image
  packages/owl-bot/cloud-build/update-lock-branch.yaml
Labels: cla: yes

#1903 fix(owlbot): do not crash on missing label
  packages/owl-bot/src/owl-bot.ts
  packages/owl-bot/test/owl-bot.ts
Labels: cla: yes

#1904 fix(owlbot): address bugs with running owlbot against fork
  packages/owl-bot/src/bin/commands/test-webhook.ts
  packages/owl-bot/src/core.ts
  packages/owl-bot/src/owl-bot.ts
  packages/owl-bot/test/owl-bot.ts
Labels: cla: yes

#1890 feat(bot-config-utils): add getConfigOptions
  packages/bot-config-utils/README.md
  packages/bot-config-utils/__snapshots__/bot-config-utils.js
  packages/bot-config-utils/src/bot-config-utils.ts
  packages/bot-config-utils/test/bot-config-utils.ts
  packages/bot-config-utils/test/fixtures/broken.yaml
  packages/bot-config-utils/test/fixtures/brokenConfigResponse.json
  packages/bot-config-utils/test/fixtures/correctConfigResponse.json
  packages/bot-config-utils/test/fixtures/filesResponse.json
  packages/bot-config-utils/test/fixtures/list-config.yaml
  packages/bot-config-utils/test/fixtures/wrong.yaml
  packages/bot-config-utils/test/fixtures/wrongConfigResponse.json
  packages/bot-config-utils/test/fixtures/wrongFilesResponse.json
  packages/bot-config-utils/test/fixtures/wrongFilesResponse2.json
  packages/bot-config-utils/test/test-config-schema.json
  packages/bot-config-utils/test/test-config-use-external-id.json
Labels: cla: yes
