Repository googleapis/repo-automation-bots, pull requests merged in 2021-12, with the labels that each got.

#2980 fix(policy): do not throw for missing branch
  packages/policy/package-lock.json
  packages/policy/src/bot.ts
  packages/policy/src/changer.ts
  packages/policy/test/test.changer.ts
Labels: cla: yes

#2947 fix(bot-config-util): decrease pagination size from 100 to 50, move to async iterator
  packages/bot-config-utils/src/bot-config-utils.ts
  packages/bot-config-utils/test/bot-config-utils.ts
Labels: cla: yes

#2993 build(bazel-bot): build with --allow-releaseinfo-change
  packages/bazel-bot/docker-image/Dockerfile
Labels: cla: yes

#2997 fix(bazel-bot): Temporary fix for #2996 to specify the branch
  packages/bazel-bot/docker-image/generate-googleapis-gen.sh
Labels: cla: yes

#2983 feat(owl-bot): Acknowledge Ignore label Before Updating PRs
  packages/owl-bot/README.md
  packages/owl-bot/cloud-build/update-pr.yaml
  packages/owl-bot/src/bin/commands/commit-post-processor-update.ts
  packages/owl-bot/src/fetch-configs.ts
  packages/owl-bot/test/commit-post-processor-update.ts
Labels: cla: yes

#3000 fix: Rename staleness.critical config parameter to staleness.extraold and update README.md
  packages/auto-label/README.md
  packages/auto-label/src/auto-label.ts
  packages/auto-label/src/config-schema.json
  packages/auto-label/src/helper.ts
  packages/auto-label/test/auto-label.ts
  packages/auto-label/test/fixtures/config/valid-config-staleness.yml
  packages/label-sync/src/labels.json
Labels: automerge: exact

#2981 feat(repo-metadata-lint): implement .repo-metadata.json linting
  README.md
  packages/repo-metadata-lint/.c8rc.json
  packages/repo-metadata-lint/.eslintignore
  packages/repo-metadata-lint/.eslintrc.json
  packages/repo-metadata-lint/.gitignore
  packages/repo-metadata-lint/.mocharc.js
  packages/repo-metadata-lint/.prettierignore
  packages/repo-metadata-lint/.prettierrc.js
  packages/repo-metadata-lint/README.md
  packages/repo-metadata-lint/cloudbuild.yaml
  packages/repo-metadata-lint/cron.yaml
  packages/repo-metadata-lint/package-lock.json
  packages/repo-metadata-lint/package.json
  packages/repo-metadata-lint/src/app.ts
  packages/repo-metadata-lint/src/bin/commands/scan-repo.ts
  packages/repo-metadata-lint/src/bin/repo-metadata-lint.ts
  packages/repo-metadata-lint/src/error-message-text.ts
  packages/repo-metadata-lint/src/file-iterator.ts
  packages/repo-metadata-lint/src/issue-opener.ts
  packages/repo-metadata-lint/src/repo-metadata-lint.ts
  packages/repo-metadata-lint/src/repo-metadata-schema.json
  packages/repo-metadata-lint/src/utils/octokit-util.ts
  packages/repo-metadata-lint/src/validate.ts
  packages/repo-metadata-lint/test/issue-opener.ts
  packages/repo-metadata-lint/test/repo-metadata-lint.ts
  packages/repo-metadata-lint/test/validate.ts
  packages/repo-metadata-lint/tsconfig.json
Labels: cla: yes

#3011 fix(bazel-bot): skip declaring bash variable read-only
  packages/bazel-bot/docker-image/generate-googleapis-gen.sh
Labels: automerge

#2998 test: add container test for bazel-bot image
  packages/bazel-bot/docker-image/cloudbuild-test.yaml
  packages/bazel-bot/docker-image/container-test.yaml
Labels: cla: yes, automerge

#2978 feat: record docker image's creation timestamp in .OwlBot.lock.yaml
  packages/owl-bot/package-lock.json
  packages/owl-bot/package.json
  packages/owl-bot/src/bin/commands/write-lock.ts
  packages/owl-bot/src/docker-api.ts
  packages/owl-bot/system-test/docker-api.ts
Labels: cla: yes

#3040 deps: update release-please dependencies
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: automerge

#3051 docs(auto-label): add spacing to README.md
  packages/auto-label/README.md
Labels: automerge
