Repository googleapis/repo-automation-bots, pull requests merged in 2021-04, with the labels that each got.

#1593 feat(mono-repo-publish): migrate to repo-automation-bots
  packages/mono-repo-publish/.gitignore
  packages/mono-repo-publish/CHANGELOG.md
  packages/mono-repo-publish/LICENSE
  packages/mono-repo-publish/README.md
  packages/mono-repo-publish/bin/mono-repo-publish.js
  packages/mono-repo-publish/package-lock.json
  packages/mono-repo-publish/package.json
  packages/mono-repo-publish/src/main.js
  packages/mono-repo-publish/test/fixtures/app-id
  packages/mono-repo-publish/test/fixtures/installation-id
  packages/mono-repo-publish/test/fixtures/private-key
  packages/mono-repo-publish/test/fixtures/pull-request-payloads/many-files.json
  packages/mono-repo-publish/test/main.test.js
  release-please-config.json
Labels: cla: yes

#1596 build(mono-repo-publish): update manifest to reflect currently published version
  .release-please-manifest.json
Labels: cla: yes

#1597 fix(mono-repo-publish): links should point to repo-automation-bots
  packages/mono-repo-publish/package.json
Labels: cla: yes

#1599 build: add cloud build file to auto-approve
  packages/auto-approve/cloudbuild.yaml
Labels: cla: yes

#1604 build: add json file when compiling
  packages/auto-approve/package-lock.json
  packages/auto-approve/src/check-config.ts
  packages/auto-approve/tsconfig.json
Labels: cla: yes

#1565 build: deploy crons per-function
  packages/failurechecker/cloudbuild.yaml
  packages/label-sync/cloudbuild.yaml
  packages/merge-on-green/cloudbuild.yaml
  packages/policy/cloudbuild.yaml
  packages/release-please/cloudbuild.yaml
  packages/slo-stat-bot/cloudbuild.yaml
  packages/sync-repo-settings/cloudbuild.yaml
  scripts/cron-deploy.sh
  serverless-scheduler-proxy/cloudbuild.yaml
Labels: cla: yes

#1608 build: fix number of args check
  scripts/cron-deploy.sh
Labels: automerge, cla: yes

#1611 fix(deps): update @octokit-webhooks manually
  packages/blunderbuss/package-lock.json
  packages/blunderbuss/package.json
  packages/blunderbuss/src/blunderbuss.ts
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: cla: yes

#1613 feat: create a second pull request to the new branch duplicating ci config
  packages/release-brancher/README.md
  packages/release-brancher/__snapshots__/release-brancher.js
  packages/release-brancher/package-lock.json
  packages/release-brancher/src/bin/commands/create-pull-request.ts
  packages/release-brancher/src/release-brancher.ts
  packages/release-brancher/test/fixtures/workflows/empty-objects.yaml
  packages/release-brancher/test/fixtures/workflows/non-object.yaml
  packages/release-brancher/test/fixtures/workflows/only-pull-request.yaml
  packages/release-brancher/test/fixtures/workflows/only-push.yaml
  packages/release-brancher/test/fixtures/workflows/push-pull-request-branches.yaml
  packages/release-brancher/test/release-brancher.ts
Labels: automerge, cla: yes

#1612 fix(deps): update dependency ajv to v8 manually
  packages/auto-approve/__snapshots__/check-config.test.js
  packages/auto-approve/package-lock.json
  packages/auto-approve/package.json
  packages/auto-approve/test/check-config.test.ts
  packages/owl-bot/package-lock.json
  packages/owl-bot/package.json
  packages/slo-stat-bot/__snapshots__/.gitkeep
  packages/slo-stat-bot/__snapshots__/slo-bot.js
  packages/slo-stat-bot/__snapshots__/slo-lint.js
  packages/slo-stat-bot/package-lock.json
  packages/slo-stat-bot/package.json
  packages/sync-repo-settings/package-lock.json
  packages/sync-repo-settings/package.json
Labels: cla: yes

#1617 fix: do not trigger on the missing releases for 'simple' release type
  packages/failurechecker/src/failurechecker.ts
Labels: automerge, cla: yes

#1618 feat: scripts for migrating python and nodejs repos
  scripts/migrate-owl-bot/README.md
  scripts/migrate-owl-bot/migrate-owl-bot-nodejs.ps1
  scripts/migrate-owl-bot/migrate-owl-bot-python.ps1
Labels: cla: yes

#1620 feat(owlbot): link to cloud build job from post processor
  packages/owl-bot/src/bin/commands/trigger-build.ts
  packages/owl-bot/src/core.ts
  packages/owl-bot/src/owl-bot.ts
  packages/owl-bot/test/owl-bot.ts
Labels: cla: yes

#1619 fix(auto-approve): nits regarding types during deployment
  packages/auto-approve/__snapshots__/auto-approve.test.js
  packages/auto-approve/src/auto-approve.ts
  packages/auto-approve/src/check-config.ts
  packages/auto-approve/test/auto-approve.test.ts
  packages/auto-approve/test/check-config.test.ts
Labels: cla: yes

#1627 fix: various improvements to node migrate script
  scripts/migrate-owl-bot/migrate-owl-bot-nodejs.ps1
Labels: automerge, cla: yes

#1629 feat(release-please): allow configuring extra files
  packages/release-please/README.md
  packages/release-please/package-lock.json
  packages/release-please/package.json
  packages/release-please/src/release-please.ts
  packages/release-please/test/fixtures/config/extra_files.yml
  packages/release-please/test/release-please.ts
Labels: automerge, cla: yes

#1635 fix(owlbot): explain what the lock file does
  packages/owl-bot/src/handlers.ts
Labels: cla: yes

#1640 feat(label-sync): added label for end of life
  packages/label-sync/src/labels.json
Labels: automerge, cla: yes

#1642 feat: update bazel query to include rules instead of tar.gz output files
  packages/bazel-bot/docker-image/generate-googleapis-gen.sh
  packages/bazel-bot/test-generate-googleapis-gen.sh
Labels: cla: yes

#1644 fix(merge-on-green): ignore 404 when removing a label
  packages/merge-on-green/src/merge-on-green.ts
Labels: cla: yes

#1645 feat(generated-files-bot): support glob matching
  packages/generated-files-bot/README.md
  packages/generated-files-bot/__snapshots__/generated-files-bot.js
  packages/generated-files-bot/package-lock.json
  packages/generated-files-bot/package.json
  packages/generated-files-bot/src/generated-files-bot.ts
  packages/generated-files-bot/test/fixtures/config/valid-config.yml
  packages/generated-files-bot/test/generated-files-bot.ts
Labels: automerge, cla: yes

#1652 deps: update release-please to 11.8.0
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: cla: yes

#1630 feat(sync-repo-settings): add CLI for debugging
  packages/sync-repo-settings/README.md
  packages/sync-repo-settings/package-lock.json
  packages/sync-repo-settings/package.json
  packages/sync-repo-settings/src/cli.ts
  packages/sync-repo-settings/test/test.cli.ts
Labels: cla: yes

#1651 feat(auto-label): support dashes and more prefixes
  packages/auto-label/src/helper.ts
  packages/auto-label/test/auto-label.ts
Labels: automerge, cla: yes

#1655 feat(gcf-utils): extend logger to populate count/event/type
  packages/gcf-utils/README.md
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/src/logging/gcf-logger.ts
  packages/gcf-utils/test/gcf-logger.ts
  packages/gcf-utils/test/test-helpers.ts
Labels: cla: yes

#1660 fix(gcf-utils): address octokit type regressions
  packages/gcf-utils/package-lock.json
  packages/gcf-utils/package.json
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/gcf-bootstrapper.ts
Labels: cla: yes

#1662 feat(snippet-bot): start emitting metrics
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/package.json
  packages/snippet-bot/src/snippet-bot.ts
Labels: cla: yes

#1656 feat(metrics): add metrics for a few automations
  packages/do-not-merge/package-lock.json
  packages/do-not-merge/package.json
  packages/do-not-merge/src/do-not-merge.ts
  packages/flakybot/package-lock.json
  packages/flakybot/package.json
  packages/flakybot/src/flakybot.ts
  packages/release-please/package-lock.json
  packages/release-please/package.json
  packages/release-please/src/release-please.ts
Labels: cla: yes

#1628 refactor(auto-approve): check first if config is being modified by PR before checking config in repo
  packages/auto-approve/__snapshots__/auto-approve.test.js
  packages/auto-approve/src/auto-approve.ts
  packages/auto-approve/test/auto-approve.test.ts
Labels: cla: yes

#1663 docs: add installation instructions for auto-approve bot in README
  README.md
Labels: automerge, cla: yes

#1664 build(m-o-g): add logging for bigquery graphs
  packages/merge-on-green/package-lock.json
  packages/merge-on-green/package.json
  packages/merge-on-green/src/merge-logic.ts
  packages/merge-on-green/src/merge-on-green.ts
Labels: cla: yes

#1666 fix(sync-repo-settings): remove local ignore and override configs
  packages/sync-repo-settings/src/required-checks.json
  packages/sync-repo-settings/src/sync-repo-settings.ts
  packages/sync-repo-settings/test/test.bot.ts
Labels: cla: yes

#1670 deps: update release-please to 11.8.1
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: automerge, cla: yes

#1671 fix(auto-approve): use create instead of submit review, nits to README and error logging
  packages/auto-approve/README.md
  packages/auto-approve/__snapshots__/auto-approve.test.js
  packages/auto-approve/__snapshots__/check-config.test.js
  packages/auto-approve/src/auto-approve.ts
  packages/auto-approve/src/get-PR-info.ts
  packages/auto-approve/src/valid-pr-schema.json
  packages/auto-approve/test/auto-approve.test.ts
  packages/auto-approve/test/fixtures/config/invalid-schemas/invalid-schema3.yml
  packages/auto-approve/test/fixtures/config/invalid-schemas/invalid-schema5.yml
  packages/auto-approve/test/fixtures/config/invalid-schemas/invalid-schema6.yml
  packages/auto-approve/test/fixtures/config/valid-schemas/valid-schema1.yml
  packages/auto-approve/test/fixtures/config/valid-schemas/valid-schema3.yml
Labels: cla: yes

#1674 fix: update release-brancher PR title to force and initial sp release
  packages/release-brancher/__snapshots__/release-brancher.js
  packages/release-brancher/src/release-brancher.ts
Labels: cla: yes

#1665 fix: open DRAFT pull requests for .Owlbot.lock file updates
  packages/owl-bot/package-lock.json
  packages/owl-bot/package.json
  packages/owl-bot/src/core.ts
  packages/owl-bot/src/handlers.ts
  packages/owl-bot/src/owl-bot.ts
  packages/owl-bot/test/owl-bot.ts
Labels: cla: yes

#1588 feat(policy): send pull requests to add SECURITY.md
  packages/policy/src/changer.ts
  packages/policy/test/test.changer.ts
Labels: cla: yes

#1682 feat(trusted): add optional comment configuration
  packages/trusted-contribution/README.md
  packages/trusted-contribution/package-lock.json
  packages/trusted-contribution/package.json
  packages/trusted-contribution/src/trusted-contribution.ts
  packages/trusted-contribution/test/fixtures/gcbrun.yml
  packages/trusted-contribution/test/trusted-contribution.ts
Labels: cla: yes

#1681 refactor(sync-repo-settings): split config out from the bot
  packages/sync-repo-settings/README.md
  packages/sync-repo-settings/src/bot.ts
  packages/sync-repo-settings/src/config.ts
  packages/sync-repo-settings/test/test.config.ts
Labels: cla: yes

#1685 feat(policy): prepare to run scans on GoogleCloudPlatform org
  packages/policy/src/bot.ts
  packages/policy/test/test.bot.ts
Labels: cla: yes

#1688 metrics: add additional context to metrics
  packages/merge-on-green/src/merge-logic.ts
  packages/merge-on-green/src/merge-on-green.ts
  packages/release-please/src/release-please.ts
Labels: cla: yes

#1694 chore: add sql for snippet-bot metrics
  metrics/snippet-bot-number-of-prevented-violations.sql
Labels: cla: yes

#1695 metrics: add metrics to version control
  metrics/do-not-merge-labeled.sql
  metrics/flakybot-issues-opened.sql
  metrics/legacy-dashboards.sql
  metrics/merge-on-green-labeled.sql
  metrics/merge-on-green-merged.sql
  metrics/release-please-releases.sql
  metrics/total-people-hours.sql
Labels: cla: yes

#1693 chore: Add title and author option for auto-approve
  packages/auto-approve/README.md
  packages/auto-approve/__snapshots__/check-config.test.js
  packages/auto-approve/src/valid-pr-schema.json
  packages/auto-approve/test/fixtures/config/invalid-schemas/invalid-schema5.yml
  packages/auto-approve/test/fixtures/config/valid-schemas/valid-schema1.yml
  packages/auto-approve/test/fixtures/config/valid-schemas/valid-schema3.yml
Labels: cla: yes

#1621 feat(owlbot): support owlbot:run label
  packages/owl-bot/package-lock.json
  packages/owl-bot/package.json
  packages/owl-bot/src/owl-bot.ts
  packages/owl-bot/test/owl-bot.ts
Labels: cla: yes

#1697 fix(policy): do not use search API due to rate limiting
  packages/policy/src/bot.ts
  packages/policy/src/changer.ts
  packages/policy/src/cli.ts
  packages/policy/test/test.bot.ts
  packages/policy/test/test.changer.ts
  packages/policy/test/test.cli.ts
Labels: cla: yes

#1699 build: Add `generate-files-bot` config
  .github/generated-files-bot.yml
  synth.metadata
Labels: cla: yes, context: full

#1701 feat(snippet-bot): add alwaysCreateStatusCheck config
  packages/snippet-bot/README.md
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/package.json
  packages/snippet-bot/src/config-schema.json
  packages/snippet-bot/src/configuration.ts
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/test/fixtures/broken_config.json
  packages/snippet-bot/test/fixtures/diff-broken-config.txt
  packages/snippet-bot/test/snippet-bot.ts
  packages/snippet-bot/tsconfig.json
Labels: cla: yes

#1703 feat: init metrics for `generated_files_bot`
  packages/generated-files-bot/package-lock.json
  packages/generated-files-bot/package.json
  packages/generated-files-bot/src/generated-files-bot.ts
Labels: cla: yes

#1702 docs(m-o-g): add more details to README
  packages/merge-on-green/README.md
Labels: automerge, cla: yes

#1706 fix(snippet-bot): limit the length of the issue comment
  packages/snippet-bot/src/snippet-bot.ts
Labels: cla: yes
