Repository googleapis/repo-automation-bots, pull requests merged in 2021-02, with the labels that each got.

#1337 fix: remaining issues discovered while deploying to cloud build
  packages/bazel-bot/.gcloudignore
  packages/bazel-bot/cloudbuild.yaml
  packages/bazel-bot/docker-image/Dockerfile
  packages/bazel-bot/docker-image/docker-main.sh
  packages/bazel-bot/docker-image/generate-googleapis-gen.sh
  packages/bazel-bot/docker-image/install-credentials.sh
Labels: cla: yes

#1339 chore: update CODEOWNERS config
  .repo-metadata.json
Labels: automerge, cla: yes

#1294 feat(owl-bot): start loading image from config
  packages/owl-bot-post-processor/.nycrc
  packages/owl-bot-post-processor/cloud-build/update-pr.yaml
  packages/owl-bot-post-processor/package-lock.json
  packages/owl-bot-post-processor/package.json
  packages/owl-bot-post-processor/src/app.ts
  packages/owl-bot-post-processor/src/bin/commands/trigger-build.ts
  packages/owl-bot-post-processor/src/core.ts
  packages/owl-bot-post-processor/src/owl-bot-post-processor.ts
  packages/owl-bot-post-processor/test/owl-bot-post-processor.ts
  packages/owl-bot-post-processor/test/owl-core.ts
Labels: cla: yes

#1340 deps: update release-please to 9.5.0-candidate.0
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: cla: yes

#1343 fix: avoid unpredictable repo state
  packages/bazel-bot/docker-image/generate-googleapis-gen.sh
Labels: cla: yes

#1344 fix: push two refs with one 'git push statement'
  packages/bazel-bot/docker-image/generate-googleapis-gen.sh
  packages/bazel-bot/test-generate-googleapis-gen.sh
Labels: cla: yes

#1349 deps: update release-please to 10.0.0-candidate.0
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: cla: yes

#1341 chore: skeleton for owl-bot responding to new docker images
  packages/owl-bot-post-processor/test/owl-bot-post-processor.ts
  packages/owl-bot/.eslintignore
  packages/owl-bot/.eslintrc.json
  packages/owl-bot/.mocharc.js
  packages/owl-bot/.nycrc
  packages/owl-bot/.prettierignore
  packages/owl-bot/.prettierrc.js
  packages/owl-bot/README.md
  packages/owl-bot/cloud-build/update-pr.yaml
  packages/owl-bot/package-lock.json
  packages/owl-bot/package.json
  packages/owl-bot/src/app.ts
  packages/owl-bot/src/bin/commands/list-repos-affected-by-docker-image.ts
  packages/owl-bot/src/bin/commands/trigger-build.ts
  packages/owl-bot/src/bin/owl-bot.ts
  packages/owl-bot/src/core.ts
  packages/owl-bot/src/index.d.ts
  packages/owl-bot/src/index.ts
  packages/owl-bot/src/owl-bot.ts
  packages/owl-bot/test/owl-bot.ts
  packages/owl-bot/test/owl-core.ts
  packages/owl-bot/tsconfig.json
Labels: cla: yes

#1351 testing(sync-repo-settings): add a test for skipping branch protection
  packages/sync-repo-settings/test/fixtures/localConfigWithoutBranchProtection.yaml
  packages/sync-repo-settings/test/test.ts
Labels: cla: yes

#1345 fix(gcf-utils): upgrade to Probot 11, with e2e deployment test
  packages/gcf-utils/package-lock.json
  packages/gcf-utils/package.json
  packages/gcf-utils/src/gcf-utils.ts
Labels: cla: yes

#1352 build(owl-bot): update gcf-utils with probot 11
  packages/owl-bot/package-lock.json
  packages/owl-bot/package.json
Labels: cla: yes

#1353 build(owl-bot): add deployment config
  packages/owl-bot/cloudbuild.yaml
Labels: cla: yes

#1354 build(owl-bot): no prepare
  packages/owl-bot/package.json
Labels: cla: yes

#1350 chore: move OwlBotLock into config-files.ts
  packages/owl-bot/src/config-files.ts
  packages/owl-bot/src/core.ts
Labels: cla: yes

#1356 fix: confirm that bazel can fetch remote build dependencies
  packages/bazel-bot/docker-image/generate-googleapis-gen.sh
  packages/bazel-bot/test-generate-googleapis-gen.sh
Labels: cla: yes

#1360 chore: use repo metadata to populate nodejs CODEOWNERS
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#1361 chore: restore CODEOWNERS and synth ignore
  .github/CODEOWNERS
  synth.py
Labels: cla: yes

#1355 build(owl-bot): main should be the entrypoint for the cloud function
  packages/owl-bot/package.json
Labels: cla: yes

#1362 chore: add org to allowlist
  packages/merge-on-green/src/merge-on-green.ts
Labels: cla: yes

#1364 build: update environment variables rather than replacing
  scripts/publish-function.sh
Labels: cla: yes

#1358 fix(auto-label): second attempt upgrading to Probot 11
  packages/auto-label/package-lock.json
  packages/auto-label/package.json
  packages/auto-label/src/auto-label.ts
  packages/auto-label/test/auto-label.ts
  packages/auto-label/test/language-path-tests.ts
Labels: cla: yes

#1363 chore: define format for .OwlBot.yaml file
  packages/owl-bot/package-lock.json
  packages/owl-bot/package.json
  packages/owl-bot/src/config-files.ts
  packages/owl-bot/src/owl-bot-yaml-schema.json
  packages/owl-bot/test/config-files.ts
  packages/owl-bot/tsconfig.json
Labels: cla: yes

#1365 fix: update secret values for old bots
  packages/gcf-utils/package-lock.json
  packages/gcf-utils/package.json
  packages/gcf-utils/src/gcf-utils.ts
Labels: cla: yes

#1371 fix(gcf-utils): release as appropriate version
  packages/gcf-utils/package.json
Labels: cla: yes

#1373 deps: update release-please to 10.1.0-candidate.0
  packages/release-please/package-lock.json
  packages/release-please/package.json
  packages/release-please/src/release-please.ts
  packages/release-please/src/runner.ts
Labels: cla: yes

#1397 feat: add logic to open pull request with updated .OwlBot.lock.yaml
  packages/owl-bot/package-lock.json
  packages/owl-bot/package.json
  packages/owl-bot/src/bin/commands/open-pr.ts
  packages/owl-bot/src/bin/owl-bot.ts
  packages/owl-bot/src/core.ts
  packages/owl-bot/src/database.ts
  packages/owl-bot/src/handlers.ts
  packages/owl-bot/src/owl-bot.ts
  packages/owl-bot/test/handlers.ts
Labels: cla: yes

#1398 feat(redirect): add redirect for container subscription
  serverless-scheduler-proxy/main.go
Labels: cla: yes

#1396 feat: implement ConfigsStore with firestore
  packages/owl-bot/package.json
  packages/owl-bot/src/bin/commands/open-pr.ts
  packages/owl-bot/src/configs-store.ts
  packages/owl-bot/src/database.ts
  packages/owl-bot/src/handlers.ts
  packages/owl-bot/test/database.ts
  packages/owl-bot/test/handlers.ts
Labels: cla: yes

#1401 feat: initialize the database in the app init code
  packages/owl-bot/src/owl-bot.ts
  packages/owl-bot/test/owl-bot.ts
Labels: cla: yes

#1403 feat(owl-bot): update .owl-bot.lock on updated container
  packages/owl-bot/src/handlers.ts
  packages/owl-bot/src/owl-bot.ts
Labels: cla: yes

#1404 fix: escape all the special characters in firestore ids
  packages/owl-bot/src/database.ts
  packages/owl-bot/test/database.ts
Labels: cla: yes

#1405 debug(owl-bot): add logging to make debugging easier
  packages/owl-bot/src/bin/commands/open-pr.ts
  packages/owl-bot/src/handlers.ts
  packages/owl-bot/src/owl-bot.ts
  packages/owl-bot/test/handlers.ts
  packages/owl-bot/test/owl-bot.ts
Labels: cla: yes

#1406 debug(owl-bot): debug build of owl-bot
  packages/owl-bot/package-lock.json
  packages/owl-bot/package.json
Labels: cla: yes

#1375 fix(conventional-commit-lint): second attempt to upgrade to Probot 11
  packages/conventional-commit-lint/package-lock.json
  packages/conventional-commit-lint/package.json
  packages/conventional-commit-lint/src/conventional-commit-lint.ts
  packages/conventional-commit-lint/test/conventional-commit-lint.ts
Labels: cla: yes

#1376 fix(do-not-merge): second attempt to upgrade to Probot 11
  packages/do-not-merge/package-lock.json
  packages/do-not-merge/package.json
  packages/do-not-merge/src/do-not-merge.ts
  packages/do-not-merge/test/test.ts
Labels: cla: yes

#1388 fix(trusted-contribution): upgrade to probot 11
  packages/trusted-contribution/package-lock.json
  packages/trusted-contribution/package.json
  packages/trusted-contribution/src/trusted-contribution.ts
  packages/trusted-contribution/test/trusted-contribution.ts
Labels: cla: yes

#1382 fix(merge-on-green): upgrade MOG to Probot 11
  packages/merge-on-green/package-lock.json
  packages/merge-on-green/package.json
  packages/merge-on-green/src/merge-logic.ts
  packages/merge-on-green/src/merge-on-green.ts
  packages/merge-on-green/test/merge-logic.ts
  packages/merge-on-green/test/merge-on-green.ts
Labels: cla: yes

#1381 fix(label-sync): upgrade label-sync to Probot 11
  packages/label-sync/package-lock.json
  packages/label-sync/package.json
  packages/label-sync/src/label-sync.ts
  packages/label-sync/test/test.ts
Labels: automerge, cla: yes

#1380 fix(header-checker-lint): upgrade to Probot 11
  packages/header-checker-lint/package-lock.json
  packages/header-checker-lint/package.json
  packages/header-checker-lint/src/header-checker-lint.ts
  packages/header-checker-lint/test/header-checker-lint.ts
Labels: cla: yes

#1374 fix(blunderbuss): second attempt to upgrade blunderbuss to probot 11
  packages/blunderbuss/package-lock.json
  packages/blunderbuss/package.json
  packages/blunderbuss/src/blunderbuss.ts
  packages/blunderbuss/test/blunderbuss.ts
Labels: cla: yes

#1387 fix(sync-repo-settings): upgrade to Probot 11
  packages/sync-repo-settings/package-lock.json
  packages/sync-repo-settings/package.json
  packages/sync-repo-settings/src/sync-repo-settings.ts
  packages/sync-repo-settings/test/test.ts
Labels: cla: yes

#1389 fix(slo-stat-bot): upgrade to Probot 11
  packages/slo-stat-bot/package-lock.json
  packages/slo-stat-bot/package.json
  packages/slo-stat-bot/src/slo-bot.ts
  packages/slo-stat-bot/src/slo-compliant.ts
  packages/slo-stat-bot/src/slo-lint.ts
  packages/slo-stat-bot/test/slo-bot.ts
  packages/slo-stat-bot/test/slo-label.ts
  packages/slo-stat-bot/test/slo-lint.ts
Labels: cla: yes

#1413 fix(owl-bot): fix two timing related bugs
  packages/gcf-utils/src/gcf-utils.ts
  packages/owl-bot/src/handlers.ts
  packages/owl-bot/test/owl-bot.ts
Labels: cla: yes

#1402 fix(snippet-bot): distinguish region tags with commit hash
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/src/snippets.ts
  packages/snippet-bot/src/utils.ts
  packages/snippet-bot/src/violations.ts
  packages/snippet-bot/test/fixtures/snippets-frozen.json
  packages/snippet-bot/test/fixtures/violations-test-snippets.json
  packages/snippet-bot/test/snippet-bot.ts
  packages/snippet-bot/test/utils.ts
  packages/snippet-bot/test/violations.ts
Labels: cla: yes

#1416 fix(owl-bot): gcf-utils with added await
  packages/owl-bot/package-lock.json
  packages/owl-bot/package.json
Labels: cla: yes

#1409 feat: functions to refresh configstore from github
  packages/owl-bot/src/config-files.ts
  packages/owl-bot/src/core.ts
  packages/owl-bot/src/handlers.ts
  packages/owl-bot/src/owl-bot-yaml-schema.json
  packages/owl-bot/test/handlers.ts
Labels: cla: yes

#1418 deps: update release-please to 11.0.0-candidate.0
  packages/release-please/package-lock.json
  packages/release-please/package.json
  packages/release-please/src/release-please.ts
  packages/release-please/test/release-please.ts
Labels: automerge, cla: yes

#1412 feat(dnm): support alternative do-not-merge label
  packages/do-not-merge/README.md
  packages/do-not-merge/__snapshots__/test.js
  packages/do-not-merge/src/do-not-merge.ts
  packages/do-not-merge/test/test.ts
Labels: automerge, cla: yes

#1419 chore(snippet-bot): small wording changes
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/src/snippet-bot.ts
Labels: automerge, cla: yes

#1417 refactor: require an installationId for scanGithubForConfigs()
  packages/owl-bot/src/handlers.ts
  packages/owl-bot/test/handlers.ts
Labels: cla: yes

#1415 fix: specify a locale in docker image
  packages/bazel-bot/docker-image/Dockerfile
Labels: cla: yes

#1421 build: fix interrogate.js for the monitoring-system
  .github/workflows/interrogate.js
Labels: cla: yes

#1420 fix(generate-bot): update generated code to compile
  packages/generate-bot/templates/package.json
  packages/generate-bot/templates/src/{{programName}}.ts
  packages/generate-bot/templates/test/test.ts
Labels: automerge, cla: yes

#1426 build: stop deploying data-processor
  packages/monitoring-system/data-processor/cloudbuild.yaml
  packages/monitoring-system/data-processor/test/unit/data-processors/github-data-processor.spec.ts
Labels: cla: yes

#1383 fix(release-please): upgrade release-please to Probot
  packages/release-please/package-lock.json
  packages/release-please/package.json
  packages/release-please/src/release-please.ts
  packages/release-please/test/release-please.ts
Labels: cla: yes

#1430 deps: rebump release-please to 11.0.0-candidate.0
  packages/release-please/package.json
Labels: automerge, cla: yes

#1377 fix(failurechecker): second attempt to upgrade to Probot 11
  packages/failurechecker/package-lock.json
  packages/failurechecker/package.json
  packages/failurechecker/src/failurechecker.ts
  packages/failurechecker/test/failurechecker.ts
Labels: cla: yes

#1378 fix(flakybot): second attempt upgrading to Probot 11
  packages/flakybot/package-lock.json
  packages/flakybot/package.json
  packages/flakybot/src/flakybot.ts
  packages/flakybot/src/main.ts
Labels: cla: yes

#1379 fix(generated-files-bot): second attempt to upgrade bot to Probot 11
  packages/generated-files-bot/package-lock.json
  packages/generated-files-bot/package.json
  packages/generated-files-bot/src/generated-files-bot.ts
  packages/generated-files-bot/test/generated-files-bot.ts
Labels: cla: yes

#1438 fix(owlbot): use branch from config
  packages/owl-bot/src/handlers.ts
  packages/owl-bot/test/handlers.ts
Labels: cla: yes

#1428 chore(snippet-bot): upgrade snippet-bot to Probot11
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/package.json
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/test/snippet-bot.ts
Labels: cla: yes

#1437 feat(owlbot): add command line helper for validation
  packages/owl-bot/src/bin/commands/validate.ts
  packages/owl-bot/src/bin/owl-bot.ts
  packages/owl-bot/src/handlers.ts
Labels: cla: yes

#1440 fix(owlbot): switch to timestamp from ISO date
  packages/owl-bot/src/handlers.ts
Labels: cla: yes

#1441 fix(sync-repo-settings): upgrade to latest release of @octokit/openapi-types
  packages/sync-repo-settings/package-lock.json
  packages/sync-repo-settings/package.json
  packages/sync-repo-settings/src/sync-repo-settings.ts
Labels: cla: yes

#1442 fix(release-please): pin the version of release-please
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: cla: yes

#1443 build(data-processor): use v1 lock file format
  packages/monitoring-system/data-processor/package-lock.json
Labels: cla: yes

#1446 fix(snippet-bot): add a sentence indicating the end of violations
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/src/snippet-bot.ts
Labels: cla: yes

#1435 feat: database functions for PRs triggered by changes to googleapis-gen
  packages/owl-bot/package-lock.json
  packages/owl-bot/package.json
  packages/owl-bot/src/config-files.ts
  packages/owl-bot/src/configs-store.ts
  packages/owl-bot/src/copy-tasks-store.ts
  packages/owl-bot/src/database.ts
  packages/owl-bot/src/owl-bot-yaml-schema.json
  packages/owl-bot/test/database.ts
  packages/owl-bot/test/handlers.ts
Labels: cla: yes

#1392 build: add a linkinator step
  .github/workflows/ci.yaml
  README.md
  packages/blunderbuss/CHANGELOG.md
  packages/blunderbuss/README.md
  packages/conventional-commit-lint/CHANGELOG.md
  packages/conventional-commit-lint/README.md
  packages/failurechecker/CHANGELOG.md
  packages/flakybot/CHANGELOG.md
  packages/gcf-utils/CHANGELOG.md
  packages/gcf-utils/README.md
  packages/generate-bot/CHANGELOG.md
  packages/header-checker-lint/CHANGELOG.md
  packages/label-sync/CHANGELOG.md
  packages/label-sync/README.md
  packages/merge-on-green/CHANGELOG.md
  packages/monitoring-system/README.md
  packages/release-please/CHANGELOG.md
  packages/release-please/README.md
  packages/trusted-contribution/CHANGELOG.md
  packages/trusted-contribution/README.md
Labels: cla: yes

#1432 feat(m-o-g): use base branch for branch protection
  packages/merge-on-green/src/merge-logic.ts
  packages/merge-on-green/src/merge-on-green.ts
  packages/merge-on-green/test/Fixtures/events/pull_request_labeled.json
  packages/merge-on-green/test/Fixtures/events/pull_request_opened.json
  packages/merge-on-green/test/merge-on-green.ts
Labels: cla: yes

#1457 fix: typescript 4.2 error
  packages/monitoring-system/data-processor/src/data-processors/data-processor-abstract.ts
Labels: cla: yes

#1456 feat: implement CopyTasksStore.filterMissingCopyTasks()
  packages/owl-bot/src/copy-tasks-store.ts
  packages/owl-bot/src/database.ts
  packages/owl-bot/test/database.ts
Labels: cla: yes
