Repository googleapis/repo-automation-bots, pull requests merged in 2022-09, with the labels that each got.

#4301 deps(gcf-utils, cron-utils): update dependencies
  packages/cron-utils/package-lock.json
  packages/cron-utils/package.json
  packages/gcf-utils/package-lock.json
  packages/gcf-utils/package.json
Labels: size: xl

#4303 build: improve weekly dependency update
  .github/workflows/deps.yaml
  .github/workflows/list-node-path-for-deps.js
  packages/cron-utils/.ncurc.yaml
  packages/gcf-utils/.ncurc.yaml
  packages/policy/.ncurc.yaml
  packages/secret-rotator/.ncurc.yaml
Labels: size: m

#4304 deps(secret-rotator): update dependencies
  packages/secret-rotator/package-lock.json
  packages/secret-rotator/package.json
Labels: size: xl

#4305 feat(release-please): enable sentence-case for googleapis
  packages/release-please/src/release-please.ts
Labels: size: xs

#4306 fix(snippet-bot): use git-file-utils for fetching files
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/package.json
  packages/snippet-bot/src/region-tag-parser.ts
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/test/region-tag-parser.ts
  packages/snippet-bot/test/snippet-bot.ts
Labels: size: l

#4350 fix(release-please): release-please with fix for sentence-case
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: size: s

#4353 chore: update renovate config
  renovate.json
Labels: size: s

#4312 fix: fixes a broken deps workflow
  .github/workflows/list-node-paths-for-deps.js
Labels: size: u

#4360 deps: security updates for owlbot-bootstrapper
  packages/owlbot-bootstrapper/app/package-lock.json
  packages/owlbot-bootstrapper/app/package.json
  packages/owlbot-bootstrapper/cli/package-lock.json
  packages/owlbot-bootstrapper/cli/package.json
  packages/owlbot-bootstrapper/common-container/package-lock.json
  packages/owlbot-bootstrapper/common-container/package.json
Labels: size: xl

#4363 chore: add directory name to renovate PR title
  renovate.json
Labels: size: xs

#4354 deps: update release-please to 14.5.0
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: size: s

#4356 fix: conventional commit for JavaApiaryCodegen
  packages/auto-approve/src/process-checks/java/apiary-codegen.ts
  packages/auto-approve/test/java-apiary-codegen.test.ts
Labels: size: xs

#4367 fix: pass context logger to release-please when using fromConfig
  packages/release-please/src/release-please.ts
Labels: size: xs

#4368 feat(mono-repo-publish): add --exclude-files option
  packages/mono-repo-publish/package-lock.json
  packages/mono-repo-publish/package.json
  packages/mono-repo-publish/src/bin/mono-repo-publish.ts
  packages/mono-repo-publish/src/main.ts
  packages/mono-repo-publish/test/cli.ts
  packages/mono-repo-publish/test/main.test.ts
Labels: size: l

#4357 feat(cherry-pick-bot): add support for preserving original PR title
  packages/cherry-pick-bot/README.md
  packages/cherry-pick-bot/__snapshots__/bot.js
  packages/cherry-pick-bot/__snapshots__/cherry-pick.js
  packages/cherry-pick-bot/src/bot.ts
  packages/cherry-pick-bot/src/cherry-pick.ts
  packages/cherry-pick-bot/src/config-schema.json
  packages/cherry-pick-bot/test/bot.ts
  packages/cherry-pick-bot/test/cherry-pick.ts
  packages/cherry-pick-bot/test/fixtures/config/broken-config.yml
  packages/cherry-pick-bot/test/fixtures/config/valid-config.yml
  packages/cherry-pick-bot/test/fixtures/data/pull_request_files_config_added.json
  packages/cherry-pick-bot/test/fixtures/events/pull_request_opened.json
  packages/cherry-pick-bot/tsconfig.json
Labels: size: l

#4382 feat(gcf-utils): switch to @google-cloud/run
  packages/gcf-utils/package-lock.json
  packages/gcf-utils/package.json
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/gcf-bootstrapper.ts
Labels: size: l

#4383 feat(cron-utils): switch to @google-cloud/run
  packages/cron-utils/package-lock.json
  packages/cron-utils/package.json
  packages/cron-utils/src/cron-utils.ts
  packages/cron-utils/test/cron-utils.ts
Labels: size: l

#4385 fix: look at all comments on merged pull request
  packages/cherry-pick-bot/src/bot.ts
  packages/cherry-pick-bot/test/bot.ts
  packages/cherry-pick-bot/test/fixtures/data/issue_comments_non_cherry_pick.json
Labels: size: m

#4386 deps(canary-bot): update gcf-utils to 14.1.0
  packages/canary-bot/package-lock.json
  packages/canary-bot/package.json
Labels: size: l

#4391 build(auto-label): deploy Cloud Run frontend
  packages/auto-label/Dockerfile
  packages/auto-label/cloudbuild.yaml
  packages/auto-label/package-lock.json
  packages/auto-label/package.json
  packages/auto-label/src/server.ts
Labels: size: l

#4392 build(blunderbuss): deploy Cloud Run frontend
  packages/blunderbuss/Dockerfile
  packages/blunderbuss/cloudbuild.yaml
  packages/blunderbuss/package-lock.json
  packages/blunderbuss/package.json
  packages/blunderbuss/src/server.ts
Labels: size: m

#4395 refactor(policy): switch meow to yargs
  packages/policy/package-lock.json
  packages/policy/package.json
  packages/policy/src/cli.ts
  packages/policy/test/test.cli.ts
Labels: size: l

#4394 build(ccl): deploy Cloud Run frontend
  packages/conventional-commit-lint/Dockerfile
  packages/conventional-commit-lint/cloudbuild.yaml
  packages/conventional-commit-lint/package-lock.json
  packages/conventional-commit-lint/package.json
  packages/conventional-commit-lint/src/server.ts
Labels: size: l

#4396 build(failurechecker): deploy Cloud Run frontend
  packages/failurechecker/Dockerfile
  packages/failurechecker/cloudbuild.yaml
  packages/failurechecker/package-lock.json
  packages/failurechecker/package.json
  packages/failurechecker/src/server.ts
Labels: size: l

#4397 build(flakybot): deploy Cloud Run frontend
  packages/flakybot/Dockerfile
  packages/flakybot/cloudbuild.yaml
  packages/flakybot/package-lock.json
  packages/flakybot/package.json
  packages/flakybot/src/server.ts
Labels: size: l

#4398 build(generated-files-bot): deploy Cloud Run frontend
  packages/generated-files-bot/Dockerfile
  packages/generated-files-bot/cloudbuild.yaml
  packages/generated-files-bot/package-lock.json
  packages/generated-files-bot/package.json
  packages/generated-files-bot/src/server.ts
Labels: size: l

#4399 build(header-checker-lint): deploy Cloud Run frontend
  packages/header-checker-lint/Dockerfile
  packages/header-checker-lint/cloudbuild.yaml
  packages/header-checker-lint/package-lock.json
  packages/header-checker-lint/package.json
  packages/header-checker-lint/src/server.ts
Labels: size: l

#4400 build(mog): deploy Cloud Run frontend
  packages/merge-on-green/Dockerfile
  packages/merge-on-green/cloudbuild.yaml
  packages/merge-on-green/package-lock.json
  packages/merge-on-green/package.json
  packages/merge-on-green/src/server.ts
Labels: size: l

#4401 build(label-sync): deploy Cloud Run frontend
  packages/label-sync/Dockerfile
  packages/label-sync/cloudbuild.yaml
  packages/label-sync/package-lock.json
  packages/label-sync/package.json
  packages/label-sync/src/server.ts
Labels: size: l

#4402 build(policy): deploy Cloud Run frontend
  packages/policy/Dockerfile
  packages/policy/cloudbuild.yaml
  packages/policy/package-lock.json
  packages/policy/package.json
  packages/policy/src/server.ts
Labels: size: xl

#4403 build(repo-metadata-lint): deploy Cloud Run frontend
  packages/repo-metadata-lint/Dockerfile
  packages/repo-metadata-lint/cloudbuild.yaml
  packages/repo-metadata-lint/package-lock.json
  packages/repo-metadata-lint/package.json
  packages/repo-metadata-lint/src/server.ts
Labels: size: l

#4404 build(sync-repo-settings): deploy Cloud Run frontend
  packages/sync-repo-settings/Dockerfile
  packages/sync-repo-settings/cloudbuild.yaml
  packages/sync-repo-settings/package-lock.json
  packages/sync-repo-settings/package.json
  packages/sync-repo-settings/src/server.ts
Labels: size: l

#4405 build(trusted-contribution): deploy Cloud Run frontend
  packages/trusted-contribution/Dockerfile
  packages/trusted-contribution/cloudbuild.yaml
  packages/trusted-contribution/package-lock.json
  packages/trusted-contribution/package.json
  packages/trusted-contribution/src/server.ts
Labels: size: l

#4415 deps(owl-bot): dependency updates
  packages/owl-bot/package-lock.json
  packages/owl-bot/package.json
Labels: size: l

#4413 feat: make Cloud Task queue rate configurable
  packages/snippet-bot/cloudbuild.yaml
  scripts/publish-cloud-run.sh
  scripts/publish-function.sh
Labels: size: s

#4422 chore: add parent directory to lock file update PRs
  renovate.json
Labels: size: xs

#4425 build: confiure task queue rate
  packages/auto-approve/cloudbuild.yaml
  packages/auto-label/cloudbuild.yaml
  packages/blunderbuss/cloudbuild.yaml
  packages/do-not-merge/cloudbuild.yaml
Labels: size: s

#4431 build: fix auto-label config
  .github/auto-label.yaml
  .github/auto-label.yml
  owlbot.py
Labels: size: m

#4430 fix: catch and log warning if issues disabled on repository
  packages/repo-metadata-lint/src/repo-metadata-lint.ts
  packages/repo-metadata-lint/test/repo-metadata-lint.ts
Labels: bot: repo-metadata-lint, size: s

#4432 feat: add closeIssue helper
  packages/issue-utils/src/issue-utils.ts
  packages/issue-utils/test/issue-utils.ts
Labels: size: m

#4414 fix(owlbot-bootstrapper): drop support for split repo
  packages/owlbot-bootstrapper/app/owlbot-bootstrapper.ts
  packages/owlbot-bootstrapper/cli/cloudbuild-owlbot-bootstrapper.yaml
  packages/owlbot-bootstrapper/common-container/__snapshots__/utils.test.js
  packages/owlbot-bootstrapper/common-container/post-process.ts
  packages/owlbot-bootstrapper/common-container/pre-process.ts
  packages/owlbot-bootstrapper/common-container/split-repo.ts
  packages/owlbot-bootstrapper/common-container/test/post-process.test.ts
  packages/owlbot-bootstrapper/common-container/test/pre-process.test.ts
  packages/owlbot-bootstrapper/common-container/test/split-repo.test.ts
  packages/owlbot-bootstrapper/common-container/test/utils.test.ts
  packages/owlbot-bootstrapper/common-container/utils.ts
Labels: size: xs

#4436 build: use uploader/releasetool from Docker image
  .kokoro/publish.sh
  .kokoro/release/docs.sh
Labels: automerge

#4435 feat(failurechecker): close failure issue if resolved
  packages/failurechecker/package-lock.json
  packages/failurechecker/package.json
  packages/failurechecker/src/failurechecker.ts
  packages/failurechecker/test/failurechecker.ts
Labels: bot: failurechecker

#4437 build(flakybot): set a lower Cloud Task rate
  packages/flakybot/cloudbuild.yaml
Labels: bot: flakybot

#4441 chore: testing the new gcf-utils with canary
  packages/canary-bot/package-lock.json
  packages/canary-bot/package.json
  packages/canary-bot/src/canary-bot.ts
  packages/canary-bot/test/fixtures/events/issue_opened_testing_error.json
  packages/canary-bot/test/test.ts
Labels: bot: canary

#4451 deps(snippet-bot): update gcf-utils to V14.2.0
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/package.json
Labels: bot: snippet-bot, automerge

#4468 deps(sync-repo-settings): update gcf-utils to V14.2.0
  packages/sync-repo-settings/package-lock.json
  packages/sync-repo-settings/package.json
Labels: bot: sync-repo-settings

#4467 deps(cherry-pick-bot): update gcf-utils to V14.2.0
  packages/cherry-pick-bot/package-lock.json
  packages/cherry-pick-bot/package.json
Labels: bot: cherry-pick

#4465 deps(release-trigger): update gcf-utils to V14.2.0
  packages/release-trigger/package-lock.json
  packages/release-trigger/package.json
Labels: bot: release-trigger

#4464 deps(flakybot): update gcf-utils to V14.2.0
  packages/flakybot/package-lock.json
  packages/flakybot/package.json
Labels: bot: flakybot

#4461 deps(repo-metadata-lint): update gcf-utils to V14.2.0
  packages/repo-metadata-lint/package-lock.json
  packages/repo-metadata-lint/package.json
Labels: bot: repo-metadata-lint

#4460 deps(policy): update gcf-utils to V14.2.0
  packages/policy/package-lock.json
  packages/policy/package.json
Labels: bot: policy

#4463 deps(header-checker-lint): update gcf-utils to V14.2.0
  packages/header-checker-lint/package-lock.json
  packages/header-checker-lint/package.json
Labels: bot: license header

#4459 deps(label-sync): update gcf-utils to V14.2.0
  packages/label-sync/package-lock.json
  packages/label-sync/package.json
Labels: bot: label-sync

#4457 deps(blunderbuss): update gcf-utils to V14.2.0
  packages/blunderbuss/package-lock.json
  packages/blunderbuss/package.json
Labels: bot: blunderbuss

#4456 deps(conventional-commit-lint): update gcf-utils to V14.2.0
  packages/conventional-commit-lint/package-lock.json
  packages/conventional-commit-lint/package.json
Labels: bot: conventional-commit-lint

#4455 deps(failurechecker): update gcf-utils to V14.2.0
  packages/failurechecker/package-lock.json
  packages/failurechecker/package.json
Labels: bot: failurechecker

#4454 deps(auto-label): update gcf-utils to V14.2.0
  packages/auto-label/package-lock.json
  packages/auto-label/package.json
Labels: bot: auto label

#4452 deps(generated-files-bot): update gcf-utils to V14.2.0
  packages/generated-files-bot/package-lock.json
  packages/generated-files-bot/package.json
Labels: bot: generated-files-bot

#4462 deps(merge-on-green): update gcf-utils to V14.2.0
  packages/merge-on-green/package-lock.json
  packages/merge-on-green/package.json
Labels: bot: merge on green

#4458 deps(secret-rotator): update gcf-utils to V14.2.0
  packages/secret-rotator/package-lock.json
  packages/secret-rotator/package.json
Labels: bot: secret-rotator

#4453 deps(release-please): update gcf-utils to V14.2.0
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: bot: release please

#4449 deps(owl-bot): update gcf-utils to V14.2.0
  packages/owl-bot/package-lock.json
  packages/owl-bot/package.json
Labels: bot: owl-bot

#4447 deps(auto-approve): update gcf-utils to v14.2.0
  packages/auto-approve/package-lock.json
  packages/auto-approve/package.json
Labels: bot: auto approve

#4450 deps(do-not-merge): update gcf-utils to V14.2.0
  packages/do-not-merge/package-lock.json
  packages/do-not-merge/package.json
Labels: automerge

#4471 build(release-please): increase backend memory
  packages/release-please/cloudbuild.yaml
Labels: bot: release please

#4427 deps: update release-please to 14.7.0
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: size: s

#4489 deps(canary-bot): update gcf-utils to V14.2.1
  packages/canary-bot/package-lock.json
  packages/canary-bot/package.json
Labels: bot: canary

#4490 deps(release-trigger): update gcf-utils to V14.2.1
  packages/release-trigger/package-lock.json
  packages/release-trigger/package.json
Labels: bot: release-trigger

#4494 deps: update release-please to 14.7.1
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: bot: release please

#4426 feat: add NESTED_COMMIT markers when combining multiple source commits
  packages/owl-bot/package.json
  packages/owl-bot/src/bin/commands/copy-code-and-create-pull-request.ts
  packages/owl-bot/src/copy-code.ts
  packages/owl-bot/src/create-pr.ts
  packages/owl-bot/src/scan-googleapis-gen-and-create-pull-requests.ts
  packages/owl-bot/test/create-pr.ts
  packages/owl-bot/test/scan-googleapis-gen-and-create-pull-requests.ts
Labels: size: l

#4497 fix(m-o-g): remove github.com links, convert to togithub.com
  packages/merge-on-green/src/merge-logic.ts
  packages/merge-on-green/test/merge-logic.ts
Labels: bot: merge on green
