Repository googleapis/repo-automation-bots, pull requests merged in 2022-04, with the labels that each got.

#3383 build(owl-bot): route traffic to the cloud run backend
  packages/owl-bot/src/server-frontend.ts
Labels: size: xs

#3384 Revert "build(owl-bot): route traffic to the cloud run backend (#3383)"
  packages/owl-bot/src/server-frontend.ts
Labels: size: xs

#3387 build(owl-bot): route tasks to Cloud Run backend
  packages/owl-bot/src/server-frontend.ts
Labels: size: xs

#3388 Revert "build(owl-bot): route tasks to Cloud Run backend"
  packages/owl-bot/src/server-frontend.ts
Labels: size: xs

#3392 build(owl-bot): temporarily disable signature verification
  packages/owl-bot/src/server-backend.ts
Labels: size: xs

#3396 build(owl-bot): use owl-bot service account for the backend
  packages/owl-bot/cloudbuild.yaml
Labels: size: xs

#3393 Revert "build(owl-bot): temporarily disable signature verification"
  packages/owl-bot/src/server-backend.ts
Labels: size: xs

#3404 debug(owl-bot): log build error
  packages/owl-bot/src/core.ts
Labels: size: xs

#3403 fix(label-sync): label colors should not include #
  packages/label-sync/src/labels.json
Labels: size: xs

#3397 build(owl-bot): install git to the backend container
  packages/owl-bot/Dockerfile.backend
Labels: automerge, size: xs

#3412 chore(owl-bot): change the routing to Cloud Run backend
  packages/owl-bot/src/server-frontend.ts
Labels: size: xs

#3422 deps: update release-please to 13.10.1
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: automerge, size: s

#3423 build(canary): use appropriate service accounts for deployments
  packages/canary-bot/cloudbuild.yaml
Labels: size: xs

#3431 fix: receiving unhandled rejection applying label to java-cloud-bom
  packages/auto-label/src/auto-label.ts
Labels: size: s

#3430 chore(label-sync): stop using Cloud Debugger
  packages/label-sync/package-lock.json
  packages/label-sync/package.json
  packages/label-sync/src/app.ts
Labels: size: m

#3432 build(owl-bot): use dedicated service accounts
  packages/owl-bot/cloudbuild.yaml
Labels: size: xs

#3438 feat: throw typed error
  packages/datastore-lock/src/datastore-lock.ts
Labels: automerge, size: s

#3433 build: use web-backend service account for deployments
  packages/auto-approve/cloudbuild.yaml
  packages/auto-label/cloudbuild.yaml
  packages/blunderbuss/cloudbuild.yaml
  packages/cherry-pick-bot/cloudbuild.yaml
Labels: size: xs

#3437 fix(owlbot): stop crashing on DatastoreLockError
  packages/owl-bot/package-lock.json
  packages/owl-bot/package.json
  packages/owl-bot/src/owl-bot.ts
Labels: size: xl

#3440 deps: update release-please to 13.10.2
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: automerge, size: s

#3445 build: use web-backend service account for bot deployments
  packages/release-please/cloudbuild.yaml
  packages/snippet-bot/cloudbuild.yaml
  packages/sync-repo-settings/cloudbuild.yaml
  packages/trusted-contribution/cloudbuild.yaml
Labels: size: s

#3444 build: use dedicated service accounts
  packages/generated-files-bot/cloudbuild.yaml
  packages/header-checker-lint/cloudbuild.yaml
  packages/merge-on-green/cloudbuild.yaml
  packages/policy/cloudbuild.yaml
Labels: size: xs

#3442 build: use web-backend service account for bots
  packages/conventional-commit-lint/cloudbuild.yaml
  packages/do-not-merge/cloudbuild.yaml
  packages/do-not-merge/package-lock.json
  packages/do-not-merge/package.json
  packages/failurechecker/cloudbuild.yaml
  packages/flakybot/cloudbuild.yaml
  scripts/publish-function.sh
Labels: size: xl

#3463 build(label-sync): use web-backend service account
  packages/label-sync/cloudbuild.yaml
Labels: size: xs

#3467 build: Add `engines` in root `package.json`
  package.json
Labels: size: xs

#3470 Revert "build: sdd srs yaml file (#1419)"
  .github/.OwlBot.lock.yaml
  .github/sync-repo-settings.yaml
Labels: size: s

#3464 fix(owl-bot): initialize Firestore app in an early stage
  packages/owl-bot/src/server-backend.ts
Labels: size: s

#3471 chore: ignore sync-repo-settings from templates
  owlbot.py
Labels: automerge, size: xs

#3472 fix(owl-bot): allow 30 minutes of execution before retry
  packages/gcf-utils/src/gcf-utils.ts
Labels: size: xs

#3479 fix(build): use newer npm for publication
  .kokoro/release/publish.cfg
Labels: size: xs

#3480 feat(monororepo-publish): use npm ci/install from registry
  packages/mono-repo-publish/src/main.js
  packages/mono-repo-publish/test/fixtures/package-lock.json
  packages/mono-repo-publish/test/main.test.js
Labels: size: s

#3482 fix(build): install mono-repo-publish from main registry
  .kokoro/publish.sh
Labels: size: xs

#3483 feat(snippet-bot): check region tag format
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/src/violations.ts
  packages/snippet-bot/test/fixtures/diff-wrong-format.txt
  packages/snippet-bot/test/snippet-bot.ts
  packages/snippet-bot/test/violations.ts
Labels: size: l

#3499 fix: use yargs default instead of coerce
  packages/release-brancher/src/bin/commands/create-pull-request.ts
  packages/release-brancher/test/release-brancher.ts
Labels: automerge, size: xs

#3505 fix: bump bazel-bot timeout to 3 hours
  packages/bazel-bot/cloudbuild.yaml
Labels: automerge, size: xs

#3508 fix(owl-bot): bump scan-googleapis-gen-and-create-pull-requests timeout to 4h
  packages/owl-bot/cloud-build/scan-googleapis-gen-and-create-pull-requests.yaml
Labels: automerge, size: xs

#3509 feat: add timestamps to log statements
  packages/owl-bot/src/cmd.ts
  packages/owl-bot/src/copy-code.ts
  packages/owl-bot/src/create-pr.ts
  packages/owl-bot/src/logger.ts
  packages/owl-bot/src/scan-googleapis-gen-and-create-pull-requests.ts
Labels: size: m

#3510 fix: `git commit` overflowed output buffer
  packages/owl-bot/src/copy-code.ts
Labels: size: s

#3512 fix: accelerate copying code into monorepos
  packages/owl-bot/src/copy-code.ts
Labels: size: m

#3511 build(serverless-scheduler-proxy): use scheduler-proxy service account
  scripts/serverless-scheduler-proxy-deploy.sh
Labels: size: xs

#3516 feat: instantiate new child logger for each request via weakmap cache
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/src/logging/gcf-logger.ts
  packages/gcf-utils/src/logging/trigger-info-builder.ts
  packages/gcf-utils/test/gcf-bootstrapper.ts
Labels: automerge, size: m

#3517 build: create GCB test that ensures the image builds
  serverless-scheduler-proxy/cloudbuild-test.yaml
Labels: automerge, size: s

#3519 fix(serverless-scheduler-proxy): use golang:1.18-alpine
  serverless-scheduler-proxy/Dockerfile
Labels: size: s

#3518 docs: add note about `cloudbuild-test.yaml` configurations
  trigger-sync/README.md
Labels: automerge, size: xs

#3522 fix: update canary-bot to use context logger
  packages/canary-bot/package-lock.json
  packages/canary-bot/package.json
  packages/canary-bot/src/canary-bot.ts
Labels: automerge, size: xl

#3521 fix(header-checker-lint): update gcf-utils to 13.4.0 and use context logger
  packages/header-checker-lint/package-lock.json
  packages/header-checker-lint/package.json
  packages/header-checker-lint/src/header-checker-lint.ts
Labels: automerge, size: s

#3525 fix: remove extra [] trailing every log statement
  packages/owl-bot/src/logger.ts
  packages/owl-bot/test/logger.ts
Labels: automerge, size: m

#3532 deps(canary-bot): update gcf-utils to 13.5.0 for log correlation
  packages/canary-bot/package-lock.json
  packages/canary-bot/package.json
Labels: automerge, size: s

#3533 fix: export GCFLogger class
  packages/gcf-utils/src/gcf-utils.ts
Labels: automerge, size: xs

#3538 fix(blunderbuss): upgrade gcf-utils and use context-logger
  packages/blunderbuss/package-lock.json
  packages/blunderbuss/package.json
  packages/blunderbuss/src/blunderbuss.ts
  packages/blunderbuss/src/utils.ts
  packages/blunderbuss/test/blunderbuss.ts
Labels: automerge, size: xl

#3539 fix(cherry-pick-bot): upgrade gcf-utils and use context-logger
  packages/cherry-pick-bot/package-lock.json
  packages/cherry-pick-bot/package.json
  packages/cherry-pick-bot/src/bot.ts
  packages/cherry-pick-bot/src/branch-protection.ts
  packages/cherry-pick-bot/src/cherry-pick.ts
Labels: automerge, size: xl

#3537 fix: ignore PHP's sharded mirror repos
  packages/owl-bot/src/bin/commands/scan-configs.ts
  packages/owl-bot/src/handlers.ts
  packages/owl-bot/src/owl-bot.ts
  packages/owl-bot/src/should-ignore-repo.ts
  packages/owl-bot/test/handlers.ts
  packages/owl-bot/test/should-ignore-repo.ts
Labels: automerge, size: m

#3541 fix(failurechecker): upgrade gcf-utils and use context-logger
  packages/failurechecker/package-lock.json
  packages/failurechecker/package.json
  packages/failurechecker/src/failurechecker.ts
Labels: automerge, size: xl

#3543 fix(generated-files): upgrade gcf-utils and use context-logger
  packages/generated-files-bot/package-lock.json
  packages/generated-files-bot/package.json
  packages/generated-files-bot/src/generated-files-bot.ts
Labels: automerge, size: xl

#3544 fix(label-sync): upgrade gcf-utils and use context-logger
  packages/label-sync/package-lock.json
  packages/label-sync/package.json
  packages/label-sync/src/label-sync.ts
  packages/label-sync/test/test.ts
Labels: automerge, size: xl

#3542 fix(ccl): upgrade gcf-utils and use context-logger
  packages/conventional-commit-lint/package-lock.json
  packages/conventional-commit-lint/package.json
  packages/conventional-commit-lint/src/conventional-commit-lint.ts
Labels: automerge, size: xl

#3545 fix(mog): upgrade gcf-utils and use context-logger
  packages/merge-on-green/package-lock.json
  packages/merge-on-green/package.json
  packages/merge-on-green/src/merge-logic.ts
  packages/merge-on-green/src/merge-on-green.ts
  packages/merge-on-green/test/merge-on-green.ts
Labels: automerge, size: m

#3546 fix: insert api names into updated pull request titles
  packages/owl-bot/src/copy-code.ts
Labels: automerge, size: s

#3552 fix(snippet-bot): update gcf-utils and use context-logger
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/package.json
  packages/snippet-bot/src/api-labels.ts
  packages/snippet-bot/src/region-tag-parser.ts
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/src/snippets.ts
  packages/snippet-bot/src/violations.ts
  packages/snippet-bot/test/snippet-bot.ts
  packages/snippet-bot/test/violations.ts
Labels: automerge, size: xl

#3547 fix(flakybot): upgrade gcf-utils and use context-logger
  packages/flakybot/package-lock.json
  packages/flakybot/package.json
  packages/flakybot/src/config-schema.json
  packages/flakybot/src/flakybot.ts
Labels: automerge, size: xl
