Repository googleapis/repo-automation-bots, pull requests merged in 2022-05, with the labels that each got.

#3548 fix(policy): update gcf-utils and migrate to context-logger
  packages/policy/package-lock.json
  packages/policy/package.json
  packages/policy/src/bot.ts
Labels: size: xl

#3549 fix(release-please): update gcf-utils and migrate to context-logger
  packages/release-please/package-lock.json
  packages/release-please/package.json
  packages/release-please/src/release-please.ts
Labels: size: xl

#3582 fix: recalculate request bindings for downloaded payloads
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/gcf-bootstrapper.ts
Labels: size: m

#3583 chore(policy): lock file update
  packages/policy/package-lock.json
Labels: size: xl

#3550 fix(release-trigger): update gcf-utils and use context-logger
  packages/release-trigger/package-lock.json
  packages/release-trigger/package.json
  packages/release-trigger/src/bot.ts
Labels: automerge, size: xl

#3586 build: make Cloud Build tests required
  .github/sync-repo-settings.yaml
Labels: automerge, size: xs

#3587 fix: fsevents error and add cloudbuild test
  packages/secret-rotator/Dockerfile
  packages/secret-rotator/cloudbuild-test.yaml
  packages/secret-rotator/package.json
Labels: size: s

#3556 fix(auto-label): update gcf-utils and use context-logger
  packages/auto-label/package-lock.json
  packages/auto-label/package.json
  packages/auto-label/src/auto-label.ts
  packages/auto-label/test/config-compatibility.ts
Labels: size: xl

#3555 fix(auto-approve): update gcf-utils and use context-logger
  packages/auto-approve/package-lock.json
  packages/auto-approve/package.json
  packages/auto-approve/src/auto-approve.ts
  packages/auto-approve/src/check-pr-v2.ts
  packages/auto-approve/src/check-pr.ts
  packages/auto-approve/src/get-pr-info.ts
  packages/auto-approve/test/auto-approve.test.ts
Labels: size: xl

#3551 fix(rml): update gcf-utils and use context-logger
  packages/repo-metadata-lint/package-lock.json
  packages/repo-metadata-lint/package.json
  packages/repo-metadata-lint/src/file-iterator.ts
  packages/repo-metadata-lint/src/issue-opener.ts
  packages/repo-metadata-lint/src/repo-metadata-lint.ts
Labels: size: xl

#3553 fix(srs): update gcf-utils and use context-logger
  packages/sync-repo-settings/package-lock.json
  packages/sync-repo-settings/package.json
  packages/sync-repo-settings/src/bot.ts
Labels: size: xl

#3554 fix(trusted-contribution): update gcf-utils and use context-logger
  packages/trusted-contribution/package-lock.json
  packages/trusted-contribution/package.json
  packages/trusted-contribution/src/trusted-contribution.ts
Labels: size: xl

#3557 fix(owl-bot): update gcf-utils and use context-logger
  packages/owl-bot/package-lock.json
  packages/owl-bot/package.json
  packages/owl-bot/src/owl-bot.ts
Labels: size: xl

#3585 fix(release-please): update gcf-utils to 13.5.2 for context logger
  packages/release-please/package.json
Labels: automerge, size: xs

#3591 fix: update package-lock fsevents dependency
  packages/secret-rotator/package-lock.json
Labels: size: xs

#3590 deps: update gcf-utils to 13.5.2
  packages/blunderbuss/package-lock.json
  packages/blunderbuss/package.json
  packages/bot-config-utils/package-lock.json
  packages/bot-config-utils/package.json
  packages/cherry-pick-bot/package-lock.json
  packages/cherry-pick-bot/package.json
  packages/conventional-commit-lint/package-lock.json
  packages/conventional-commit-lint/package.json
  packages/datastore-lock/package-lock.json
  packages/datastore-lock/package.json
  packages/do-not-merge/package-lock.json
  packages/do-not-merge/package.json
  packages/failurechecker/package-lock.json
  packages/failurechecker/package.json
  packages/flakybot/package-lock.json
  packages/flakybot/package.json
  packages/generated-files-bot/package-lock.json
  packages/generated-files-bot/package.json
  packages/header-checker-lint/package-lock.json
  packages/header-checker-lint/package.json
  packages/label-sync/package-lock.json
  packages/label-sync/package.json
  packages/label-utils/package-lock.json
  packages/label-utils/package.json
  packages/merge-on-green/package-lock.json
  packages/merge-on-green/package.json
  packages/policy/package-lock.json
  packages/policy/package.json
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/package.json
Labels: size: xl

#3592 refactor(test): fix stubbing with sinon sandbox
  packages/merge-on-green/src/merge-on-green.ts
  packages/merge-on-green/test/merge-logic.ts
  packages/merge-on-green/test/merge-on-green.ts
Labels: automerge, size: m

#3594 fix(m-o-g): check completed status and allow neutral conclusion
  packages/merge-on-green/src/merge-logic.ts
  packages/merge-on-green/test/merge-logic.ts
Labels: size: m

#3528 feat: require tagging titles with [autoapprove] for owlbot template changes
  packages/auto-approve/README.md
  packages/auto-approve/src/interfaces.ts
  packages/auto-approve/src/process-checks/owl-bot-template-changes.ts
  packages/auto-approve/test/owlbot-template-changes.test.ts
Labels: size: s

#3593 build: make secret rotator GCB test required
  .github/sync-repo-settings.yaml
Labels: size: xs

#3595 feat(auto-approve): remove codeowners condition from approvals
  packages/auto-approve/__snapshots__/auto-approve.test.js
  packages/auto-approve/package-lock.json
  packages/auto-approve/src/auto-approve.ts
  packages/auto-approve/src/check-config.ts
  packages/auto-approve/test/auto-approve.test.ts
  packages/auto-approve/test/check-config.test.ts
Labels: size: xl

#3603 chore: update blunderbuss.yml
  .github/blunderbuss.yml
Labels: size: s

#3600 fix(snippet-bot): allow capital letters
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/src/violations.ts
  packages/snippet-bot/test/fixtures/diff-wrong-format.txt
  packages/snippet-bot/test/violations.ts
Labels: automerge, size: xl

#3641 build(release-trigger): add minimal docker frontend image
  packages/release-trigger/Dockerfile.frontend
  packages/release-trigger/cloudbuild-test.yaml
  packages/release-trigger/cloudbuild.yaml
  packages/release-trigger/package.json
  packages/release-trigger/src/server-frontend.ts
Labels: automerge, size: m

#3605 build(auto-approve): deploy Cloud Run frontend
  packages/auto-approve/Dockerfile
  packages/auto-approve/cloudbuild.yaml
  packages/auto-approve/package.json
  packages/auto-approve/src/server.ts
Labels: automerge, size: m

#3656 fix(blunderbuss): assign issues to the reporter too
  packages/blunderbuss/__snapshots__/blunderbuss.js
  packages/blunderbuss/src/utils.ts
  packages/blunderbuss/test/blunderbuss.ts
  packages/blunderbuss/test/fixtures/config/valid_only_reporter.yml
Labels: automerge, size: s

#3657 fix: throw InvalidConfigurationFormat error on validation error
  packages/bot-config-utils/src/bot-config-utils.ts
  packages/bot-config-utils/test/bot-config-utils.ts
Labels: automerge, size: s

#3662 deps(release-please): rollback release-please version to 13.15.1
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: size: s

#3658 feat: add configuration for setting changelog host
  packages/release-please/README.md
  packages/release-please/src/config-constants.ts
  packages/release-please/src/release-please.ts
Labels: automerge, size: xs

#3664 deps: update release-please to 13.16.1
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: automerge, size: s

#3668 fix: handling misconfigured manifest repos
  packages/release-please/package-lock.json
  packages/release-please/package.json
  packages/release-please/src/release-please.ts
  packages/release-please/test/release-please.ts
Labels: size: m

#3667 fix: skip schema validation when trying to run release-please
  packages/release-please/package-lock.json
  packages/release-please/package.json
  packages/release-please/src/release-please.ts
Labels: automerge, size: s

#3671 chore(snippet-bot): added an issue number to the TODO comment
  packages/snippet-bot/src/region-tag-parser.ts
Labels: size: xs

#3673 fix: truncate git status --porcelain output
  packages/owl-bot/src/bin/commands/commit-post-processor-update.ts
  packages/owl-bot/src/git-utils.ts
  packages/owl-bot/src/update-lock.ts
  packages/owl-bot/test/git-utils.ts
Labels: automerge, size: m

#3709 Revert "deps: update snippet-bot deps"
  packages/snippet-bot/package-lock.json
Labels: size: l

#3715 deps: update release-please to 13.16.4
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: size: xl

#3669 fix: force label now attempts releases
  packages/release-please/src/release-please.ts
  packages/release-please/test/release-please.ts
Labels: bot: release please, automerge, size: m

#3714 build(canary-bot): migrate to node14
  .github/workflows/ci.yaml
  packages/canary-bot/cloudbuild-test.yaml
  packages/canary-bot/cloudbuild.yaml
  packages/canary-bot/package-lock.json
  packages/canary-bot/package.json
  scripts/build-function.sh
Labels: size: xl

#3713 build(policy,snippet-bot): add test builds
  packages/policy/cloudbuild-test.yaml
  packages/policy/package-lock.json
  packages/snippet-bot/cloudbuild-test.yaml
  packages/snippet-bot/package-lock.json
Labels: size: xl

#3717 build(snippet-bot): update dependencies
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/package.json
Labels: size: m

#3718 build(policy): update dependencies
  packages/policy/package-lock.json
  packages/policy/package.json
Labels: size: m

#3731 fix(deps): update release-please to 13.16.5
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: automerge, size: xs

#3767 style: fix typo in repo-metadata-schema
  packages/repo-metadata-lint/src/repo-metadata-schema.json
Labels: size: xs

#3670 fix: return undefined rather than throwing an error
  packages/auto-approve/src/check-config.ts
  packages/auto-approve/src/process-checks/java/dependency.ts
  packages/auto-approve/src/process-checks/node/dependency.ts
  packages/auto-approve/src/process-checks/node/release.ts
  packages/auto-approve/src/process-checks/python/dependency.ts
  packages/auto-approve/src/utils-for-pr-checking.ts
  packages/auto-approve/test/additional-validation-for-versioning.test.ts
Labels: automerge, size: l

#3772 deps: update release-please to v13.17.0
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: automerge, size: xl

#3781 feat: open issue on repository for ConfigurationErrors
  packages/release-please/src/error-handling.ts
  packages/release-please/src/release-please.ts
  packages/release-please/test/error-handling.ts
  packages/release-please/test/release-please.ts
Labels: automerge, size: l

#3777 fix: release-please should log error when repository has no detected language and no release-type specified
  packages/release-please/src/release-please.ts
  packages/release-please/test/fixtures/push_to_main_no_language.json
  packages/release-please/test/release-please.ts
Labels: size: m

#3783 feat: allow targeting Cloud Run URLs with crons
  packages/cron-utils/src/cli.ts
  packages/cron-utils/src/cron-utils.ts
  scripts/cron-deploy.sh
  scripts/serverless-scheduler-proxy-deploy.sh
  serverless-scheduler-proxy/cloudbuild.yaml
  serverless-scheduler-proxy/main.go
Labels: automerge, size: m

#3770 fix: handle uncaught 404 exception as permission errors
  packages/auto-approve/src/auto-approve.ts
  packages/auto-approve/src/check-pr-v2.ts
  packages/auto-approve/src/check-pr.ts
  packages/auto-approve/src/get-pr-info.ts
  packages/auto-approve/src/process-checks/owl-bot-template-changes.ts
  packages/auto-approve/test/auto-approve.test.ts
  packages/auto-approve/test/check-pr-V2.test.ts
Labels: size: m

#3784 build: fix logging error
  packages/auto-approve/src/process-checks/owl-bot-template-changes.ts
Labels: size: xs

#3790 chore(deps): update package with new header level changes
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: size: s
