Repository googleapis/repo-automation-bots, pull requests merged in 2022-06, with the labels that each got.

#3786 build(canary-bot): target cloud run with cron
  packages/canary-bot/cloudbuild.yaml
  scripts/cron-deploy.sh
  serverless-scheduler-proxy/main.go
Labels: automerge, size: s

#3815 fix(python): remove required check for python 3.6 unit tests
  packages/sync-repo-settings/src/required-checks.json
Labels: size: xs

#3820 build: fix cron scheduler job name
  packages/release-trigger/cron.yaml
Labels: automerge, size: xs

#3823 fix: bot name is underscored, Cloud Run URL is dasherized
  packages/release-trigger/cloudbuild.yaml
  serverless-scheduler-proxy/main.go
Labels: size: xs

#3822 build: canary-bot cloud run has different installation id for googleapis
  packages/canary-bot/cron.yaml
Labels: automerge, size: xs

#3829 build(merge-on-green): update lock file
  packages/merge-on-green/package-lock.json
Labels: size: m

#3818 deps: update release-please to 13.18.0
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: automerge, size: s

#3824 fix: allow configuring max pages of pull requests to fetch and default to 2
  packages/release-trigger/src/release-trigger.ts
Labels: automerge, size: xs

#3865 fix: delay finding pending PRs on release event
  packages/release-trigger/src/bot.ts
  packages/release-trigger/src/release-trigger.ts
  packages/release-trigger/test/bot.ts
Labels: size: s

#3873 build(release-trigger): increase memory, concurrency and minimum instance
  packages/release-trigger/cloudbuild.yaml
Labels: size: s

#3877 fix: handle bad manifest configuration files
  packages/release-please/package-lock.json
  packages/release-please/package.json
  packages/release-please/src/release-please.ts
  packages/release-please/test/release-please.ts
Labels: size: m

#3879 fix: also handle secondary rate limit errors from GitHub API
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/gcf-bootstrapper.ts
Labels: size: s

#3881 feat(gcf-utils): add flow control for scheduling jobs
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/fixtures/many_installations.json
  packages/gcf-utils/test/gcf-bootstrapper.ts
Labels: size: xl

#3883 testing(canary-bot): enable flow control
  packages/canary-bot/package-lock.json
  packages/canary-bot/package.json
Labels: size: m

#3884 deps: update gcf-utils for cron throttling
  packages/release-trigger/package-lock.json
  packages/release-trigger/package.json
Labels: size: m

#3885 feat(gcf-utils): Make the flow control delay configurable
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/gcf-bootstrapper.ts
Labels: size: m

#3887 testing(canary): testing gcf-utils 13.8.0
  packages/canary-bot/package-lock.json
  packages/canary-bot/package.json
Labels: size: s

#3888 deps(release-trigger): use gcf-utils 13.8.0
  packages/release-trigger/package-lock.json
  packages/release-trigger/package.json
Labels: size: s

#3411 fix: remove docs from required checks for nodejs
  packages/sync-repo-settings/package-lock.json
  packages/sync-repo-settings/package.json
  packages/sync-repo-settings/src/required-checks.json
  packages/sync-repo-settings/test/test.bot.ts
Labels: size: l

#3936 fix: trust copy source directory
  packages/owl-bot/src/copy-code.ts
Labels: size: xs

#3942 fix: await an unawaited promise
  packages/blunderbuss/src/blunderbuss.ts
Labels: size: xs

#3945 deps(policy): use gcf-utils 13.8.0
  packages/policy/package-lock.json
  packages/policy/package.json
Labels: size: m

#3943 feat(ccl): create an issue comment for notifying user
  packages/conventional-commit-lint/__snapshots__/conventional-commit-lint.js
  packages/conventional-commit-lint/package-lock.json
  packages/conventional-commit-lint/package.json
  packages/conventional-commit-lint/src/conventional-commit-lint.ts
  packages/conventional-commit-lint/src/utils.ts
  packages/conventional-commit-lint/test/conventional-commit-lint.ts
  packages/conventional-commit-lint/test/fixtures/pr11.json
  packages/conventional-commit-lint/test/fixtures/pr11WithBadMessage.json
  packages/conventional-commit-lint/test/fixtures/pr11WithCorrectMessage.json
  packages/conventional-commit-lint/test/fixtures/pull_request_synchronize_bad_message.json
  packages/conventional-commit-lint/test/fixtures/pull_request_synchronize_valid_message.json
Labels: size: xl

#3933 fix: when logging errors, log all errors contained in an AggregateError
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/src/logging/gcf-logger.ts
  packages/gcf-utils/test/gcf-bootstrapper.ts
Labels: automerge, package: gcf-utils, size: m

#3950 fix(policy): updated package-lock.json and use nodejs14 runtime
  packages/policy/cloudbuild.yaml
  packages/policy/package-lock.json
Labels: size: l

#3947 chore: update blunderbuss config
  .github/blunderbuss.yml
Labels: size: xs

#3956 deps(auto-approve): use gcf-utils 13.8.1
  packages/auto-approve/cloudbuild.yaml
  packages/auto-approve/package-lock.json
  packages/auto-approve/package.json
Labels: size: l

#3957 deps(auto-label): use gcf-utils 13.8.1
  packages/auto-label/cloudbuild.yaml
  packages/auto-label/package-lock.json
  packages/auto-label/package.json
Labels: size: l

#3959 deps(cherry-pick-bot): use gcf-utils 13.8.1
  packages/cherry-pick-bot/package-lock.json
  packages/cherry-pick-bot/package.json
Labels: size: xl

#3960 deps(do-not-merge): use gcf-utils 13.8.1
  packages/do-not-merge/cloudbuild.yaml
  packages/do-not-merge/package-lock.json
  packages/do-not-merge/package.json
Labels: size: xl

#3968 deps(repo-metadata-lint): use gcf-utils 13.8.1
  packages/repo-metadata-lint/cloudbuild.yaml
  packages/repo-metadata-lint/package-lock.json
  packages/repo-metadata-lint/package.json
Labels: automerge, size: xl

#3976 deps(do-not-merge): update package-lock.json
  packages/do-not-merge/package-lock.json
Labels: size: m

#3971 deps(trusted-contribution): use gcf-utils 13.8.1
  packages/trusted-contribution/cloudbuild.yaml
  packages/trusted-contribution/package-lock.json
  packages/trusted-contribution/package.json
Labels: automerge, size: l

#3967 deps(release-please): use gcf-utils 13.8.1
  packages/release-please/cloudbuild.yaml
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: automerge, size: l

#3964 deps(label-sync): use gcf-utils 13.8.1
  packages/label-sync/cloudbuild.yaml
  packages/label-sync/package-lock.json
  packages/label-sync/package.json
Labels: automerge, size: xl

#3966 deps(owl-bot): use gcf-utils 13.8.1
  packages/owl-bot/package-lock.json
  packages/owl-bot/package.json
Labels: automerge, size: xl

#3970 deps(sync-repo-settings): use gcf-utils 13.8.1
  packages/sync-repo-settings/cloudbuild.yaml
  packages/sync-repo-settings/package-lock.json
  packages/sync-repo-settings/package.json
Labels: automerge, size: xl

#3961 deps(failurechecker): use gcf-utils 13.8.1
  packages/failurechecker/cloudbuild.yaml
  packages/failurechecker/package-lock.json
  packages/failurechecker/package.json
Labels: automerge, size: xl

#3962 deps(generated-files-bot): use gcf-utils 13.8.1
  packages/generated-files-bot/cloudbuild.yaml
  packages/generated-files-bot/package-lock.json
  packages/generated-files-bot/package.json
Labels: automerge, size: xl

#3963 deps(header-checker-lint): use gcf-utils 13.8.1
  packages/header-checker-lint/cloudbuild.yaml
  packages/header-checker-lint/package-lock.json
  packages/header-checker-lint/package.json
Labels: automerge, size: xl

#3965 deps(merge-on-green): use gcf-utils 13.8.1
  packages/merge-on-green/cloudbuild.yaml
  packages/merge-on-green/package-lock.json
  packages/merge-on-green/package.json
Labels: automerge, size: l

#3955 fix: don't run post processor on draft PRs
  packages/owl-bot/src/core.ts
  packages/owl-bot/src/owl-bot.ts
  packages/owl-bot/test/owl-bot.ts
Labels: size: m

#3980 deps(mog): update package-lock.json
  packages/merge-on-green/package-lock.json
Labels: size: l

#3944 fix: small tweaks in production to get owlbot-bootstrapper running, pass GH token as env variable, redact GH token from logging
  packages/owlbot-bootstrapper/app/package-lock.json
  packages/owlbot-bootstrapper/cli/cloudbuild-owlbot-bootstrapper.yaml
  packages/owlbot-bootstrapper/cli/package-lock.json
  packages/owlbot-bootstrapper/cli/run-trigger.ts
  packages/owlbot-bootstrapper/cli/test/run-trigger.test.ts
  packages/owlbot-bootstrapper/common-container/Dockerfile
  packages/owlbot-bootstrapper/common-container/__snapshots__/utils.test.js
  packages/owlbot-bootstrapper/common-container/commands/post-process.ts
  packages/owlbot-bootstrapper/common-container/commands/pre-process.ts
  packages/owlbot-bootstrapper/common-container/github-authenticator.ts
  packages/owlbot-bootstrapper/common-container/interfaces.ts
  packages/owlbot-bootstrapper/common-container/mono-repo.ts
  packages/owlbot-bootstrapper/common-container/package-lock.json
  packages/owlbot-bootstrapper/common-container/pre-process.ts
  packages/owlbot-bootstrapper/common-container/test/github-authenticator.test.ts
  packages/owlbot-bootstrapper/common-container/test/mono-repo.test.ts
  packages/owlbot-bootstrapper/common-container/test/post-process.test.ts
  packages/owlbot-bootstrapper/common-container/test/pre-process.test.ts
  packages/owlbot-bootstrapper/common-container/test/utils.test.ts
  packages/owlbot-bootstrapper/common-container/utils.ts
Labels: size: xl

#3981 fix: allow multiple paths to --config-file
  packages/owl-bot/src/bin/commands/copy-code.ts
  packages/owl-bot/src/copy-code.ts
  packages/owl-bot/test/copy-code.ts
Labels: size: s

#3946 fix: examine all repos even when one fails
  packages/owl-bot/src/handlers.ts
Labels: automerge, size: xs

#3934 fix: apps cannot use getAuthenticatedUser endpoint
  packages/release-please/src/error-handling.ts
  packages/release-please/test/error-handling.ts
Labels: bot: release please, automerge, size: s

#3982 fix: there's no "head" command on Windows
  packages/owl-bot/src/bin/commands/commit-post-processor-update.ts
  packages/owl-bot/src/bin/commands/maybe-create-pull-request-for-lock-update.ts
  packages/owl-bot/src/git-utils.ts
  packages/owl-bot/src/update-lock.ts
  packages/owl-bot/test/git-utils.ts
  packages/owl-bot/test/update-lock.ts
Labels: size: m

#4021 chore: update node version for deps updater
  .github/workflows/deps.yaml
Labels: size: xs

#4024 feat(blunderbuss): allow ignoring issues and prs by some authors
  packages/blunderbuss/README.md
  packages/blunderbuss/src/blunderbuss.ts
  packages/blunderbuss/src/config-schema.json
  packages/blunderbuss/src/config.ts
  packages/blunderbuss/test/blunderbuss.ts
  packages/blunderbuss/test/fixtures/config/ignore.yml
Labels: size: m
