Repository googleapis/repo-automation-bots, pull requests merged in 2022-08, with the labels that each got.

#4099 feat: add custom command for running arbitrary publish script
  packages/mono-repo-publish/package-lock.json
  packages/mono-repo-publish/src/bin/mono-repo-publish.ts
  packages/mono-repo-publish/src/main.ts
  packages/mono-repo-publish/test/cli.ts
  packages/mono-repo-publish/test/main.test.ts
Labels: size: l

#4107 Revert "chore: release main (#4100)"
  .release-please-manifest.json
  packages/mono-repo-publish/CHANGELOG.md
  packages/mono-repo-publish/package-lock.json
  packages/mono-repo-publish/package.json
Labels: size: s

#4106 fix: need to compile as part of the prepare step
  packages/mono-repo-publish/package.json
Labels: size: xs

#4104 deps: update release-please to 13.19.7
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: automerge, size: s

#4111 deps: regenerate package-lock.json
  packages/release-please/package-lock.json
Labels: bot: release please, size: xl

#4101 fix: extend post procesor timeout to 80 minutes
  packages/owl-bot/cloud-build/copy-code-again.yaml
  packages/owl-bot/cloud-build/update-pr.yaml
Labels: automerge, size: xs

#4092 refactor: reimplement failurechecker with failure messages
  packages/failurechecker/__snapshots__/failurechecker.js
  packages/failurechecker/package-lock.json
  packages/failurechecker/package.json
  packages/failurechecker/src/failurechecker.ts
  packages/failurechecker/test/failurechecker.ts
Labels: bot: failurechecker, size: l

#4113 docs: fix description of header checker lint bot
  packages/header-checker-lint/package.json
Labels: automerge, size: xs

#4116 feat(bot-config-utils): resolve false on invalid config files
  packages/bot-config-utils/README.md
  packages/bot-config-utils/src/bot-config-utils.ts
  packages/bot-config-utils/test/multi-config-checker.ts
Labels: size: s

#4117 feat(bot-config-utils)!: validateConfigChanges now resolve boolean for valid config
  packages/bot-config-utils/src/bot-config-utils.ts
Labels: size: xs

#4119 fix(bazel-bot): add pipefail option for better logging
  packages/bazel-bot/docker-image/docker-main.sh
Labels: size: xs

#4115 feat(conventional-commit-lint): support configuration file
  packages/conventional-commit-lint/README.md
  packages/conventional-commit-lint/package-lock.json
  packages/conventional-commit-lint/package.json
  packages/conventional-commit-lint/src/conventional-commit-lint.ts
  packages/conventional-commit-lint/src/schema.json
  packages/conventional-commit-lint/test/conventional-commit-lint.ts
  packages/conventional-commit-lint/test/fixtures/config/enabled-false.yaml
  packages/conventional-commit-lint/test/fixtures/config/valid.yaml
  packages/conventional-commit-lint/tsconfig.json
Labels: size: l

#4121 deps: update release-please to 13.20.0
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: size: s

#4130 chore: add release config for git-file-utils
  release-please-config.json
Labels: size: xs

#4135 deps: update release-please to v13.21.0
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: size: xl

#4132 fix(gcf-utils)!: update @octokit/rest to 19
  packages/gcf-utils/package-lock.json
  packages/gcf-utils/package.json
  packages/gcf-utils/src/gcf-utils.ts
  packages/gcf-utils/test/gcf-utils.ts
  packages/gcf-utils/test/logging-octokit-plugin.ts
Labels: size: xl

#4137 deps(canary): use gcf-utils 14.0.0
  packages/canary-bot/package-lock.json
  packages/canary-bot/package.json
  packages/canary-bot/src/canary-bot.ts
  packages/canary-bot/test/test.ts
Labels: size: xl

#4143 deps(bot-config-utils)!: use gcf-utils 14
  packages/bot-config-utils/package-lock.json
  packages/bot-config-utils/package.json
  packages/bot-config-utils/test/bot-config-utils.ts
  packages/datastore-lock/.mocharc.js
  packages/datastore-lock/package-lock.json
  packages/datastore-lock/package.json
  packages/issue-utils/package-lock.json
  packages/issue-utils/package.json
  packages/object-selector/package-lock.json
  packages/object-selector/package.json
Labels: size: xl

#4146 deps(label-utils): use gcf-utils 14
  packages/label-utils/package-lock.json
  packages/label-utils/package.json
Labels: size: xl

#4149 deps: use gcf-utils 14
  packages/auto-approve/package-lock.json
  packages/auto-approve/package.json
  packages/auto-approve/src/auto-approve.ts
  packages/auto-approve/test/auto-approve.test.ts
  packages/auto-label/package-lock.json
  packages/auto-label/package.json
  packages/auto-label/src/auto-label.ts
  packages/auto-label/test/auto-label.ts
  packages/auto-label/test/config-compatibility.ts
  packages/auto-label/test/language-path-tests.ts
Labels: size: xl

#4156 fix(auto-label): throws an Error when installation id is not provided
  packages/auto-label/src/auto-label.ts
Labels: size: s

#4155 deps(blunderbuss): update to gcf-utils 14
  packages/blunderbuss/package-lock.json
  packages/blunderbuss/package.json
  packages/blunderbuss/src/blunderbuss.ts
  packages/blunderbuss/src/utils.ts
  packages/blunderbuss/test/blunderbuss.ts
Labels: size: xl

#4160 build: run release-please app on Cloud Run
  packages/release-please/cloudbuild.yaml
  packages/release-please/src/server.ts
Labels: size: s

#4158 deps(cherry-pick-bot): update to gcf-utils 14
  packages/cherry-pick-bot/package-lock.json
  packages/cherry-pick-bot/package.json
  packages/cherry-pick-bot/src/bot.ts
  packages/cherry-pick-bot/test/bot.ts
  packages/cherry-pick-bot/test/fixtures/events/issue_comment_created.json
  packages/cherry-pick-bot/test/fixtures/events/issue_comment_created_command.json
  packages/cherry-pick-bot/test/fixtures/events/issue_comment_created_non_member.json
  packages/cherry-pick-bot/test/fixtures/events/pull_request_merged.json
Labels: size: xl

#4161 deps(do-not-merge): update to gcf-utils 14
  packages/do-not-merge/package-lock.json
  packages/do-not-merge/package.json
  packages/do-not-merge/src/do-not-merge.ts
  packages/do-not-merge/test/test.ts
Labels: size: xl

#4159 deps(ccl): update to gcf-utils 14
  packages/conventional-commit-lint/package-lock.json
  packages/conventional-commit-lint/package.json
  packages/conventional-commit-lint/src/conventional-commit-lint.ts
  packages/conventional-commit-lint/src/utils.ts
  packages/conventional-commit-lint/test/conventional-commit-lint.ts
Labels: size: xl

#4162 deps(failurechecker): update gcf-utils to v14
  packages/failurechecker/package-lock.json
  packages/failurechecker/package.json
  packages/failurechecker/src/failurechecker.ts
  packages/failurechecker/test/failurechecker.ts
Labels: size: xl

#4164 deps(flakybot): update gcf-utils to v14
  packages/flakybot/flakybot.go
  packages/flakybot/package-lock.json
  packages/flakybot/package.json
  packages/flakybot/src/flakybot.ts
  packages/flakybot/test/flakybot.test.ts
Labels: size: xl

#4165 feat: add findFilesByFilename and findFilesByExtension
  packages/git-file-utils/package-lock.json
  packages/git-file-utils/src/git-file-utils.ts
  packages/git-file-utils/test/find-files.ts
  packages/git-file-utils/test/fixtures/github-data-api/data-api-trees-successful-response-subdir-pkg-recursive.json
  packages/git-file-utils/test/fixtures/github-data-api/data-api-trees-successful-response-subdir-pkg-truncated.json
  packages/git-file-utils/test/fixtures/github-data-api/data-api-trees-successful-response-subdir-subdir1.json
  packages/git-file-utils/test/git-file-utils.ts
Labels: size: xl

#4148 deps: update release-please to v14
  packages/release-please/package-lock.json
  packages/release-please/package.json
  packages/release-please/src/release-please.ts
  packages/release-please/test/compatibility-test.ts
  packages/release-please/test/fixtures/pull_request_labeled.json
  packages/release-please/test/fixtures/pull_request_labeled_feature_branch.json
  packages/release-please/test/release-please.ts
Labels: size: xl

#4166 deps: update gcf-utils to v14
  packages/generated-files-bot/package-lock.json
  packages/generated-files-bot/package.json
  packages/generated-files-bot/src/generated-files-bot.ts
  packages/generated-files-bot/test/generated-files-bot.ts
  packages/header-checker-lint/package-lock.json
  packages/header-checker-lint/package.json
  packages/header-checker-lint/src/header-checker-lint.ts
  packages/header-checker-lint/test/header-checker-lint.ts
  packages/loadtest-bot/package-lock.json
  packages/loadtest-bot/package.json
Labels: size: xl

#4138 feat(owlbot-bootstrapper): add default cli args
  packages/owlbot-bootstrapper/cli/cli.ts
  packages/owlbot-bootstrapper/cli/package-lock.json
  packages/owlbot-bootstrapper/cli/package.json
  packages/owlbot-bootstrapper/cli/run-trigger-command.ts
  packages/owlbot-bootstrapper/cli/run-trigger.ts
  packages/owlbot-bootstrapper/cli/test/run-trigger.test.ts
  packages/owlbot-bootstrapper/common-container/cloudbuild-deploy-container.yaml
Labels: size: m

#4169 fix: update bad license error message
  packages/policy/src/issue.ts
Labels: automerge, size: xs

#4168 deps(mog): update gcf-utils to v14
  packages/merge-on-green/package-lock.json
  packages/merge-on-green/package.json
  packages/merge-on-green/src/merge-on-green.ts
  packages/merge-on-green/test/merge-logic.ts
  packages/merge-on-green/test/merge-on-green.ts
Labels: size: xl

#4173 feat: bot-config-utils can validate JSONSchema formats
  packages/bot-config-utils/__snapshots__/bot-config-utils.js
  packages/bot-config-utils/package-lock.json
  packages/bot-config-utils/package.json
  packages/bot-config-utils/src/bot-config-utils.ts
  packages/bot-config-utils/test/bot-config-utils.ts
  packages/bot-config-utils/test/fixtures/formats-wrong.yaml
  packages/bot-config-utils/test/fixtures/formats.yaml
  packages/bot-config-utils/test/test-config-formats.json
Labels: size: xl

#4172 deps(owl-bot): update gcf-utils to v14
  packages/owl-bot/package-lock.json
  packages/owl-bot/package.json
  packages/owl-bot/src/copy-code.ts
  packages/owl-bot/src/core.ts
  packages/owl-bot/src/create-pr.ts
  packages/owl-bot/src/handlers.ts
  packages/owl-bot/src/octokit-util.ts
  packages/owl-bot/src/owl-bot.ts
  packages/owl-bot/src/scan-googleapis-gen-and-create-pull-requests.ts
  packages/owl-bot/test/fake-octokit.ts
  packages/owl-bot/test/owl-bot.ts
  packages/owl-bot/test/owl-core.ts
  packages/owl-bot/test/scan-googleapis-gen-and-create-pull-requests.ts
  packages/owl-bot/test/update-lock.ts
Labels: size: xl

#4175 deps(policy): update gcf-utils to v14
  packages/policy/package-lock.json
  packages/policy/package.json
  packages/policy/src/bot.ts
  packages/policy/test/test.bot.ts
  packages/policy/test/test.policy.ts
Labels: size: xl

#4171 deps: update release-please to 14.1.0
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: size: m

#4176 deps(release-trigger): update gcf-utils to v14
  packages/release-trigger/package-lock.json
  packages/release-trigger/package.json
  packages/release-trigger/src/bot.ts
  packages/release-trigger/src/release-trigger.ts
  packages/release-trigger/src/server-frontend.ts
  packages/release-trigger/test/bot.ts
Labels: size: xl

#4177 deps(repo-metadata-lint): update gcf-utils to v14
  packages/repo-metadata-lint/package-lock.json
  packages/repo-metadata-lint/package.json
  packages/repo-metadata-lint/src/file-iterator.ts
  packages/repo-metadata-lint/src/issue-opener.ts
  packages/repo-metadata-lint/src/repo-metadata-lint.ts
  packages/repo-metadata-lint/src/utils/octokit-util.ts
  packages/repo-metadata-lint/src/validate.ts
  packages/repo-metadata-lint/test/issue-opener.ts
  packages/repo-metadata-lint/test/repo-metadata-lint.ts
  packages/repo-metadata-lint/test/validate.ts
Labels: size: xl

#4179 deps(sync-repo-settings): update gcf-utils to v14
  packages/sync-repo-settings/package-lock.json
  packages/sync-repo-settings/package.json
  packages/sync-repo-settings/src/bot.ts
  packages/sync-repo-settings/src/sync-repo-settings.ts
  packages/sync-repo-settings/test/compatibility-test.ts
  packages/sync-repo-settings/test/fixtures/repository_transferred.json
  packages/sync-repo-settings/test/test.bot.ts
Labels: size: xl

#4180 deps(trusted-contribution): update gcf-utils to v14
  packages/trusted-contribution/package-lock.json
  packages/trusted-contribution/package.json
  packages/trusted-contribution/src/trusted-contribution.ts
  packages/trusted-contribution/test/trusted-contribution.ts
  packages/trusted-contribution/test/validation-test.ts
Labels: size: xl

#4178 deps(snippet-bot): update gcf-utils to v14
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/package.json
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/test/snippet-bot.ts
Labels: size: xl

#4183 deps(owlbot-bootstrapper): update dependencies
  packages/owlbot-bootstrapper/app/package-lock.json
  packages/owlbot-bootstrapper/app/package.json
  packages/owlbot-bootstrapper/cli/package-lock.json
  packages/owlbot-bootstrapper/cli/package.json
  packages/owlbot-bootstrapper/common-container/package-lock.json
  packages/owlbot-bootstrapper/common-container/package.json
  packages/owlbot-bootstrapper/package-lock.json
  packages/owlbot-bootstrapper/package.json
Labels: size: xl

#4185 build: remove docs test
  .github/workflows/ci.yaml
Labels: size: s

#4186 build: add link checking cron
  .github/workflows/links.yaml
Labels: size: s

#4189 fix: fix labels in links.yaml
  .github/workflows/links.yaml
Labels: size: xs

#4187 build: update repo names in AR for owlbot-bootstrapper images
  packages/owlbot-bootstrapper/common-container/cloudbuild-deploy-container.yaml
Labels: size: xs

#4190 chore: limit concurrency for link checking job
  .github/workflows/links.yaml
Labels: size: xs

#4202 fix(owlbot-bootstrapper): push docker image to artifact registry
  packages/owlbot-bootstrapper/common-container/cloudbuild-deploy-container.yaml
Labels: size: xs

#4201 fix: forcing npm audit fix
  scripts/update-dependencies.sh
Labels: size: s

#4236 deps: update dependencies
  packages/auto-approve/package-lock.json
  packages/auto-approve/package.json
  packages/bot-config-utils/package-lock.json
  packages/bot-config-utils/package.json
  packages/datastore-lock/package-lock.json
  packages/datastore-lock/package.json
  packages/label-sync/package-lock.json
  packages/label-sync/package.json
  packages/secret-rotator/package-lock.json
  packages/secret-rotator/package.json
Labels: size: xl

#4242 fix(owlbot-bootstrapper): spacing typo
  packages/owlbot-bootstrapper/common-container/cloudbuild-deploy-container.yaml
Labels: size: xs

#4245 build: use PROJECT_ID
  packages/owlbot-bootstrapper/common-container/cloudbuild-deploy-container.yaml
Labels: size: xs

#4246 chore: update repo name for packages in AR
  packages/owlbot-bootstrapper/cli/run-trigger-command.ts
  packages/owlbot-bootstrapper/cli/run-trigger.ts
  packages/owlbot-bootstrapper/cli/test/run-trigger.test.ts
Labels: size: s

#4243 fix(snippet-bot): stop using node-fetch
  packages/snippet-bot/__snapshots__/snippet-bot.js
  packages/snippet-bot/package-lock.json
  packages/snippet-bot/package.json
  packages/snippet-bot/src/region-tag-parser.ts
  packages/snippet-bot/src/snippet-bot.ts
  packages/snippet-bot/src/utils.ts
  packages/snippet-bot/test/snippet-bot.ts
Labels: size: xl

#4244 deps: update release-please to v14.2.1
  packages/release-please/package-lock.json
  packages/release-please/package.json
  packages/release-please/src/release-please.ts
  packages/release-please/test/release-please.ts
Labels: size: xl

#4252 fix(snippet-bot): make formatBody resilient to an empty body
  packages/snippet-bot/src/utils.ts
  packages/snippet-bot/test/utils.ts
Labels: size: s

#4254 fix(snippet-bot): convert null value to an empty string
  packages/snippet-bot/src/utils.ts
  packages/snippet-bot/test/utils.ts
Labels: size: xs

#4284 fix: look at pull `merged` field to determine merged status
  packages/cherry-pick-bot/src/bot.ts
  packages/cherry-pick-bot/test/bot.ts
Labels: size: s

#4288 deps: update release-please to v14.2.2
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: automerge, size: xl

#4289 deps: update releasetool to 1.8.7
  packages/release-trigger/requirements.txt
Labels: size: xs

#4294 chore: configure renovate to use commit hash for github actions
  .github/workflows/links.yaml
  renovate.json
Labels: size: xs

#4293 deps: update release-please to v14.2.4
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: size: xs

#4255 deps(owl-bot): update dependencies
  packages/owl-bot/package-lock.json
  packages/owl-bot/package.json
  packages/owl-bot/src/docker-api.ts
  packages/owl-bot/test/docker-api.ts
  packages/owl-bot/test/fixtures/manifests.json
Labels: size: l

#4299 feat: add ability to find files by glob
  packages/git-file-utils/package-lock.json
  packages/git-file-utils/package.json
  packages/git-file-utils/src/git-file-utils.ts
  packages/git-file-utils/test/find-files.ts
Labels: size: xl

#4297 feat(sentence-case): enable sentence-case plugin for googleapis
  packages/release-please/package-lock.json
  packages/release-please/package.json
  packages/release-please/src/release-please.ts
  packages/release-please/test/release-please.ts
Labels: size: m
