Repository googleapis/repo-automation-bots, pull requests merged in 2022-07, with the labels that each got.

#4033 feat(owlbot-bootstrapper): add PR copy-tag info, and API ID info in PR title
  packages/owlbot-bootstrapper/app/package-lock.json
  packages/owlbot-bootstrapper/cli/cloudbuild-owlbot-bootstrapper.yaml
  packages/owlbot-bootstrapper/cli/package-lock.json
  packages/owlbot-bootstrapper/common-container/__snapshots__/utils.test.js
  packages/owlbot-bootstrapper/common-container/commands/post-process.ts
  packages/owlbot-bootstrapper/common-container/commands/pre-process.ts
  packages/owlbot-bootstrapper/common-container/interfaces.ts
  packages/owlbot-bootstrapper/common-container/mono-repo.ts
  packages/owlbot-bootstrapper/common-container/package-lock.json
  packages/owlbot-bootstrapper/common-container/post-process.ts
  packages/owlbot-bootstrapper/common-container/pre-process.ts
  packages/owlbot-bootstrapper/common-container/split-repo.ts
  packages/owlbot-bootstrapper/common-container/test/mono-repo.test.ts
  packages/owlbot-bootstrapper/common-container/test/split-repo.test.ts
  packages/owlbot-bootstrapper/common-container/test/utils.test.ts
  packages/owlbot-bootstrapper/common-container/utils.ts
Labels: size: xl

#4028 fix: add etag retry logic
  packages/auto-approve/__snapshots__/auto-approve.test.js
  packages/auto-approve/src/auto-approve.ts
  packages/auto-approve/test/auto-approve.test.ts
Labels: size: m

#4044 fix(deps): update release-please to 13.19.2
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: size: s

#4045 feat: add MultiConfigChecker to validate multiple schemas in a single pass
  packages/bot-config-utils/__snapshots__/bot-config-utils.js
  packages/bot-config-utils/__snapshots__/multi-config-checker.js
  packages/bot-config-utils/src/bot-config-utils.ts
  packages/bot-config-utils/test/fixtures/broken.json
  packages/bot-config-utils/test/fixtures/config.json
  packages/bot-config-utils/test/fixtures/empty.json
  packages/bot-config-utils/test/fixtures/wrong.json
  packages/bot-config-utils/test/multi-config-checker.ts
  packages/bot-config-utils/test/test-config-schema.json
Labels: automerge, size: l

#4050 feat: add new issue-utils package
  .release-please-manifest.json
  packages/issue-utils/.c8rc.json
  packages/issue-utils/.eslintignore
  packages/issue-utils/.eslintrc.json
  packages/issue-utils/.gitignore
  packages/issue-utils/.mocharc.js
  packages/issue-utils/.prettierignore
  packages/issue-utils/.prettierrc.js
  packages/issue-utils/LICENSE
  packages/issue-utils/README.md
  packages/issue-utils/package-lock.json
  packages/issue-utils/package.json
  packages/issue-utils/src/issue-utils.ts
  packages/issue-utils/test/issue-utils.ts
  packages/issue-utils/tsconfig.json
  release-please-config.json
Labels: size: xl

#4056 deps: update release-please to 13.19.3
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: size: s

#4051 deps: update gcf-utils to 13.8.3
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: size: m

#4063 fix: add source link hash in owlbot-bootstrapper
  packages/owlbot-bootstrapper/common-container/__snapshots__/utils.test.js
  packages/owlbot-bootstrapper/common-container/utils.ts
Labels: size: xs

#4047 feat: validate manifest config files on pull requests
  packages/release-please/__snapshots__/compatibility-test.js
  packages/release-please/package-lock.json
  packages/release-please/package.json
  packages/release-please/src/release-please.ts
  packages/release-please/test/compatibility-test.ts
  packages/release-please/test/fixtures/manifest-config/extra_field.json
  packages/release-please/test/fixtures/manifest-config/invalid.json
  packages/release-please/test/fixtures/manifest-config/missing_required.json
  packages/release-please/test/fixtures/manifest-config/valid.json
  packages/release-please/test/fixtures/manifest/invalid.json
  packages/release-please/test/fixtures/manifest/valid.json
Labels: bot: release please, size: l

#4065 fix: get latest sha from googleapis-gen, and add missing 'https' in PR body
  packages/owlbot-bootstrapper/common-container/__snapshots__/utils.test.js
  packages/owlbot-bootstrapper/common-container/test/utils.test.ts
  packages/owlbot-bootstrapper/common-container/utils.ts
Labels: size: s

#4066 fix(owlbot-bootstrapper): add Copy-Tag logic in commit as well
  packages/owlbot-bootstrapper/common-container/__snapshots__/utils.test.js
  packages/owlbot-bootstrapper/common-container/mono-repo.ts
  packages/owlbot-bootstrapper/common-container/split-repo.ts
  packages/owlbot-bootstrapper/common-container/test/mono-repo.test.ts
  packages/owlbot-bootstrapper/common-container/test/split-repo.test.ts
  packages/owlbot-bootstrapper/common-container/test/utils.test.ts
  packages/owlbot-bootstrapper/common-container/utils.ts
Labels: size: m

#4070 chore: remove unused env variables
  packages/owlbot-bootstrapper/common-container/post-process.ts
  packages/owlbot-bootstrapper/common-container/pre-process.ts
Labels: size: xs

#4069 fix: Reduce race condition window for appending PR
  packages/owl-bot/src/copy-code.ts
Labels: size: s

#4075 fix: remove line length checks that are not part of the conventional …
  packages/conventional-commit-lint/__snapshots__/conventional-commit-lint.js
  packages/conventional-commit-lint/src/utils.ts
  packages/conventional-commit-lint/test/conventional-commit-lint.ts
  packages/conventional-commit-lint/test/fixtures/commit_with_long_body_line_length.json
Labels: size: m

#4074 feat: implement owlbot:copy-code label
  packages/owl-bot/cloud-build/copy-code-again.yaml
  packages/owl-bot/src/bin/commands/copy-code-into-pull-request.ts
  packages/owl-bot/src/bin/commands/test-webhook.ts
  packages/owl-bot/src/copy-code.ts
  packages/owl-bot/src/core.ts
  packages/owl-bot/src/labels.ts
  packages/owl-bot/src/owl-bot.ts
  packages/owl-bot/test/core.ts
  packages/owl-bot/test/owl-bot.ts
  packages/owl-bot/test/scan-googleapis-gen-and-create-pull-requests.ts
Labels: size: l

#4080 fix: pass the action to copy-code-into-pull-request
  packages/owl-bot/cloud-build/copy-code-again.yaml
Labels: size: xs

#4082 feat: sync-repo-settings opens an issue on installed repo for bad config
  packages/sync-repo-settings/package-lock.json
  packages/sync-repo-settings/package.json
  packages/sync-repo-settings/src/bot.ts
  packages/sync-repo-settings/test/fixtures/malformed.yaml
  packages/sync-repo-settings/test/test.bot.ts
Labels: size: l

#4085 docs(sync-repo-settings): describe all supported options
  packages/sync-repo-settings/README.md
Labels: size: s

#4086 feat(auto-approve): run on edits to PRs as well
  packages/auto-approve/src/auto-approve.ts
Labels: size: xs

#4084 chore: cleanup warning logs from unnecessary default wrap option
  packages/sync-repo-settings/src/app.ts
Labels: automerge, size: xs

#4079 fix(owlbot-bootstrapper): remove regenerate textbox process, use owlbot:copy-code label instead
  packages/owlbot-bootstrapper/common-container/__snapshots__/utils.test.js
  packages/owlbot-bootstrapper/common-container/mono-repo.ts
  packages/owlbot-bootstrapper/common-container/split-repo.ts
  packages/owlbot-bootstrapper/common-container/test/mono-repo.test.ts
  packages/owlbot-bootstrapper/common-container/test/split-repo.test.ts
  packages/owlbot-bootstrapper/common-container/test/utils.test.ts
  packages/owlbot-bootstrapper/common-container/utils.ts
Labels: size: m

#4088 fix(ccl): change the order of the error message
  packages/conventional-commit-lint/__snapshots__/conventional-commit-lint.js
  packages/conventional-commit-lint/src/utils.ts
Labels: size: s

#4089 chore(owlbot-bootstrapper): update email address to match name
  packages/owlbot-bootstrapper/common-container/__snapshots__/utils.test.js
  packages/owlbot-bootstrapper/common-container/utils.ts
Labels: size: xs

#4090 chore: cleanup warning logs from unnecessary default wrap option
  packages/header-checker-lint/src/app.ts
Labels: size: xs

#4091 deps: update release-please to 13.19.6
  packages/release-please/package-lock.json
  packages/release-please/package.json
Labels: size: s
